// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"github.com/mutuals/go-mutuals/service/persist"
)

func (r *Claim) ID() GqlID {
	return GqlID(fmt.Sprintf("Claim:%s", r.Dbid))
}

func (r *DeletedNode) ID() GqlID {
	return GqlID(fmt.Sprintf("DeletedNode:%s", r.Dbid))
}

func (r *Pool) ID() GqlID {
	return GqlID(fmt.Sprintf("Pool:%s", r.Dbid))
}

func (r *User) ID() GqlID {
	return GqlID(fmt.Sprintf("User:%s", r.Dbid))
}

func (r *Viewer) ID() GqlID {
	//-----------------------------------------------------------------------------------------------
	//-----------------------------------------------------------------------------------------------
	// Some fields specified by @goGqlId require manual binding because one of the following is true:
	// (a) the field does not exist on the Viewer type, or
	// (b) the field exists but is not a string type
	//-----------------------------------------------------------------------------------------------
	// Please create binding methods on the Viewer type with the following signatures:
	// func (r *Viewer) GetGqlIDField_UserID() string
	//-----------------------------------------------------------------------------------------------
	return GqlID(fmt.Sprintf("Viewer:%s", r.GetGqlIDField_UserID()))
}

type NodeFetcher struct {
	OnClaim       func(ctx context.Context, dbid persist.DBID) (*Claim, error)
	OnDeletedNode func(ctx context.Context, dbid persist.DBID) (*DeletedNode, error)
	OnPool        func(ctx context.Context, dbid persist.DBID) (*Pool, error)
	OnUser        func(ctx context.Context, dbid persist.DBID) (*User, error)
	OnViewer      func(ctx context.Context, userId string) (*Viewer, error)
}

func (n *NodeFetcher) GetNodeByGqlID(ctx context.Context, id GqlID) (Node, error) {
	parts := strings.Split(string(id), ":")
	if len(parts) == 1 {
		return nil, ErrInvalidIDFormat{message: "no ID components specified after type name"}
	}

	typeName := parts[0]
	ids := parts[1:]

	switch typeName {
	case "Claim":
		if len(ids) != 1 {
			return nil, ErrInvalidIDFormat{message: fmt.Sprintf("'Claim' type requires 1 ID component(s) (%d component(s) supplied)", len(ids))}
		}
		return n.OnClaim(ctx, persist.DBID(ids[0]))
	case "DeletedNode":
		if len(ids) != 1 {
			return nil, ErrInvalidIDFormat{message: fmt.Sprintf("'DeletedNode' type requires 1 ID component(s) (%d component(s) supplied)", len(ids))}
		}
		return n.OnDeletedNode(ctx, persist.DBID(ids[0]))
	case "Pool":
		if len(ids) != 1 {
			return nil, ErrInvalidIDFormat{message: fmt.Sprintf("'Pool' type requires 1 ID component(s) (%d component(s) supplied)", len(ids))}
		}
		return n.OnPool(ctx, persist.DBID(ids[0]))
	case "User":
		if len(ids) != 1 {
			return nil, ErrInvalidIDFormat{message: fmt.Sprintf("'User' type requires 1 ID component(s) (%d component(s) supplied)", len(ids))}
		}
		return n.OnUser(ctx, persist.DBID(ids[0]))
	case "Viewer":
		if len(ids) != 1 {
			return nil, ErrInvalidIDFormat{message: fmt.Sprintf("'Viewer' type requires 1 ID component(s) (%d component(s) supplied)", len(ids))}
		}
		return n.OnViewer(ctx, string(ids[0]))
	}

	return nil, ErrInvalidIDFormat{typeName}
}

func (n *NodeFetcher) ValidateHandlers() {
	switch {
	case n.OnClaim == nil:
		panic("NodeFetcher handler validation failed: no handler set for NodeFetcher.OnClaim")
	case n.OnDeletedNode == nil:
		panic("NodeFetcher handler validation failed: no handler set for NodeFetcher.OnDeletedNode")
	case n.OnPool == nil:
		panic("NodeFetcher handler validation failed: no handler set for NodeFetcher.OnPool")
	case n.OnUser == nil:
		panic("NodeFetcher handler validation failed: no handler set for NodeFetcher.OnUser")
	case n.OnViewer == nil:
		panic("NodeFetcher handler validation failed: no handler set for NodeFetcher.OnViewer")
	}
}
