// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/mutuals/go-mutuals/service/persist"
)

type AddUserWalletResult interface {
	IsAddUserWalletResult()
}

type AuthorizationError interface {
	IsAuthorizationError()
}

type ClaimBulkCreateResult interface {
	IsClaimBulkCreateResult()
}

type ClaimBulkDeleteResult interface {
	IsClaimBulkDeleteResult()
}

type ClaimBulkUpdateResult interface {
	IsClaimBulkUpdateResult()
}

type ClaimCreateResult interface {
	IsClaimCreateResult()
}

type ClaimDeleteResult interface {
	IsClaimDeleteResult()
}

type ClaimUpdateResult interface {
	IsClaimUpdateResult()
}

type Error interface {
	IsError()
}

type LoginResult interface {
	IsLoginResult()
}

type Node interface {
	IsNode()
}

type PoolCreateResult interface {
	IsPoolCreateResult()
}

type PoolDeleteResult interface {
	IsPoolDeleteResult()
}

type PoolOrUserOrEVMAccount interface {
	IsPoolOrUserOrEVMAccount()
}

type PoolResult interface {
	IsPoolResult()
}

type PoolUpdateResult interface {
	IsPoolUpdateResult()
}

type RemoveUserWalletsResult interface {
	IsRemoveUserWalletsResult()
}

type RoleUpdateResult interface {
	IsRoleUpdateResult()
}

type SearchPoolsResult interface {
	IsSearchPoolsResult()
}

type SearchUsersResult interface {
	IsSearchUsersResult()
}

type UserDeleteResult interface {
	IsUserDeleteResult()
}

type UserOrEVMAccount interface {
	IsUserOrEVMAccount()
}

type UserRegisterResult interface {
	IsUserRegisterResult()
}

type UserResult interface {
	IsUserResult()
}

type UserUpdateResult interface {
	IsUserUpdateResult()
}

type VerifyTokenResult interface {
	IsVerifyTokenResult()
}

type AddUserWalletPayload struct {
	Viewer *User `json:"viewer"`
}

func (AddUserWalletPayload) IsAddUserWalletResult() {}

type Claim struct {
	Data         persist.JSON           `json:"data"`
	Label        string                 `json:"label"`
	Path         string                 `json:"path"`
	Parent       *Claim                 `json:"parent"`
	Children     []*Claim               `json:"children"`
	Pool         *Pool                  `json:"pool"`
	Recipient    PoolOrUserOrEVMAccount `json:"recipient"`
	Validation   *Module                `json:"validation"`
	Distribution *Module                `json:"distribution"`
	CreatedAt    time.Time              `json:"createdAt"`
	UpdatedAt    time.Time              `json:"updatedAt"`
}

func (Claim) IsNode() {}

type ClaimBulkCreateInput struct {
	Data           persist.JSON `json:"data"`
	Parent         *GqlID       `json:"parent"`
	Children       []GqlID      `json:"children"`
	ValidationID   string       `json:"validationId"`
	DistributionID string       `json:"distributionId"`
}

type ClaimBulkCreatePayload struct {
	Count  int      `json:"count"`
	Claims []*Claim `json:"claims"`
}

func (ClaimBulkCreatePayload) IsClaimBulkCreateResult() {}

type ClaimBulkDeletePayload struct {
	Count int `json:"count"`
}

func (ClaimBulkDeletePayload) IsClaimBulkDeleteResult() {}

type ClaimBulkUpdateInput struct {
	ClaimID        GqlID        `json:"claimId"`
	Data           persist.JSON `json:"data"`
	Parent         *GqlID       `json:"parent"`
	Children       []GqlID      `json:"children"`
	ValidationID   *string      `json:"validationId"`
	DistributionID *string      `json:"distributionId"`
}

type ClaimBulkUpdatePayload struct {
	Count  int      `json:"count"`
	Claims []*Claim `json:"claims"`
}

func (ClaimBulkUpdatePayload) IsClaimBulkUpdateResult() {}

type ClaimCreateInput struct {
	Label          string       `json:"label"`
	Data           persist.JSON `json:"data"`
	Parent         *string      `json:"parent"`
	Children       []string     `json:"children"`
	ValidationID   string       `json:"validationId"`
	DistributionID string       `json:"distributionId"`
}

type ClaimCreatePayload struct {
	Claim *Claim `json:"claim"`
}

func (ClaimCreatePayload) IsClaimCreateResult() {}

type ClaimDeletePayload struct {
	Claim *Claim `json:"claim"`
}

func (ClaimDeletePayload) IsClaimDeleteResult() {}

type ClaimUpdateInput struct {
	ClaimID        GqlID        `json:"claimId"`
	Data           persist.JSON `json:"data"`
	Parent         *GqlID       `json:"parent"`
	Children       []GqlID      `json:"children"`
	ValidationID   *string      `json:"validationId"`
	DistributionID *string      `json:"distributionId"`
}

type ClaimUpdatePayload struct {
	Claim *Claim `json:"claim"`
}

func (ClaimUpdatePayload) IsClaimUpdateResult() {}

type DeletedNode struct {
}

func (DeletedNode) IsNode() {}

type Deposit struct {
	ID          GqlID             `json:"id"`
	Transaction *Tx               `json:"transaction"`
	Pool        *Pool             `json:"pool"`
	Token       *Token            `json:"token"`
	From        persist.Address   `json:"from"`
	To          persist.Address   `json:"to"`
	Origin      string            `json:"origin"`
	Amount      persist.HexString `json:"amount"`
	LogIndex    *int              `json:"logIndex"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type EVMAccount struct {
	ID          GqlID           `json:"id"`
	Address     persist.Address `json:"address"`
	AccountType EVMAccountType  `json:"accountType"`
	SelfPools   []*Pool         `json:"selfPools"`
	Balances    []*TokenBalance `json:"balances"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

func (EVMAccount) IsUserOrEVMAccount()       {}
func (EVMAccount) IsPoolOrUserOrEVMAccount() {}

type ErrAddressOwnedByUser struct {
	Message string `json:"message"`
}

func (ErrAddressOwnedByUser) IsError()               {}
func (ErrAddressOwnedByUser) IsAddUserWalletResult() {}

type ErrAuthenticationFailed struct {
	Message string `json:"message"`
}

func (ErrAuthenticationFailed) IsError()               {}
func (ErrAuthenticationFailed) IsUserRegisterResult()  {}
func (ErrAuthenticationFailed) IsAddUserWalletResult() {}
func (ErrAuthenticationFailed) IsLoginResult()         {}

type ErrDoesNotOwnRequiredToken struct {
	Message string `json:"message"`
}

func (ErrDoesNotOwnRequiredToken) IsError()              {}
func (ErrDoesNotOwnRequiredToken) IsAuthorizationError() {}
func (ErrDoesNotOwnRequiredToken) IsUserRegisterResult() {}
func (ErrDoesNotOwnRequiredToken) IsLoginResult()        {}

type ErrInvalidInput struct {
	Message    string   `json:"message"`
	Parameters []string `json:"parameters"`
	Reasons    []string `json:"reasons"`
}

func (ErrInvalidInput) IsError()                   {}
func (ErrInvalidInput) IsUserResult()              {}
func (ErrInvalidInput) IsPoolResult()              {}
func (ErrInvalidInput) IsSearchUsersResult()       {}
func (ErrInvalidInput) IsSearchPoolsResult()       {}
func (ErrInvalidInput) IsUserRegisterResult()      {}
func (ErrInvalidInput) IsUserUpdateResult()        {}
func (ErrInvalidInput) IsUserDeleteResult()        {}
func (ErrInvalidInput) IsAddUserWalletResult()     {}
func (ErrInvalidInput) IsRemoveUserWalletsResult() {}
func (ErrInvalidInput) IsVerifyTokenResult()       {}
func (ErrInvalidInput) IsRoleUpdateResult()        {}
func (ErrInvalidInput) IsClaimCreateResult()       {}
func (ErrInvalidInput) IsClaimUpdateResult()       {}
func (ErrInvalidInput) IsClaimDeleteResult()       {}
func (ErrInvalidInput) IsClaimBulkCreateResult()   {}
func (ErrInvalidInput) IsClaimBulkUpdateResult()   {}
func (ErrInvalidInput) IsClaimBulkDeleteResult()   {}
func (ErrInvalidInput) IsPoolCreateResult()        {}
func (ErrInvalidInput) IsPoolUpdateResult()        {}
func (ErrInvalidInput) IsPoolDeleteResult()        {}

type ErrInvalidToken struct {
	Message string `json:"message"`
}

func (ErrInvalidToken) IsError()              {}
func (ErrInvalidToken) IsAuthorizationError() {}

type ErrNoCookie struct {
	Message string `json:"message"`
}

func (ErrNoCookie) IsError()              {}
func (ErrNoCookie) IsAuthorizationError() {}

type ErrNotAuthorized struct {
	Message string             `json:"message"`
	Cause   AuthorizationError `json:"cause"`
}

func (ErrNotAuthorized) IsError()                   {}
func (ErrNotAuthorized) IsUserResult()              {}
func (ErrNotAuthorized) IsUserUpdateResult()        {}
func (ErrNotAuthorized) IsUserDeleteResult()        {}
func (ErrNotAuthorized) IsAddUserWalletResult()     {}
func (ErrNotAuthorized) IsRemoveUserWalletsResult() {}
func (ErrNotAuthorized) IsVerifyTokenResult()       {}
func (ErrNotAuthorized) IsRoleUpdateResult()        {}
func (ErrNotAuthorized) IsClaimCreateResult()       {}
func (ErrNotAuthorized) IsClaimUpdateResult()       {}
func (ErrNotAuthorized) IsClaimDeleteResult()       {}
func (ErrNotAuthorized) IsClaimBulkCreateResult()   {}
func (ErrNotAuthorized) IsClaimBulkUpdateResult()   {}
func (ErrNotAuthorized) IsClaimBulkDeleteResult()   {}
func (ErrNotAuthorized) IsPoolCreateResult()        {}
func (ErrNotAuthorized) IsPoolUpdateResult()        {}
func (ErrNotAuthorized) IsPoolDeleteResult()        {}

type ErrPoolNotFound struct {
	Message string `json:"message"`
}

func (ErrPoolNotFound) IsError()                 {}
func (ErrPoolNotFound) IsPoolResult()            {}
func (ErrPoolNotFound) IsClaimCreateResult()     {}
func (ErrPoolNotFound) IsClaimUpdateResult()     {}
func (ErrPoolNotFound) IsClaimDeleteResult()     {}
func (ErrPoolNotFound) IsClaimBulkCreateResult() {}
func (ErrPoolNotFound) IsClaimBulkUpdateResult() {}
func (ErrPoolNotFound) IsClaimBulkDeleteResult() {}
func (ErrPoolNotFound) IsPoolUpdateResult()      {}
func (ErrPoolNotFound) IsPoolDeleteResult()      {}

type ErrSessionInvalidated struct {
	Message string `json:"message"`
}

func (ErrSessionInvalidated) IsError()              {}
func (ErrSessionInvalidated) IsAuthorizationError() {}

type ErrSyncFailed struct {
	Message string `json:"message"`
}

func (ErrSyncFailed) IsError() {}

type ErrTokenNotFound struct {
	Message string `json:"message"`
}

func (ErrTokenNotFound) IsError() {}

type ErrUserAlreadyExists struct {
	Message string `json:"message"`
}

func (ErrUserAlreadyExists) IsError()              {}
func (ErrUserAlreadyExists) IsUserRegisterResult() {}

type ErrUserNotFound struct {
	Message string `json:"message"`
}

func (ErrUserNotFound) IsError()       {}
func (ErrUserNotFound) IsUserResult()  {}
func (ErrUserNotFound) IsLoginResult() {}

type ErrUsernameNotAvailable struct {
	Message string `json:"message"`
}

func (ErrUsernameNotAvailable) IsError()            {}
func (ErrUsernameNotAvailable) IsUserUpdateResult() {}

type LoginPayload struct {
	Viewer *User `json:"viewer"`
}

func (LoginPayload) IsLoginResult() {}

type LogoutPayload struct {
	Viewer *User `json:"viewer"`
}

type Module struct {
	ID             GqlID           `json:"id"`
	Address        persist.Address `json:"address"`
	ChainID        int             `json:"chainId"`
	ModuleRegistry *ModuleRegistry `json:"moduleRegistry"`
	ModuleID       string          `json:"moduleId"`
	ModuleType     ModuleType      `json:"moduleType"`
	Permissions    []string        `json:"permissions"`
	Data           persist.JSON    `json:"data"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

type ModuleRegistry struct {
	ID          GqlID           `json:"id"`
	Address     persist.Address `json:"address"`
	ChainID     int             `json:"chainId"`
	ModuleCount int             `json:"moduleCount"`
	Owner       *EVMAccount     `json:"owner"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type PageInfo struct {
	Total           *int   `json:"total"`
	Size            int    `json:"size"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	HasNextPage     bool   `json:"hasNextPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
}

type Pool struct {
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Image       string           `json:"image"`
	DonationBps int              `json:"donationBps"`
	Slug        string           `json:"slug"`
	Status      PoolStatus       `json:"status"`
	Owner       UserOrEVMAccount `json:"owner"`
	Contract    *PoolContract    `json:"contract"`
	Claims      []*Claim         `json:"claims"`
	CreatedAt   time.Time        `json:"createdAt"`
	UpdatedAt   time.Time        `json:"updatedAt"`
}

func (Pool) IsNode()                   {}
func (Pool) IsPoolOrUserOrEVMAccount() {}
func (Pool) IsPoolResult()             {}

type PoolContract struct {
	ID          GqlID              `json:"id"`
	Address     persist.Address    `json:"address"`
	ChainID     int                `json:"chainId"`
	Status      PoolStatus         `json:"status"`
	PoolFactory *PoolFactory       `json:"poolFactory"`
	Account     *EVMAccount        `json:"account"`
	Owner       *EVMAccount        `json:"owner"`
	DayBalance  []*PoolDayBalance  `json:"dayBalance"`
	HourBalance []*PoolHourBalance `json:"hourBalance"`
	Deposits    []*Deposit         `json:"deposits"`
	Withdrawals []*Withdrawal      `json:"withdrawals"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

type PoolCreateInput struct {
	Owner       *string             `json:"owner"`
	Private     *bool               `json:"private"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	Image       *string             `json:"image"`
	DonationBps *int                `json:"donationBps"`
	Slug        string              `json:"slug"`
	AddClaims   []*ClaimCreateInput `json:"addClaims"`
}

type PoolCreatePayload struct {
	Pool *Pool `json:"pool"`
}

func (PoolCreatePayload) IsPoolCreateResult() {}

type PoolDayBalance struct {
	ID        GqlID             `json:"id"`
	ChainID   int               `json:"chainId"`
	Date      time.Time         `json:"date"`
	Pool      *Pool             `json:"pool"`
	Token     *Token            `json:"token"`
	Amount    persist.HexString `json:"amount"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

type PoolDeletePayload struct {
	Pool *Pool `json:"pool"`
}

func (PoolDeletePayload) IsPoolDeleteResult() {}

type PoolFactory struct {
	ID        GqlID           `json:"id"`
	Address   persist.Address `json:"address"`
	ChainID   int             `json:"chainId"`
	PoolCount int             `json:"poolCount"`
	Owner     *EVMAccount     `json:"owner"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type PoolHourBalance struct {
	ID        GqlID             `json:"id"`
	ChainID   int               `json:"chainId"`
	Date      time.Time         `json:"date"`
	Pool      *Pool             `json:"pool"`
	Token     *Token            `json:"token"`
	Amount    persist.HexString `json:"amount"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

type PoolSearchResult struct {
	Pool *Pool `json:"pool"`
}

type PoolUpdateInput struct {
	Private      *bool               `json:"private"`
	Name         *string             `json:"name"`
	Description  *string             `json:"description"`
	Image        *string             `json:"image"`
	DonationBps  *int                `json:"donationBps"`
	Slug         *string             `json:"slug"`
	AddClaims    []*ClaimCreateInput `json:"addClaims"`
	UpdateClaims []*ClaimUpdateInput `json:"updateClaims"`
	RemoveClaims []GqlID             `json:"removeClaims"`
}

type PoolUpdatePayload struct {
	Pool *Pool `json:"pool"`
}

func (PoolUpdatePayload) IsPoolUpdateResult() {}

type RemoveUserWalletsPayload struct {
	Viewer *User `json:"viewer"`
}

func (RemoveUserWalletsPayload) IsRemoveUserWalletsResult() {}

type RoleUpdateInput struct {
	AddRoles    []persist.Role `json:"addRoles"`
	RemoveRoles []persist.Role `json:"removeRoles"`
}

type RoleUpdatePayload struct {
	User *User `json:"user"`
}

func (RoleUpdatePayload) IsRoleUpdateResult() {}

type SearchPoolsPayload struct {
	Results []*PoolSearchResult `json:"results"`
}

func (SearchPoolsPayload) IsSearchPoolsResult() {}

type SearchUsersPayload struct {
	Results []*UserSearchResult `json:"results"`
}

func (SearchUsersPayload) IsSearchUsersResult() {}

type Token struct {
	ID           GqlID           `json:"id"`
	Address      persist.Address `json:"address"`
	ChainID      int             `json:"chainId"`
	TokenType    TokenType       `json:"tokenType"`
	Symbol       string          `json:"symbol"`
	Name         string          `json:"name"`
	Decimals     int             `json:"decimals"`
	Logo         *string         `json:"logo"`
	Thumbnail    *string         `json:"thumbnail"`
	Validated    *int            `json:"validated"`
	PossibleSpam *bool           `json:"possibleSpam"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
}

type TokenBalance struct {
	ID        GqlID                  `json:"id"`
	ChainID   int                    `json:"chainId"`
	Token     *Token                 `json:"token"`
	Holder    PoolOrUserOrEVMAccount `json:"holder"`
	Amount    persist.HexString      `json:"amount"`
	CreatedAt time.Time              `json:"createdAt"`
	UpdatedAt time.Time              `json:"updatedAt"`
}

type Tx struct {
	ID          GqlID             `json:"id"`
	GasUsed     persist.HexString `json:"gasUsed"`
	GasPrice    persist.HexString `json:"gasPrice"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
	Deposits    []*Deposit        `json:"deposits"`
	Withdrawals []*Withdrawal     `json:"withdrawals"`
}

type User struct {
	Roles []*persist.Role `json:"roles"`
	Pools []*Pool         `json:"pools"`
}

func (User) IsNode()                   {}
func (User) IsUserOrEVMAccount()       {}
func (User) IsPoolOrUserOrEVMAccount() {}
func (User) IsUserResult()             {}

type UserDeletePayload struct {
	User *User `json:"user"`
}

func (UserDeletePayload) IsUserDeleteResult() {}

type UserEdge struct {
	Node   *User   `json:"node"`
	Cursor *string `json:"cursor"`
}

type UserRegisterPayload struct {
	User                 *User `json:"user"`
	RequiresConfirmation *bool `json:"requiresConfirmation"`
}

func (UserRegisterPayload) IsUserRegisterResult() {}

type UserSearchResult struct {
	User *User `json:"user"`
}

type UserUpdateInput struct {
	Username *string `json:"username"`
}

type UserUpdatePayload struct {
	User *User `json:"user"`
}

func (UserUpdatePayload) IsUserUpdateResult() {}

type UsersConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type VerifyTokenPayload struct {
	User    *User `json:"user"`
	IsValid bool  `json:"isValid"`
}

func (VerifyTokenPayload) IsVerifyTokenResult() {}

type Withdrawal struct {
	ID          GqlID             `json:"id"`
	Transaction *Tx               `json:"transaction"`
	Pool        *Pool             `json:"pool"`
	Token       *Token            `json:"token"`
	From        persist.Address   `json:"from"`
	To          persist.Address   `json:"to"`
	Origin      string            `json:"origin"`
	Amount      persist.HexString `json:"amount"`
	LogIndex    *int              `json:"logIndex"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type EVMAccountType string

const (
	EVMAccountTypeEoa      EVMAccountType = "EOA"
	EVMAccountTypeContract EVMAccountType = "Contract"
)

var AllEVMAccountType = []EVMAccountType{
	EVMAccountTypeEoa,
	EVMAccountTypeContract,
}

func (e EVMAccountType) IsValid() bool {
	switch e {
	case EVMAccountTypeEoa, EVMAccountTypeContract:
		return true
	}
	return false
}

func (e EVMAccountType) String() string {
	return string(e)
}

func (e *EVMAccountType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EVMAccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EVMAccountType", str)
	}
	return nil
}

func (e EVMAccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ErrorPolicyEnum string

const (
	ErrorPolicyEnumIgnoreFailed     ErrorPolicyEnum = "IGNORE_FAILED"
	ErrorPolicyEnumRejectEverything ErrorPolicyEnum = "REJECT_EVERYTHING"
	ErrorPolicyEnumRejectFailedRows ErrorPolicyEnum = "REJECT_FAILED_ROWS"
)

var AllErrorPolicyEnum = []ErrorPolicyEnum{
	ErrorPolicyEnumIgnoreFailed,
	ErrorPolicyEnumRejectEverything,
	ErrorPolicyEnumRejectFailedRows,
}

func (e ErrorPolicyEnum) IsValid() bool {
	switch e {
	case ErrorPolicyEnumIgnoreFailed, ErrorPolicyEnumRejectEverything, ErrorPolicyEnumRejectFailedRows:
		return true
	}
	return false
}

func (e ErrorPolicyEnum) String() string {
	return string(e)
}

func (e *ErrorPolicyEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ErrorPolicyEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ErrorPolicyEnum", str)
	}
	return nil
}

func (e ErrorPolicyEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ModuleType string

const (
	ModuleTypeValidation   ModuleType = "Validation"
	ModuleTypeDistribution ModuleType = "Distribution"
)

var AllModuleType = []ModuleType{
	ModuleTypeValidation,
	ModuleTypeDistribution,
}

func (e ModuleType) IsValid() bool {
	switch e {
	case ModuleTypeValidation, ModuleTypeDistribution:
		return true
	}
	return false
}

func (e ModuleType) String() string {
	return string(e)
}

func (e *ModuleType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ModuleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ModuleType", str)
	}
	return nil
}

func (e ModuleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PoolStatus string

const (
	PoolStatusDraft  PoolStatus = "Draft"
	PoolStatusActive PoolStatus = "Active"
	PoolStatusPaused PoolStatus = "Paused"
)

var AllPoolStatus = []PoolStatus{
	PoolStatusDraft,
	PoolStatusActive,
	PoolStatusPaused,
}

func (e PoolStatus) IsValid() bool {
	switch e {
	case PoolStatusDraft, PoolStatusActive, PoolStatusPaused:
		return true
	}
	return false
}

func (e PoolStatus) String() string {
	return string(e)
}

func (e *PoolStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PoolStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PoolStatus", str)
	}
	return nil
}

func (e PoolStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TokenType string

const (
	TokenTypeErc20   TokenType = "ERC20"
	TokenTypeErc721  TokenType = "ERC721"
	TokenTypeErc1155 TokenType = "ERC1155"
)

var AllTokenType = []TokenType{
	TokenTypeErc20,
	TokenTypeErc721,
	TokenTypeErc1155,
}

func (e TokenType) IsValid() bool {
	switch e {
	case TokenTypeErc20, TokenTypeErc721, TokenTypeErc1155:
		return true
	}
	return false
}

func (e TokenType) String() string {
	return string(e)
}

func (e *TokenType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TokenType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TokenType", str)
	}
	return nil
}

func (e TokenType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
