// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/mutuals/go-mutuals/service/persist"
)

type AddRolesToUserPayloadOrError interface {
	IsAddRolesToUserPayloadOrError()
}

// -------------------------------------------------------------------------------
//
//	MUTATIONS
//
// -------------------------------------------------------------------------------
type AddUserWalletPayloadOrError interface {
	IsAddUserWalletPayloadOrError()
}

type AuthorizationError interface {
	IsAuthorizationError()
}

type CreateUserPayloadOrError interface {
	IsCreateUserPayloadOrError()
}

type Error interface {
	IsError()
}

type LoginPayloadOrError interface {
	IsLoginPayloadOrError()
}

type Node interface {
	IsNode()
}

type Notification interface {
	Node
	IsNotification()
}

type OptInForRolesPayloadOrError interface {
	IsOptInForRolesPayloadOrError()
}

type OptOutForRolesPayloadOrError interface {
	IsOptOutForRolesPayloadOrError()
}

type PoolByIDPayloadOrError interface {
	IsPoolByIDPayloadOrError()
}

type PoolOrUserOrEVMAccount interface {
	IsPoolOrUserOrEVMAccount()
}

type PreverifyEmailPayloadOrError interface {
	IsPreverifyEmailPayloadOrError()
}

type RemoveUserWalletsPayloadOrError interface {
	IsRemoveUserWalletsPayloadOrError()
}

type ResendVerificationEmailPayloadOrError interface {
	IsResendVerificationEmailPayloadOrError()
}

type RevokeRolesFromUserPayloadOrError interface {
	IsRevokeRolesFromUserPayloadOrError()
}

type SearchPoolsPayloadOrError interface {
	IsSearchPoolsPayloadOrError()
}

type SearchUsersPayloadOrError interface {
	IsSearchUsersPayloadOrError()
}

type UnsubscribeFromEmailTypePayloadOrError interface {
	IsUnsubscribeFromEmailTypePayloadOrError()
}

type UpdateEmailNotificationSettingsPayloadOrError interface {
	IsUpdateEmailNotificationSettingsPayloadOrError()
}

type UpdateEmailPayloadOrError interface {
	IsUpdateEmailPayloadOrError()
}

type UpdateUserInfoPayloadOrError interface {
	IsUpdateUserInfoPayloadOrError()
}

type UploadPersistedQueriesPayloadOrError interface {
	IsUploadPersistedQueriesPayloadOrError()
}

type UserByAddressOrError interface {
	IsUserByAddressOrError()
}

type UserByIDOrError interface {
	IsUserByIDOrError()
}

type UserByUsernameOrError interface {
	IsUserByUsernameOrError()
}

type UserOrAccount interface {
	IsUserOrAccount()
}

type VerifyEmailMagicLinkPayloadOrError interface {
	IsVerifyEmailMagicLinkPayloadOrError()
}

type VerifyEmailPayloadOrError interface {
	IsVerifyEmailPayloadOrError()
}

type ViewerOrError interface {
	IsViewerOrError()
}

type AddUserWalletPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (AddUserWalletPayload) IsAddUserWalletPayloadOrError() {}

type AuthMechanism struct {
	Eoa               *EoaAuth               `json:"eoa"`
	GnosisSafe        *GnosisSafeAuth        `json:"gnosisSafe"`
	Debug             *DebugAuth             `json:"debug"`
	MagicLink         *MagicLinkAuth         `json:"magicLink"`
	OneTimeLoginToken *OneTimeLoginTokenAuth `json:"oneTimeLoginToken"`
	Privy             *PrivyAuth             `json:"privy"`
}

type ChainPools struct {
	ChainID *int    `json:"chainId"`
	Pools   []*Pool `json:"pools"`
}

type Claim struct {
	Dbid persist.DBID `json:"dbid"`
	// Extension (strategy and state) specific data.
	Data          persist.JSON           `json:"data"`
	Label         string                 `json:"label"`
	Path          string                 `json:"path"`
	ChildrenCount int                    `json:"childrenCount"`
	Parent        *Claim                 `json:"parent"`
	Children      []*Claim               `json:"children"`
	Pool          *Pool                  `json:"pool"`
	Recipient     PoolOrUserOrEVMAccount `json:"recipient"`
	State         *Extension             `json:"state"`
	Strategy      *Extension             `json:"strategy"`
	CreatedAt     time.Time              `json:"createdAt"`
	UpdatedAt     time.Time              `json:"updatedAt"`
}

func (Claim) IsNode() {}

// Creates claims.
type ClaimBulkCreate struct {
	// Returns how many objects were created.
	Count int `json:"count"`
	// List of the created claims.
	Results []*ClaimBulkResult `json:"results"`
	Errors  []*ClaimBulkError  `json:"errors"`
}

type ClaimBulkCreateInput struct {
	// Claim recipient address.
	RecipientAddress *persist.Address `json:"recipientAddress"`
	// Extension (strategy and state) specific data.
	Data persist.JSON `json:"data"`
	// Parent claim.
	Parent *persist.DBID `json:"parent"`
	// Children claims.
	Children []persist.DBID `json:"children"`
	// State id.
	StateID string `json:"stateId"`
	// Strategy id.
	StrategyID string `json:"strategyId"`
}

// Deletes claims.
type ClaimBulkDelete struct {
	// Returns how many objects were affected.
	Count  int           `json:"count"`
	Errors []*ClaimError `json:"errors"`
}

type ClaimBulkError struct {
	// Path to field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
	Path *string `json:"path"`
	// The error message.
	Message *string `json:"message"`
	// The error code.
	Code ClaimBulkErrorCode `json:"code"`
}

type ClaimBulkResult struct {
	// Claim data.
	Claim *Claim `json:"claim"`
	// List of errors occurred on create attempt.
	Errors []*ClaimBulkError `json:"errors"`
}

// Updates claims.
type ClaimBulkUpdate struct {
	// Returns how many objects were updated.
	Count int `json:"count"`
	// List of the updated claims.
	Results []*ClaimBulkResult `json:"results"`
	Errors  []*ClaimBulkError  `json:"errors"`
}

type ClaimBulkUpdateInput struct {
	// Claim ID.
	ClaimID persist.DBID `json:"claimId"`
	// Claim recipient address.
	RecipientAddress *persist.Address `json:"recipientAddress"`
	// Extension (strategy and state) specific data.
	Data persist.JSON `json:"data"`
	// Parent claim.
	Parent *persist.DBID `json:"parent"`
	// Children claims.
	Children []persist.DBID `json:"children"`
	// State id.
	StateID string `json:"stateId"`
	// Strategy id.
	StrategyID string `json:"strategyId"`
}

// Creates a new claim.
type ClaimCreate struct {
	Errors []*ClaimError `json:"errors"`
	Claim  *Claim        `json:"claim"`
}

type ClaimCreateInput struct {
	// Claim label.
	Label *string `json:"label"`
	// Claim recipient address.
	RecipientAddress *persist.Address `json:"recipientAddress"`
	// Extension (strategy and state) specific data.
	Data persist.JSON `json:"data"`
	// Parent claim label.
	Parent *string `json:"parent"`
	// Children claim labels.
	Children []string `json:"children"`
	// State id.
	StateID string `json:"stateId"`
	// Strategy id.
	StrategyID string `json:"strategyId"`
}

// Deletes a claim.
type ClaimDelete struct {
	Errors []*ClaimError `json:"errors"`
	Claim  *Claim        `json:"claim"`
}

type ClaimError struct {
	// Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
	Field *string `json:"field"`
	// The error message.
	Message *string `json:"message"`
	// The error code.
	Code ClaimErrorCode `json:"code"`
}

// Updates given claim.
type ClaimUpdate struct {
	Errors []*ClaimError `json:"errors"`
	Claim  *Claim        `json:"claim"`
}

type ClaimUpdateInput struct {
	// Claim ID.
	ClaimID persist.DBID `json:"claimId"`
	// Claim recipient address.
	RecipientAddress *persist.Address `json:"recipientAddress"`
	// Extension (strategy and state) specific data.
	Data persist.JSON `json:"data"`
	// Parent claim.
	Parent *persist.DBID `json:"parent"`
	// Children claims.
	Children []persist.DBID `json:"children"`
	// State id.
	StateID string `json:"stateId"`
	// Strategy id.
	StrategyID string `json:"strategyId"`
}

type ClearAllNotificationsPayload struct {
	Notifications []Notification `json:"notifications"`
}

type CreateUserPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (CreateUserPayload) IsCreateUserPayloadOrError() {}

type DebugAuth struct {
	AsUsername         *string                 `json:"asUsername"`
	UserID             *persist.DBID           `json:"userId"`
	ChainAddresses     []*persist.ChainAddress `json:"chainAddresses"`
	DebugToolsPassword *string                 `json:"debugToolsPassword"`
}

type DeletedNode struct {
	Dbid persist.DBID `json:"dbid"`
}

func (DeletedNode) IsNode() {}

type Deposit struct {
	ID          GqlID             `json:"id"`
	Transaction *Tx               `json:"transaction"`
	Pool        *Pool             `json:"pool"`
	Token       *Token            `json:"token"`
	From        persist.Address   `json:"from"`
	To          persist.Address   `json:"to"`
	Origin      string            `json:"origin"`
	Amount      persist.HexString `json:"amount"`
	LogIndex    *int              `json:"logIndex"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type EVMAccount struct {
	ID          GqlID           `json:"id"`
	Address     persist.Address `json:"address"`
	AccountType EVMAccountType  `json:"accountType"`
	SelfPools   []*Pool         `json:"selfPools"`
	Balances    []*TokenBalance `json:"balances"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

func (EVMAccount) IsUserOrAccount()          {}
func (EVMAccount) IsPoolOrUserOrEVMAccount() {}

type EmailNotificationSettings struct {
	UnsubscribedFromAll           bool `json:"unsubscribedFromAll"`
	UnsubscribedFromNotifications bool `json:"unsubscribedFromNotifications"`
}

type EoaAuth struct {
	ChainPubKey *persist.ChainPubKey `json:"chainPubKey"`
	Nonce       string               `json:"nonce"`
	Message     string               `json:"message"`
	Signature   string               `json:"signature"`
}

type ErrAddressOwnedByUser struct {
	Message string `json:"message"`
}

func (ErrAddressOwnedByUser) IsAddUserWalletPayloadOrError() {}
func (ErrAddressOwnedByUser) IsError()                       {}

type ErrAuthenticationFailed struct {
	Message string `json:"message"`
}

func (ErrAuthenticationFailed) IsAddUserWalletPayloadOrError() {}
func (ErrAuthenticationFailed) IsError()                       {}
func (ErrAuthenticationFailed) IsLoginPayloadOrError()         {}
func (ErrAuthenticationFailed) IsCreateUserPayloadOrError()    {}

type ErrCommunityNotFound struct {
	Message string `json:"message"`
}

func (ErrCommunityNotFound) IsError() {}

type ErrDoesNotOwnRequiredToken struct {
	Message string `json:"message"`
}

func (ErrDoesNotOwnRequiredToken) IsAuthorizationError()       {}
func (ErrDoesNotOwnRequiredToken) IsError()                    {}
func (ErrDoesNotOwnRequiredToken) IsLoginPayloadOrError()      {}
func (ErrDoesNotOwnRequiredToken) IsCreateUserPayloadOrError() {}

type ErrInvalidInput struct {
	Message    string   `json:"message"`
	Parameters []string `json:"parameters"`
	Reasons    []string `json:"reasons"`
}

func (ErrInvalidInput) IsUserByUsernameOrError()                         {}
func (ErrInvalidInput) IsUserByIDOrError()                               {}
func (ErrInvalidInput) IsUserByAddressOrError()                          {}
func (ErrInvalidInput) IsSearchUsersPayloadOrError()                     {}
func (ErrInvalidInput) IsSearchPoolsPayloadOrError()                     {}
func (ErrInvalidInput) IsAddUserWalletPayloadOrError()                   {}
func (ErrInvalidInput) IsRemoveUserWalletsPayloadOrError()               {}
func (ErrInvalidInput) IsUpdateUserInfoPayloadOrError()                  {}
func (ErrInvalidInput) IsError()                                         {}
func (ErrInvalidInput) IsCreateUserPayloadOrError()                      {}
func (ErrInvalidInput) IsVerifyEmailPayloadOrError()                     {}
func (ErrInvalidInput) IsPreverifyEmailPayloadOrError()                  {}
func (ErrInvalidInput) IsVerifyEmailMagicLinkPayloadOrError()            {}
func (ErrInvalidInput) IsUpdateEmailPayloadOrError()                     {}
func (ErrInvalidInput) IsResendVerificationEmailPayloadOrError()         {}
func (ErrInvalidInput) IsUpdateEmailNotificationSettingsPayloadOrError() {}
func (ErrInvalidInput) IsUnsubscribeFromEmailTypePayloadOrError()        {}
func (ErrInvalidInput) IsOptInForRolesPayloadOrError()                   {}
func (ErrInvalidInput) IsOptOutForRolesPayloadOrError()                  {}

type ErrInvalidToken struct {
	Message string `json:"message"`
}

func (ErrInvalidToken) IsAuthorizationError() {}
func (ErrInvalidToken) IsError()              {}

type ErrNoCookie struct {
	Message string `json:"message"`
}

func (ErrNoCookie) IsAuthorizationError() {}
func (ErrNoCookie) IsError()              {}

type ErrNotAuthorized struct {
	Message string             `json:"message"`
	Cause   AuthorizationError `json:"cause"`
}

func (ErrNotAuthorized) IsViewerOrError()                        {}
func (ErrNotAuthorized) IsAddUserWalletPayloadOrError()          {}
func (ErrNotAuthorized) IsRemoveUserWalletsPayloadOrError()      {}
func (ErrNotAuthorized) IsUpdateUserInfoPayloadOrError()         {}
func (ErrNotAuthorized) IsError()                                {}
func (ErrNotAuthorized) IsAddRolesToUserPayloadOrError()         {}
func (ErrNotAuthorized) IsRevokeRolesFromUserPayloadOrError()    {}
func (ErrNotAuthorized) IsOptInForRolesPayloadOrError()          {}
func (ErrNotAuthorized) IsOptOutForRolesPayloadOrError()         {}
func (ErrNotAuthorized) IsUploadPersistedQueriesPayloadOrError() {}

type ErrPoolNotFound struct {
	Message string `json:"message"`
}

func (ErrPoolNotFound) IsError()                  {}
func (ErrPoolNotFound) IsPoolByIDPayloadOrError() {}

type ErrPushTokenBelongsToAnotherUser struct {
	Message string `json:"message"`
}

func (ErrPushTokenBelongsToAnotherUser) IsError() {}

type ErrSessionInvalidated struct {
	Message string `json:"message"`
}

func (ErrSessionInvalidated) IsAuthorizationError() {}
func (ErrSessionInvalidated) IsError()              {}

type ErrSyncFailed struct {
	Message string `json:"message"`
}

func (ErrSyncFailed) IsError() {}

type ErrTokenNotFound struct {
	Message string `json:"message"`
}

func (ErrTokenNotFound) IsError() {}

type ErrUserAlreadyExists struct {
	Message string `json:"message"`
}

func (ErrUserAlreadyExists) IsError()                    {}
func (ErrUserAlreadyExists) IsCreateUserPayloadOrError() {}

type ErrUserNotFound struct {
	Message string `json:"message"`
}

func (ErrUserNotFound) IsUserByUsernameOrError() {}
func (ErrUserNotFound) IsUserByIDOrError()       {}
func (ErrUserNotFound) IsUserByAddressOrError()  {}
func (ErrUserNotFound) IsError()                 {}
func (ErrUserNotFound) IsLoginPayloadOrError()   {}

type ErrUsernameNotAvailable struct {
	Message string `json:"message"`
}

func (ErrUsernameNotAvailable) IsUpdateUserInfoPayloadOrError() {}
func (ErrUsernameNotAvailable) IsError()                        {}
func (ErrUsernameNotAvailable) IsCreateUserPayloadOrError()     {}

type Extension struct {
	ID                GqlID              `json:"id"`
	Address           persist.Address    `json:"address"`
	ChainID           int                `json:"chainId"`
	ExtensionRegistry *ExtensionRegistry `json:"extensionRegistry"`
	ExtensionID       string             `json:"extensionId"`
	ExtensionType     ExtensionType      `json:"extensionType"`
	Permissions       []string           `json:"permissions"`
	Data              persist.JSON       `json:"data"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	CreatedAt         time.Time          `json:"createdAt"`
	UpdatedAt         time.Time          `json:"updatedAt"`
}

type ExtensionRegistry struct {
	ID             GqlID           `json:"id"`
	Address        persist.Address `json:"address"`
	ChainID        int             `json:"chainId"`
	ExtensionCount int             `json:"extensionCount"`
	Owner          *EVMAccount     `json:"owner"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

type GnosisSafeAuth struct {
	Address persist.Address `json:"address"`
	Nonce   string          `json:"nonce"`
	Message string          `json:"message"`
}

type GroupNotificationUserEdge struct {
	Node   *User   `json:"node"`
	Cursor *string `json:"cursor"`
}

type GroupNotificationUsersConnection struct {
	HelperGroupNotificationUsersConnectionData
	Edges    []*GroupNotificationUserEdge `json:"edges"`
	PageInfo *PageInfo                    `json:"pageInfo"`
}

type LoginPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (LoginPayload) IsLoginPayloadOrError() {}

type LogoutPayload struct {
	Viewer *Viewer `json:"viewer"`
}

type MagicLinkAuth struct {
	Token string `json:"token"`
}

// Create and get a new nonce and message.
type Nonce struct {
	Nonce   *string `json:"nonce"`
	Message *string `json:"message"`
}

type NotificationEdge struct {
	Node   Notification `json:"node"`
	Cursor *string      `json:"cursor"`
}

type NotificationSettings struct {
	SomeoneViewedYourPool *bool `json:"someoneViewedYourPool"`
}

type NotificationSettingsInput struct {
	SomeoneViewedYourPool *bool `json:"someoneViewedYourPool"`
}

type NotificationsConnection struct {
	HelperNotificationsConnectionData
	Edges       []*NotificationEdge `json:"edges"`
	UnseenCount *int                `json:"unseenCount"`
	PageInfo    *PageInfo           `json:"pageInfo"`
}

type OneTimeLoginTokenAuth struct {
	Token string `json:"token"`
}

type OptInForRolesPayload struct {
	User *User `json:"user"`
}

func (OptInForRolesPayload) IsOptInForRolesPayloadOrError() {}

type OptOutForRolesPayload struct {
	User *User `json:"user"`
}

func (OptOutForRolesPayload) IsOptOutForRolesPayloadOrError() {}

type PageInfo struct {
	Total           *int   `json:"total"`
	Size            int    `json:"size"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	HasNextPage     bool   `json:"hasNextPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
}

type Pool struct {
	Dbid        persist.DBID `json:"dbid"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Image       string       `json:"image"`
	// Basis point donation.
	DonationBps int           `json:"donationBps"`
	Slug        string        `json:"slug"`
	Status      PoolStatus    `json:"status"`
	Owner       UserOrAccount `json:"owner"`
	Contract    *PoolContract `json:"contract"`
	Claims      []*Claim      `json:"claims"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
}

func (Pool) IsNode()                   {}
func (Pool) IsPoolOrUserOrEVMAccount() {}
func (Pool) IsPoolByIDPayloadOrError() {}

type PoolContract struct {
	ID          GqlID              `json:"id"`
	Address     persist.Address    `json:"address"`
	ChainID     int                `json:"chainId"`
	Status      PoolStatus         `json:"status"`
	PoolFactory *PoolFactory       `json:"poolFactory"`
	Account     *EVMAccount        `json:"account"`
	Owner       *EVMAccount        `json:"owner"`
	DayBalance  []*PoolDayBalance  `json:"dayBalance"`
	HourBalance []*PoolHourBalance `json:"hourBalance"`
	Deposits    []*Deposit         `json:"deposits"`
	Withdrawals []*Withdrawal      `json:"withdrawals"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

type PoolCreate struct {
	Errors []*PoolError `json:"errors"`
	Pool   *Pool        `json:"pool"`
}

type PoolCreateInput struct {
	// Name of the pool.
	Owner *string `json:"owner"`
	// Whether a pool is shared with its recipients or not.
	Private *bool `json:"private"`
	// Name of the pool.
	Name *string `json:"name"`
	// Name of the pool.
	Description *string `json:"description"`
	// Name of the pool.
	Image *string `json:"image"`
	// Basis point donation.
	DonationBps *int `json:"donationBps"`
	// Slug of the pool.
	Slug *string `json:"slug"`
	// List of claims to create and assign to the pool.
	AddClaims []*ClaimCreateInput `json:"addClaims"`
}

type PoolDayBalance struct {
	ID        GqlID             `json:"id"`
	ChainID   int               `json:"chainId"`
	Date      time.Time         `json:"date"`
	Pool      *Pool             `json:"pool"`
	Token     *Token            `json:"token"`
	Amount    persist.HexString `json:"amount"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

// Update a pool.
type PoolDelete struct {
	Errors []*PoolError `json:"errors"`
	Pool   *Pool        `json:"pool"`
}

type PoolError struct {
	// Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
	Field *string `json:"field"`
	// The error message.
	Message *string `json:"message"`
	// The error code.
	Code PoolErrorCode `json:"code"`
}

type PoolFactory struct {
	ID        GqlID           `json:"id"`
	Address   persist.Address `json:"address"`
	ChainID   int             `json:"chainId"`
	PoolCount int             `json:"poolCount"`
	Owner     *EVMAccount     `json:"owner"`
	CreatedAt time.Time       `json:"createdAt"`
	UpdatedAt time.Time       `json:"updatedAt"`
}

type PoolHourBalance struct {
	ID        GqlID             `json:"id"`
	ChainID   int               `json:"chainId"`
	Date      time.Time         `json:"date"`
	Pool      *Pool             `json:"pool"`
	Token     *Token            `json:"token"`
	Amount    persist.HexString `json:"amount"`
	CreatedAt time.Time         `json:"createdAt"`
	UpdatedAt time.Time         `json:"updatedAt"`
}

type PoolSearchResult struct {
	Pool *Pool `json:"pool"`
}

// Update a pool.
type PoolUpdate struct {
	Errors []*PoolError `json:"errors"`
	Pool   *Pool        `json:"pool"`
}

type PoolUpdateInput struct {
	// Whether a pool is shared with its recipients or not.
	Private *bool `json:"private"`
	// Name of the pool.
	Name *string `json:"name"`
	// Name of the pool.
	Description *string `json:"description"`
	// Image of the pool.
	Image *string `json:"image"`
	// Basis point donation.
	DonationBps *int `json:"donationBps"`
	// Slug of the pool.
	Slug *string `json:"slug"`
	// List of claims to assign to the pool.
	AddClaims []*ClaimCreateInput `json:"addClaims"`
	// List of claims to assign to the pool.
	UpdateClaims []*ClaimUpdateInput `json:"updateClaims"`
	// List of claims to remove from the pool.
	RemoveClaims []persist.DBID `json:"removeClaims"`
}

type PreverifyEmailInput struct {
	Email persist.Email `json:"email"`
}

type PreverifyEmailPayload struct {
	Email  persist.Email        `json:"email"`
	Result PreverifyEmailResult `json:"result"`
}

func (PreverifyEmailPayload) IsPreverifyEmailPayloadOrError() {}

type PrivyAuth struct {
	Token string `json:"token"`
}

type PushTokenError struct {
	// Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
	Field *string `json:"field"`
	// The error message.
	Message *string `json:"message"`
	// The error code.
	Code PushTokenErrorCode `json:"code"`
}

type PushTokenRegister struct {
	// push token.
	PushToken *string `json:"pushToken"`
	// A user instance.
	User   *User             `json:"user"`
	Errors []*PushTokenError `json:"errors"`
}

type PushTokenRegisterInput struct {
	// Whether a pool is shared with its recipients or not.
	Private *bool `json:"private"`
	// Name of the pool.
	Name *string `json:"name"`
	// Name of the pool.
	Description *string `json:"description"`
	// Slug of the pool.
	Slug *string `json:"slug"`
	// List of claims to assign to the pool.
	AddClaims []persist.DBID `json:"addClaims"`
}

// Update a pool.
type PushTokenUnregister struct {
	// push token.
	PushToken *string `json:"pushToken"`
	// A user instance.
	User   *User             `json:"user"`
	Errors []*PushTokenError `json:"errors"`
}

type PushTokenUnregisterInput struct {
	// Whether a pool is shared with its recipients or not.
	Private *bool `json:"private"`
	// Name of the pool.
	Name *string `json:"name"`
	// Name of the pool.
	Description *string `json:"description"`
	// Slug of the pool.
	Slug *string `json:"slug"`
	// List of claims to assign to the pool.
	AddClaims []persist.DBID `json:"addClaims"`
	// List of claims to remove from the pool.
	RemoveClaims []persist.DBID `json:"removeClaims"`
}

type RemoveUserWalletsPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (RemoveUserWalletsPayload) IsRemoveUserWalletsPayloadOrError() {}

type ResendVerificationEmailPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (ResendVerificationEmailPayload) IsResendVerificationEmailPayloadOrError() {}

type RoleError struct {
	// Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
	Field *string `json:"field"`
	// The error message.
	Message *string `json:"message"`
	// The error code.
	Code RoleErrorCode `json:"code"`
}

// Update role.
type RoleUpdate struct {
	Errors []*RoleError  `json:"errors"`
	Role   *persist.Role `json:"role"`
}

type RoleUpdateInput struct {
	// List of users to assign to a role.
	AddUsers []persist.DBID `json:"addUsers"`
	// List of users to unassign from a role.
	RemoveUsers []persist.DBID `json:"removeUsers"`
}

type SearchPoolsPayload struct {
	Results []*PoolSearchResult `json:"results"`
}

func (SearchPoolsPayload) IsSearchPoolsPayloadOrError() {}

type SearchUsersPayload struct {
	Results []*UserSearchResult `json:"results"`
}

func (SearchUsersPayload) IsSearchUsersPayloadOrError() {}

type Token struct {
	ID           GqlID           `json:"id"`
	Address      persist.Address `json:"address"`
	ChainID      int             `json:"chainId"`
	TokenType    TokenType       `json:"tokenType"`
	Symbol       string          `json:"symbol"`
	Name         string          `json:"name"`
	Decimals     int             `json:"decimals"`
	Logo         *string         `json:"logo"`
	Thumbnail    *string         `json:"thumbnail"`
	Validated    *int            `json:"validated"`
	PossibleSpam *bool           `json:"possibleSpam"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
}

type TokenBalance struct {
	ID        GqlID                  `json:"id"`
	ChainID   int                    `json:"chainId"`
	Token     *Token                 `json:"token"`
	Holder    PoolOrUserOrEVMAccount `json:"holder"`
	Amount    persist.HexString      `json:"amount"`
	CreatedAt time.Time              `json:"createdAt"`
	UpdatedAt time.Time              `json:"updatedAt"`
}

type Tx struct {
	ID          GqlID             `json:"id"`
	GasUsed     persist.HexString `json:"gasUsed"`
	GasPrice    persist.HexString `json:"gasPrice"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
	Deposits    []*Deposit        `json:"deposits"`
	Withdrawals []*Withdrawal     `json:"withdrawals"`
}

type UnsubscribeFromEmailTypeInput struct {
	Type  EmailUnsubscriptionType `json:"type"`
	Token string                  `json:"token"`
}

type UnsubscribeFromEmailTypePayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UnsubscribeFromEmailTypePayload) IsUnsubscribeFromEmailTypePayloadOrError() {}

type UpdateEmailInput struct {
	Email persist.Email `json:"email"`
	// authMechanism is an optional parameter that can verify a user's email address in lieu of sending
	// a verification email to the user. If not provided, a verification email will be sent.
	AuthMechanism *AuthMechanism `json:"authMechanism"`
}

type UpdateEmailNotificationSettingsInput struct {
	UnsubscribedFromAll           bool `json:"unsubscribedFromAll"`
	UnsubscribedFromNotifications bool `json:"unsubscribedFromNotifications"`
}

type UpdateEmailNotificationSettingsPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateEmailNotificationSettingsPayload) IsUpdateEmailNotificationSettingsPayloadOrError() {}

type UpdateEmailPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateEmailPayload) IsUpdateEmailPayloadOrError() {}

type UpdateUserInfoInput struct {
	Username string `json:"username"`
}

type UpdateUserInfoPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateUserInfoPayload) IsUpdateUserInfoPayloadOrError() {}

type UploadPersistedQueriesInput struct {
	PersistedQueries *string `json:"persistedQueries"`
}

type UploadPersistedQueriesPayload struct {
	Message *string `json:"message"`
}

func (UploadPersistedQueriesPayload) IsUploadPersistedQueriesPayloadOrError() {}

type User struct {
	HelperUserData
	Dbid  persist.DBID    `json:"dbid"`
	Roles []*persist.Role `json:"roles"`
	Pools []*Pool         `json:"pools"`
}

func (User) IsNode()                              {}
func (User) IsUserOrAccount()                     {}
func (User) IsUserByUsernameOrError()             {}
func (User) IsUserByIDOrError()                   {}
func (User) IsUserByAddressOrError()              {}
func (User) IsPoolOrUserOrEVMAccount()            {}
func (User) IsAddRolesToUserPayloadOrError()      {}
func (User) IsRevokeRolesFromUserPayloadOrError() {}

// Removes a user.
type UserDelete struct {
	Errors []*UserError `json:"errors"`
	User   *User        `json:"user"`
}

type UserEdge struct {
	Node   *User   `json:"node"`
	Cursor *string `json:"cursor"`
}

type UserEmail struct {
	Email                     *persist.Email                   `json:"email"`
	VerificationStatus        *persist.EmailVerificationStatus `json:"verificationStatus"`
	EmailNotificationSettings *EmailNotificationSettings       `json:"emailNotificationSettings"`
}

// Represents errors in user mutations.
type UserError struct {
	// Name of a field that caused the error. A value of `null` indicates that the error isn't associated with a particular field.
	Field *string `json:"field"`
	// The error message.
	Message *string `json:"message"`
	// The error code.
	Code UserErrorCode `json:"code"`
}

// Fields required to update the user.
type UserInput struct {
	// Username.
	Username *string `json:"username"`
}

// Login an existing user or register a new one.
type UserLoginOrRegister struct {
	// Informs whether users need to confirm their email address.
	RequiresConfirmation *bool `json:"requiresConfirmation"`
	// JWT token, required to authenticate.
	Token *string `json:"token"`
	// JWT refresh token, required to re-generate access token.
	RefreshToken *string      `json:"refreshToken"`
	User         *User        `json:"user"`
	Errors       []*UserError `json:"errors"`
}

// Fields required to login or register a user.
type UserLoginOrRegisterInput struct {
	// Base of frontend URL that will be needed to create confirmation URL. Required when account confirmation is enabled.
	RedirectURL *string `json:"redirectUrl"`
}

// Register a new user.
type UserRegister struct {
	// Informs whether users need to confirm their email address.
	RequiresConfirmation *bool        `json:"requiresConfirmation"`
	Errors               []*UserError `json:"errors"`
	User                 *User        `json:"user"`
}

// Fields required to create a user.
type UserRegisterInput struct {
	// Decentralized identifier of the user.
	Did *string `json:"did"`
	// Base of frontend URL that will be needed to create confirmation URL.
	RedirectURL *string `json:"redirectUrl"`
}

// Sends an email with the user removal link for the logged-in user.
type UserRequestDeletion struct {
	Errors []*UserError `json:"errors"`
}

// -------------------------------------------------------------------------------
//
//	SEARCH
//
// -------------------------------------------------------------------------------
type UserSearchResult struct {
	User *User `json:"user"`
}

// Updates the user of the logged-in user.
type UserUpdate struct {
	Errors []*UserError `json:"errors"`
	User   *User        `json:"user"`
}

type UsersConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type VerifyEmailInput struct {
	Token string `json:"token"`
}

type VerifyEmailMagicLinkInput struct {
	Email persist.Email `json:"email"`
}

type VerifyEmailMagicLinkPayload struct {
	CanSend bool `json:"canSend"`
}

func (VerifyEmailMagicLinkPayload) IsVerifyEmailMagicLinkPayloadOrError() {}

type VerifyEmailPayload struct {
	Email persist.Email `json:"email"`
}

func (VerifyEmailPayload) IsVerifyEmailPayloadOrError() {}

// Verify JWT token.
type VerifyToken struct {
	// User assigned to token.
	User *User `json:"user"`
	// Determine if token is valid or not.
	IsValid bool `json:"isValid"`
	// JWT payload.
	Errors []*UserError `json:"errors"`
}

type Viewer struct {
	HelperViewerData
	User  *User   `json:"user"`
	Pools []*Pool `json:"pools"`
	// Returns a list of notifications in reverse chronological order.
	// Seen notifications come after unseen notifications
	Notifications        *NotificationsConnection `json:"notifications"`
	NotificationSettings *NotificationSettings    `json:"notificationSettings"`
}

func (Viewer) IsViewerOrError() {}
func (Viewer) IsNode()          {}

type Withdrawal struct {
	ID          GqlID             `json:"id"`
	Transaction *Tx               `json:"transaction"`
	Pool        *Pool             `json:"pool"`
	Token       *Token            `json:"token"`
	From        persist.Address   `json:"from"`
	To          persist.Address   `json:"to"`
	Origin      string            `json:"origin"`
	Amount      persist.HexString `json:"amount"`
	LogIndex    *int              `json:"logIndex"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type ClaimBulkErrorCode string

const (
	ClaimBulkErrorCodeBlank               ClaimBulkErrorCode = "BLANK"
	ClaimBulkErrorCodeMaxLength           ClaimBulkErrorCode = "MAX_LENGTH"
	ClaimBulkErrorCodeDuplicatedInputItem ClaimBulkErrorCode = "DUPLICATED_INPUT_ITEM"
	ClaimBulkErrorCodeGraphqlError        ClaimBulkErrorCode = "GRAPHQL_ERROR"
	ClaimBulkErrorCodeInvalid             ClaimBulkErrorCode = "INVALID"
	ClaimBulkErrorCodeNotFound            ClaimBulkErrorCode = "NOT_FOUND"
	ClaimBulkErrorCodeRequired            ClaimBulkErrorCode = "REQUIRED"
	ClaimBulkErrorCodeUnique              ClaimBulkErrorCode = "UNIQUE"
)

var AllClaimBulkErrorCode = []ClaimBulkErrorCode{
	ClaimBulkErrorCodeBlank,
	ClaimBulkErrorCodeMaxLength,
	ClaimBulkErrorCodeDuplicatedInputItem,
	ClaimBulkErrorCodeGraphqlError,
	ClaimBulkErrorCodeInvalid,
	ClaimBulkErrorCodeNotFound,
	ClaimBulkErrorCodeRequired,
	ClaimBulkErrorCodeUnique,
}

func (e ClaimBulkErrorCode) IsValid() bool {
	switch e {
	case ClaimBulkErrorCodeBlank, ClaimBulkErrorCodeMaxLength, ClaimBulkErrorCodeDuplicatedInputItem, ClaimBulkErrorCodeGraphqlError, ClaimBulkErrorCodeInvalid, ClaimBulkErrorCodeNotFound, ClaimBulkErrorCodeRequired, ClaimBulkErrorCodeUnique:
		return true
	}
	return false
}

func (e ClaimBulkErrorCode) String() string {
	return string(e)
}

func (e *ClaimBulkErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClaimBulkErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClaimBulkErrorCode", str)
	}
	return nil
}

func (e ClaimBulkErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ClaimErrorCode string

const (
	ClaimErrorCodeAlreadyExists ClaimErrorCode = "ALREADY_EXISTS"
	ClaimErrorCodeGraphqlError  ClaimErrorCode = "GRAPHQL_ERROR"
	ClaimErrorCodeInvalid       ClaimErrorCode = "INVALID"
	ClaimErrorCodeNotFound      ClaimErrorCode = "NOT_FOUND"
	ClaimErrorCodeRequired      ClaimErrorCode = "REQUIRED"
	ClaimErrorCodeUnique        ClaimErrorCode = "UNIQUE"
)

var AllClaimErrorCode = []ClaimErrorCode{
	ClaimErrorCodeAlreadyExists,
	ClaimErrorCodeGraphqlError,
	ClaimErrorCodeInvalid,
	ClaimErrorCodeNotFound,
	ClaimErrorCodeRequired,
	ClaimErrorCodeUnique,
}

func (e ClaimErrorCode) IsValid() bool {
	switch e {
	case ClaimErrorCodeAlreadyExists, ClaimErrorCodeGraphqlError, ClaimErrorCodeInvalid, ClaimErrorCodeNotFound, ClaimErrorCodeRequired, ClaimErrorCodeUnique:
		return true
	}
	return false
}

func (e ClaimErrorCode) String() string {
	return string(e)
}

func (e *ClaimErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ClaimErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ClaimErrorCode", str)
	}
	return nil
}

func (e ClaimErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EVMAccountType string

const (
	EVMAccountTypeEoa      EVMAccountType = "EOA"
	EVMAccountTypeContract EVMAccountType = "Contract"
)

var AllEVMAccountType = []EVMAccountType{
	EVMAccountTypeEoa,
	EVMAccountTypeContract,
}

func (e EVMAccountType) IsValid() bool {
	switch e {
	case EVMAccountTypeEoa, EVMAccountTypeContract:
		return true
	}
	return false
}

func (e EVMAccountType) String() string {
	return string(e)
}

func (e *EVMAccountType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EVMAccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EVMAccountType", str)
	}
	return nil
}

func (e EVMAccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type EmailUnsubscriptionType string

const (
	EmailUnsubscriptionTypeAll           EmailUnsubscriptionType = "All"
	EmailUnsubscriptionTypeNotifications EmailUnsubscriptionType = "Notifications"
)

var AllEmailUnsubscriptionType = []EmailUnsubscriptionType{
	EmailUnsubscriptionTypeAll,
	EmailUnsubscriptionTypeNotifications,
}

func (e EmailUnsubscriptionType) IsValid() bool {
	switch e {
	case EmailUnsubscriptionTypeAll, EmailUnsubscriptionTypeNotifications:
		return true
	}
	return false
}

func (e EmailUnsubscriptionType) String() string {
	return string(e)
}

func (e *EmailUnsubscriptionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmailUnsubscriptionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmailUnsubscriptionType", str)
	}
	return nil
}

func (e EmailUnsubscriptionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ErrorPolicyEnum string

const (
	// Save what is possible within a single row. If there are errors in an input data row, try to save it partially and skip the invalid part.
	ErrorPolicyEnumIgnoreFailed ErrorPolicyEnum = "IGNORE_FAILED"
	// Reject all rows if there is at least one error in any of them.
	ErrorPolicyEnumRejectEverything ErrorPolicyEnum = "REJECT_EVERYTHING"
	// Reject rows with errors.
	ErrorPolicyEnumRejectFailedRows ErrorPolicyEnum = "REJECT_FAILED_ROWS"
)

var AllErrorPolicyEnum = []ErrorPolicyEnum{
	ErrorPolicyEnumIgnoreFailed,
	ErrorPolicyEnumRejectEverything,
	ErrorPolicyEnumRejectFailedRows,
}

func (e ErrorPolicyEnum) IsValid() bool {
	switch e {
	case ErrorPolicyEnumIgnoreFailed, ErrorPolicyEnumRejectEverything, ErrorPolicyEnumRejectFailedRows:
		return true
	}
	return false
}

func (e ErrorPolicyEnum) String() string {
	return string(e)
}

func (e *ErrorPolicyEnum) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ErrorPolicyEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ErrorPolicyEnum", str)
	}
	return nil
}

func (e ErrorPolicyEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ExtensionType string

const (
	ExtensionTypeState    ExtensionType = "State"
	ExtensionTypeStrategy ExtensionType = "Strategy"
)

var AllExtensionType = []ExtensionType{
	ExtensionTypeState,
	ExtensionTypeStrategy,
}

func (e ExtensionType) IsValid() bool {
	switch e {
	case ExtensionTypeState, ExtensionTypeStrategy:
		return true
	}
	return false
}

func (e ExtensionType) String() string {
	return string(e)
}

func (e *ExtensionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExtensionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExtensionType", str)
	}
	return nil
}

func (e ExtensionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PoolErrorCode string

const (
	PoolErrorCodeAlreadyExists PoolErrorCode = "ALREADY_EXISTS"
	PoolErrorCodeGraphqlError  PoolErrorCode = "GRAPHQL_ERROR"
	PoolErrorCodeInvalid       PoolErrorCode = "INVALID"
	PoolErrorCodeNotFound      PoolErrorCode = "NOT_FOUND"
	PoolErrorCodeRequired      PoolErrorCode = "REQUIRED"
	PoolErrorCodeUnique        PoolErrorCode = "UNIQUE"
)

var AllPoolErrorCode = []PoolErrorCode{
	PoolErrorCodeAlreadyExists,
	PoolErrorCodeGraphqlError,
	PoolErrorCodeInvalid,
	PoolErrorCodeNotFound,
	PoolErrorCodeRequired,
	PoolErrorCodeUnique,
}

func (e PoolErrorCode) IsValid() bool {
	switch e {
	case PoolErrorCodeAlreadyExists, PoolErrorCodeGraphqlError, PoolErrorCodeInvalid, PoolErrorCodeNotFound, PoolErrorCodeRequired, PoolErrorCodeUnique:
		return true
	}
	return false
}

func (e PoolErrorCode) String() string {
	return string(e)
}

func (e *PoolErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PoolErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PoolErrorCode", str)
	}
	return nil
}

func (e PoolErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PoolStatus string

const (
	PoolStatusDraft  PoolStatus = "Draft"
	PoolStatusActive PoolStatus = "Active"
	PoolStatusPaused PoolStatus = "Paused"
)

var AllPoolStatus = []PoolStatus{
	PoolStatusDraft,
	PoolStatusActive,
	PoolStatusPaused,
}

func (e PoolStatus) IsValid() bool {
	switch e {
	case PoolStatusDraft, PoolStatusActive, PoolStatusPaused:
		return true
	}
	return false
}

func (e PoolStatus) String() string {
	return string(e)
}

func (e *PoolStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PoolStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PoolStatus", str)
	}
	return nil
}

func (e PoolStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PreverifyEmailResult string

const (
	PreverifyEmailResultInvalid PreverifyEmailResult = "Invalid"
	PreverifyEmailResultRisky   PreverifyEmailResult = "Risky"
	PreverifyEmailResultValid   PreverifyEmailResult = "Valid"
)

var AllPreverifyEmailResult = []PreverifyEmailResult{
	PreverifyEmailResultInvalid,
	PreverifyEmailResultRisky,
	PreverifyEmailResultValid,
}

func (e PreverifyEmailResult) IsValid() bool {
	switch e {
	case PreverifyEmailResultInvalid, PreverifyEmailResultRisky, PreverifyEmailResultValid:
		return true
	}
	return false
}

func (e PreverifyEmailResult) String() string {
	return string(e)
}

func (e *PreverifyEmailResult) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PreverifyEmailResult(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PreverifyEmailResult", str)
	}
	return nil
}

func (e PreverifyEmailResult) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PushTokenErrorCode string

const (
	PushTokenErrorCodeAlreadyExists PushTokenErrorCode = "ALREADY_EXISTS"
	PushTokenErrorCodeGraphqlError  PushTokenErrorCode = "GRAPHQL_ERROR"
	PushTokenErrorCodeInvalid       PushTokenErrorCode = "INVALID"
	PushTokenErrorCodeNotFound      PushTokenErrorCode = "NOT_FOUND"
	PushTokenErrorCodeRequired      PushTokenErrorCode = "REQUIRED"
	PushTokenErrorCodeUnique        PushTokenErrorCode = "UNIQUE"
)

var AllPushTokenErrorCode = []PushTokenErrorCode{
	PushTokenErrorCodeAlreadyExists,
	PushTokenErrorCodeGraphqlError,
	PushTokenErrorCodeInvalid,
	PushTokenErrorCodeNotFound,
	PushTokenErrorCodeRequired,
	PushTokenErrorCodeUnique,
}

func (e PushTokenErrorCode) IsValid() bool {
	switch e {
	case PushTokenErrorCodeAlreadyExists, PushTokenErrorCodeGraphqlError, PushTokenErrorCodeInvalid, PushTokenErrorCodeNotFound, PushTokenErrorCodeRequired, PushTokenErrorCodeUnique:
		return true
	}
	return false
}

func (e PushTokenErrorCode) String() string {
	return string(e)
}

func (e *PushTokenErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PushTokenErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PushTokenErrorCode", str)
	}
	return nil
}

func (e PushTokenErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RoleErrorCode string

const (
	RoleErrorCodeRequired            RoleErrorCode = "REQUIRED"
	RoleErrorCodeUnique              RoleErrorCode = "UNIQUE"
	RoleErrorCodeDuplicatedInputItem RoleErrorCode = "DUPLICATED_INPUT_ITEM"
	RoleErrorCodeOutOfScopeUser      RoleErrorCode = "OUT_OF_SCOPE_USER"
)

var AllRoleErrorCode = []RoleErrorCode{
	RoleErrorCodeRequired,
	RoleErrorCodeUnique,
	RoleErrorCodeDuplicatedInputItem,
	RoleErrorCodeOutOfScopeUser,
}

func (e RoleErrorCode) IsValid() bool {
	switch e {
	case RoleErrorCodeRequired, RoleErrorCodeUnique, RoleErrorCodeDuplicatedInputItem, RoleErrorCodeOutOfScopeUser:
		return true
	}
	return false
}

func (e RoleErrorCode) String() string {
	return string(e)
}

func (e *RoleErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RoleErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RoleErrorCode", str)
	}
	return nil
}

func (e RoleErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TokenType string

const (
	TokenTypeErc20 TokenType = "ERC20"
)

var AllTokenType = []TokenType{
	TokenTypeErc20,
}

func (e TokenType) IsValid() bool {
	switch e {
	case TokenTypeErc20:
		return true
	}
	return false
}

func (e TokenType) String() string {
	return string(e)
}

func (e *TokenType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TokenType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TokenType", str)
	}
	return nil
}

func (e TokenType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserErrorCode string

const (
	UserErrorCodeActivateOwnAccount         UserErrorCode = "ACTIVATE_OWN_ACCOUNT"
	UserErrorCodeActivateSuperuserAccount   UserErrorCode = "ACTIVATE_SUPERUSER_ACCOUNT"
	UserErrorCodeDuplicatedInputItem        UserErrorCode = "DUPLICATED_INPUT_ITEM"
	UserErrorCodeDeactivateOwnAccount       UserErrorCode = "DEACTIVATE_OWN_ACCOUNT"
	UserErrorCodeDeactivateSuperuserAccount UserErrorCode = "DEACTIVATE_SUPERUSER_ACCOUNT"
	UserErrorCodeDeleteNonStaffUser         UserErrorCode = "DELETE_NON_STAFF_USER"
	UserErrorCodeDeleteOwnAccount           UserErrorCode = "DELETE_OWN_ACCOUNT"
	UserErrorCodeDeleteSuperuserAccount     UserErrorCode = "DELETE_SUPERUSER_ACCOUNT"
	UserErrorCodeGraphqlError               UserErrorCode = "GRAPHQL_ERROR"
	UserErrorCodeInactive                   UserErrorCode = "INACTIVE"
	UserErrorCodeInvalid                    UserErrorCode = "INVALID"
	UserErrorCodeInvalidCredentials         UserErrorCode = "INVALID_CREDENTIALS"
	UserErrorCodeNotFound                   UserErrorCode = "NOT_FOUND"
	UserErrorCodeOutOfScopeRole             UserErrorCode = "OUT_OF_SCOPE_ROLE"
	UserErrorCodeRequired                   UserErrorCode = "REQUIRED"
	UserErrorCodeUnique                     UserErrorCode = "UNIQUE"
	UserErrorCodeJwtSignatureExpired        UserErrorCode = "JWT_SIGNATURE_EXPIRED"
	UserErrorCodeJwtInvalidToken            UserErrorCode = "JWT_INVALID_TOKEN"
	UserErrorCodeJwtDecodeError             UserErrorCode = "JWT_DECODE_ERROR"
	UserErrorCodeJwtMissingToken            UserErrorCode = "JWT_MISSING_TOKEN"
	UserErrorCodeJwtInvalidCsrfToken        UserErrorCode = "JWT_INVALID_CSRF_TOKEN"
	UserErrorCodeAccountNotConfirmed        UserErrorCode = "ACCOUNT_NOT_CONFIRMED"
	UserErrorCodeLoginAttemptDelayed        UserErrorCode = "LOGIN_ATTEMPT_DELAYED"
	UserErrorCodeUnknownIPAddress           UserErrorCode = "UNKNOWN_IP_ADDRESS"
)

var AllUserErrorCode = []UserErrorCode{
	UserErrorCodeActivateOwnAccount,
	UserErrorCodeActivateSuperuserAccount,
	UserErrorCodeDuplicatedInputItem,
	UserErrorCodeDeactivateOwnAccount,
	UserErrorCodeDeactivateSuperuserAccount,
	UserErrorCodeDeleteNonStaffUser,
	UserErrorCodeDeleteOwnAccount,
	UserErrorCodeDeleteSuperuserAccount,
	UserErrorCodeGraphqlError,
	UserErrorCodeInactive,
	UserErrorCodeInvalid,
	UserErrorCodeInvalidCredentials,
	UserErrorCodeNotFound,
	UserErrorCodeOutOfScopeRole,
	UserErrorCodeRequired,
	UserErrorCodeUnique,
	UserErrorCodeJwtSignatureExpired,
	UserErrorCodeJwtInvalidToken,
	UserErrorCodeJwtDecodeError,
	UserErrorCodeJwtMissingToken,
	UserErrorCodeJwtInvalidCsrfToken,
	UserErrorCodeAccountNotConfirmed,
	UserErrorCodeLoginAttemptDelayed,
	UserErrorCodeUnknownIPAddress,
}

func (e UserErrorCode) IsValid() bool {
	switch e {
	case UserErrorCodeActivateOwnAccount, UserErrorCodeActivateSuperuserAccount, UserErrorCodeDuplicatedInputItem, UserErrorCodeDeactivateOwnAccount, UserErrorCodeDeactivateSuperuserAccount, UserErrorCodeDeleteNonStaffUser, UserErrorCodeDeleteOwnAccount, UserErrorCodeDeleteSuperuserAccount, UserErrorCodeGraphqlError, UserErrorCodeInactive, UserErrorCodeInvalid, UserErrorCodeInvalidCredentials, UserErrorCodeNotFound, UserErrorCodeOutOfScopeRole, UserErrorCodeRequired, UserErrorCodeUnique, UserErrorCodeJwtSignatureExpired, UserErrorCodeJwtInvalidToken, UserErrorCodeJwtDecodeError, UserErrorCodeJwtMissingToken, UserErrorCodeJwtInvalidCsrfToken, UserErrorCodeAccountNotConfirmed, UserErrorCodeLoginAttemptDelayed, UserErrorCodeUnknownIPAddress:
		return true
	}
	return false
}

func (e UserErrorCode) String() string {
	return string(e)
}

func (e *UserErrorCode) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserErrorCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserErrorCode", str)
	}
	return nil
}

func (e UserErrorCode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
