// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/mutuals/go-mutuals/service/persist"
)

type AddRolesToUserPayloadOrError interface {
	IsAddRolesToUserPayloadOrError()
}

type AddUserWalletPayloadOrError interface {
	IsAddUserWalletPayloadOrError()
}

type AdminAddWalletPayloadOrError interface {
	IsAdminAddWalletPayloadOrError()
}

type AuthorizationError interface {
	IsAuthorizationError()
}

type CreatePoolPayloadOrError interface {
	IsCreatePoolPayloadOrError()
}

type CreateUserPayloadOrError interface {
	IsCreateUserPayloadOrError()
}

type DeletePoolPayloadOrError interface {
	IsDeletePoolPayloadOrError()
}

type Error interface {
	IsError()
}

type GetAuthNoncePayloadOrError interface {
	IsGetAuthNoncePayloadOrError()
}

type GroupedNotification interface {
	Notification
	Node
	IsGroupedNotification()
}

type LoginPayloadOrError interface {
	IsLoginPayloadOrError()
}

type MutualsUserOrAddress interface {
	IsMutualsUserOrAddress()
}

type MutualsUserOrWallet interface {
	IsMutualsUserOrWallet()
}

type Node interface {
	IsNode()
}

type Notification interface {
	Node
	IsNotification()
}

type OptInForRolesPayloadOrError interface {
	IsOptInForRolesPayloadOrError()
}

type OptOutForRolesPayloadOrError interface {
	IsOptOutForRolesPayloadOrError()
}

type PoolByIDPayloadOrError interface {
	IsPoolByIDPayloadOrError()
}

type PreverifyEmailPayloadOrError interface {
	IsPreverifyEmailPayloadOrError()
}

type PublishPoolPayloadOrError interface {
	IsPublishPoolPayloadOrError()
}

type RegisterUserPushTokenPayloadOrError interface {
	IsRegisterUserPushTokenPayloadOrError()
}

type RemoveUserWalletsPayloadOrError interface {
	IsRemoveUserWalletsPayloadOrError()
}

type ResendVerificationEmailPayloadOrError interface {
	IsResendVerificationEmailPayloadOrError()
}

type RevokeRolesFromUserPayloadOrError interface {
	IsRevokeRolesFromUserPayloadOrError()
}

type SearchPoolsPayloadOrError interface {
	IsSearchPoolsPayloadOrError()
}

type SearchUsersPayloadOrError interface {
	IsSearchUsersPayloadOrError()
}

type UnregisterUserPushTokenPayloadOrError interface {
	IsUnregisterUserPushTokenPayloadOrError()
}

type UnsubscribeFromEmailTypePayloadOrError interface {
	IsUnsubscribeFromEmailTypePayloadOrError()
}

type UpdateEmailNotificationSettingsPayloadOrError interface {
	IsUpdateEmailNotificationSettingsPayloadOrError()
}

type UpdateEmailPayloadOrError interface {
	IsUpdateEmailPayloadOrError()
}

type UpdatePoolHiddenPayloadOrError interface {
	IsUpdatePoolHiddenPayloadOrError()
}

type UpdatePoolOrderPayloadOrError interface {
	IsUpdatePoolOrderPayloadOrError()
}

type UpdatePoolPayloadOrError interface {
	IsUpdatePoolPayloadOrError()
}

type UpdatePrimaryWalletPayloadOrError interface {
	IsUpdatePrimaryWalletPayloadOrError()
}

type UpdateUserExperiencePayloadOrError interface {
	IsUpdateUserExperiencePayloadOrError()
}

type UpdateUserInfoPayloadOrError interface {
	IsUpdateUserInfoPayloadOrError()
}

type UploadPersistedQueriesPayloadOrError interface {
	IsUploadPersistedQueriesPayloadOrError()
}

type UpsertPoolPayloadOrError interface {
	IsUpsertPoolPayloadOrError()
}

type UserByAddressOrError interface {
	IsUserByAddressOrError()
}

type UserByIDOrError interface {
	IsUserByIDOrError()
}

type UserByUsernameOrError interface {
	IsUserByUsernameOrError()
}

type VerifyEmailMagicLinkPayloadOrError interface {
	IsVerifyEmailMagicLinkPayloadOrError()
}

type VerifyEmailPayloadOrError interface {
	IsVerifyEmailPayloadOrError()
}

type ViewerOrError interface {
	IsViewerOrError()
}

type ViewerPoolByIDPayloadOrError interface {
	IsViewerPoolByIDPayloadOrError()
}

type AddUserWalletPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (AddUserWalletPayload) IsAddUserWalletPayloadOrError() {}

type AdminAddWalletInput struct {
	Username     string                `json:"username"`
	ChainAddress *persist.ChainAddress `json:"chainAddress"`
	WalletType   persist.WalletType    `json:"walletType"`
}

type AdminAddWalletPayload struct {
	User *MutualsUser `json:"user"`
}

func (AdminAddWalletPayload) IsAdminAddWalletPayloadOrError() {}

type Allocation struct {
	Dbid             persist.DBID       `json:"dbid"`
	Version          *int               `json:"version"`
	RecipientAddress *persist.Address   `json:"recipientAddress"`
	Value            *persist.HexString `json:"value"`
	CreationTime     *time.Time         `json:"creationTime"`
	LastUpdated      *time.Time         `json:"lastUpdated"`
	Pool             *Pool              `json:"pool"`
}

func (Allocation) IsNode() {}

type AllocationAggregation struct {
	Dbid             persist.DBID     `json:"dbid"`
	Version          *int             `json:"version"`
	RecipientAddress *persist.Address `json:"recipientAddress"`
	Expression       *string          `json:"expression"`
	CreationTime     *time.Time       `json:"creationTime"`
	LastUpdated      *time.Time       `json:"lastUpdated"`
	Pool             *Pool            `json:"pool"`
}

func (AllocationAggregation) IsNode() {}

type Asset struct {
	Dbid         persist.DBID          `json:"dbid"`
	Version      *int                  `json:"version"`
	OwnerAddress *persist.ChainAddress `json:"ownerAddress"`
	Balance      *persist.HexString    `json:"balance"`
	Token        *Token                `json:"token"`
}

func (Asset) IsNode() {}

type AuthMechanism struct {
	Eoa               *EoaAuth               `json:"eoa"`
	GnosisSafe        *GnosisSafeAuth        `json:"gnosisSafe"`
	Debug             *DebugAuth             `json:"debug"`
	MagicLink         *MagicLinkAuth         `json:"magicLink"`
	OneTimeLoginToken *OneTimeLoginTokenAuth `json:"oneTimeLoginToken"`
	Privy             *PrivyAuth             `json:"privy"`
}

type AuthNonce struct {
	Nonce   *string `json:"nonce"`
	Message *string `json:"message"`
}

func (AuthNonce) IsGetAuthNoncePayloadOrError() {}

type ChainPools struct {
	Chain *persist.Chain `json:"chain"`
	Pools []*Pool        `json:"pools"`
}

type ClearAllNotificationsPayload struct {
	Notifications []Notification `json:"notifications"`
}

type CreatePoolInput struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Logo        *string `json:"logo"`
}

type CreatePoolPayload struct {
	Pool *Pool `json:"pool"`
}

func (CreatePoolPayload) IsCreatePoolPayloadOrError() {}

type CreateUserInput struct {
	Username *string        `json:"username"`
	Email    *persist.Email `json:"email"`
}

type CreateUserPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (CreateUserPayload) IsCreateUserPayloadOrError() {}

type DebugAuth struct {
	AsUsername         *string                 `json:"asUsername"`
	UserID             *persist.DBID           `json:"userId"`
	ChainAddresses     []*persist.ChainAddress `json:"chainAddresses"`
	DebugToolsPassword *string                 `json:"debugToolsPassword"`
}

type DeletePoolPayload struct {
	DeletedID *DeletedNode `json:"deletedId"`
}

func (DeletePoolPayload) IsDeletePoolPayloadOrError() {}

type DeletedNode struct {
	Dbid persist.DBID `json:"dbid"`
}

func (DeletedNode) IsNode() {}

type EmailNotificationSettings struct {
	UnsubscribedFromAll           bool `json:"unsubscribedFromAll"`
	UnsubscribedFromNotifications bool `json:"unsubscribedFromNotifications"`
}

type EoaAuth struct {
	ChainPubKey *persist.ChainPubKey `json:"chainPubKey"`
	Nonce       string               `json:"nonce"`
	Message     string               `json:"message"`
	Signature   string               `json:"signature"`
}

type ErrAddressOwnedByUser struct {
	Message string `json:"message"`
}

func (ErrAddressOwnedByUser) IsAddUserWalletPayloadOrError()  {}
func (ErrAddressOwnedByUser) IsError()                        {}
func (ErrAddressOwnedByUser) IsAdminAddWalletPayloadOrError() {}

type ErrAuthenticationFailed struct {
	Message string `json:"message"`
}

func (ErrAuthenticationFailed) IsAddUserWalletPayloadOrError() {}
func (ErrAuthenticationFailed) IsError()                       {}
func (ErrAuthenticationFailed) IsLoginPayloadOrError()         {}
func (ErrAuthenticationFailed) IsCreateUserPayloadOrError()    {}

type ErrCommunityNotFound struct {
	Message string `json:"message"`
}

func (ErrCommunityNotFound) IsError() {}

type ErrDoesNotOwnRequiredToken struct {
	Message string `json:"message"`
}

func (ErrDoesNotOwnRequiredToken) IsAuthorizationError()       {}
func (ErrDoesNotOwnRequiredToken) IsError()                    {}
func (ErrDoesNotOwnRequiredToken) IsLoginPayloadOrError()      {}
func (ErrDoesNotOwnRequiredToken) IsCreateUserPayloadOrError() {}

type ErrInvalidInput struct {
	Message    string   `json:"message"`
	Parameters []string `json:"parameters"`
	Reasons    []string `json:"reasons"`
}

func (ErrInvalidInput) IsUserByUsernameOrError()                         {}
func (ErrInvalidInput) IsUserByIDOrError()                               {}
func (ErrInvalidInput) IsUserByAddressOrError()                          {}
func (ErrInvalidInput) IsSearchUsersPayloadOrError()                     {}
func (ErrInvalidInput) IsSearchPoolsPayloadOrError()                     {}
func (ErrInvalidInput) IsAddUserWalletPayloadOrError()                   {}
func (ErrInvalidInput) IsRemoveUserWalletsPayloadOrError()               {}
func (ErrInvalidInput) IsUpdateUserInfoPayloadOrError()                  {}
func (ErrInvalidInput) IsRegisterUserPushTokenPayloadOrError()           {}
func (ErrInvalidInput) IsUnregisterUserPushTokenPayloadOrError()         {}
func (ErrInvalidInput) IsError()                                         {}
func (ErrInvalidInput) IsCreateUserPayloadOrError()                      {}
func (ErrInvalidInput) IsVerifyEmailPayloadOrError()                     {}
func (ErrInvalidInput) IsPreverifyEmailPayloadOrError()                  {}
func (ErrInvalidInput) IsVerifyEmailMagicLinkPayloadOrError()            {}
func (ErrInvalidInput) IsUpdateEmailPayloadOrError()                     {}
func (ErrInvalidInput) IsResendVerificationEmailPayloadOrError()         {}
func (ErrInvalidInput) IsUpdateEmailNotificationSettingsPayloadOrError() {}
func (ErrInvalidInput) IsUnsubscribeFromEmailTypePayloadOrError()        {}
func (ErrInvalidInput) IsOptInForRolesPayloadOrError()                   {}
func (ErrInvalidInput) IsOptOutForRolesPayloadOrError()                  {}
func (ErrInvalidInput) IsCreatePoolPayloadOrError()                      {}
func (ErrInvalidInput) IsUpsertPoolPayloadOrError()                      {}
func (ErrInvalidInput) IsUpdatePoolHiddenPayloadOrError()                {}
func (ErrInvalidInput) IsDeletePoolPayloadOrError()                      {}
func (ErrInvalidInput) IsUpdatePoolOrderPayloadOrError()                 {}
func (ErrInvalidInput) IsUpdatePoolPayloadOrError()                      {}
func (ErrInvalidInput) IsPublishPoolPayloadOrError()                     {}
func (ErrInvalidInput) IsUpdatePrimaryWalletPayloadOrError()             {}
func (ErrInvalidInput) IsUpdateUserExperiencePayloadOrError()            {}

type ErrInvalidToken struct {
	Message string `json:"message"`
}

func (ErrInvalidToken) IsAuthorizationError() {}
func (ErrInvalidToken) IsError()              {}

type ErrNoCookie struct {
	Message string `json:"message"`
}

func (ErrNoCookie) IsAuthorizationError() {}
func (ErrNoCookie) IsError()              {}

type ErrNotAuthorized struct {
	Message string             `json:"message"`
	Cause   AuthorizationError `json:"cause"`
}

func (ErrNotAuthorized) IsViewerOrError()                         {}
func (ErrNotAuthorized) IsAddUserWalletPayloadOrError()           {}
func (ErrNotAuthorized) IsRemoveUserWalletsPayloadOrError()       {}
func (ErrNotAuthorized) IsUpdateUserInfoPayloadOrError()          {}
func (ErrNotAuthorized) IsRegisterUserPushTokenPayloadOrError()   {}
func (ErrNotAuthorized) IsUnregisterUserPushTokenPayloadOrError() {}
func (ErrNotAuthorized) IsError()                                 {}
func (ErrNotAuthorized) IsAddRolesToUserPayloadOrError()          {}
func (ErrNotAuthorized) IsRevokeRolesFromUserPayloadOrError()     {}
func (ErrNotAuthorized) IsOptInForRolesPayloadOrError()           {}
func (ErrNotAuthorized) IsOptOutForRolesPayloadOrError()          {}
func (ErrNotAuthorized) IsUploadPersistedQueriesPayloadOrError()  {}
func (ErrNotAuthorized) IsCreatePoolPayloadOrError()              {}
func (ErrNotAuthorized) IsUpsertPoolPayloadOrError()              {}
func (ErrNotAuthorized) IsUpdatePoolHiddenPayloadOrError()        {}
func (ErrNotAuthorized) IsDeletePoolPayloadOrError()              {}
func (ErrNotAuthorized) IsUpdatePoolOrderPayloadOrError()         {}
func (ErrNotAuthorized) IsUpdatePoolPayloadOrError()              {}
func (ErrNotAuthorized) IsPublishPoolPayloadOrError()             {}
func (ErrNotAuthorized) IsUpdatePrimaryWalletPayloadOrError()     {}
func (ErrNotAuthorized) IsAdminAddWalletPayloadOrError()          {}
func (ErrNotAuthorized) IsUpdateUserExperiencePayloadOrError()    {}

type ErrPoolNotFound struct {
	Message string `json:"message"`
}

func (ErrPoolNotFound) IsError()                        {}
func (ErrPoolNotFound) IsPoolByIDPayloadOrError()       {}
func (ErrPoolNotFound) IsViewerPoolByIDPayloadOrError() {}

type ErrPushTokenBelongsToAnotherUser struct {
	Message string `json:"message"`
}

func (ErrPushTokenBelongsToAnotherUser) IsRegisterUserPushTokenPayloadOrError()   {}
func (ErrPushTokenBelongsToAnotherUser) IsUnregisterUserPushTokenPayloadOrError() {}
func (ErrPushTokenBelongsToAnotherUser) IsError()                                 {}

type ErrSessionInvalidated struct {
	Message string `json:"message"`
}

func (ErrSessionInvalidated) IsAuthorizationError() {}
func (ErrSessionInvalidated) IsError()              {}

type ErrSyncFailed struct {
	Message string `json:"message"`
}

func (ErrSyncFailed) IsError() {}

type ErrTokenNotFound struct {
	Message string `json:"message"`
}

func (ErrTokenNotFound) IsError() {}

type ErrUserAlreadyExists struct {
	Message string `json:"message"`
}

func (ErrUserAlreadyExists) IsError()                    {}
func (ErrUserAlreadyExists) IsCreateUserPayloadOrError() {}

type ErrUserNotFound struct {
	Message string `json:"message"`
}

func (ErrUserNotFound) IsUserByUsernameOrError()        {}
func (ErrUserNotFound) IsUserByIDOrError()              {}
func (ErrUserNotFound) IsUserByAddressOrError()         {}
func (ErrUserNotFound) IsError()                        {}
func (ErrUserNotFound) IsLoginPayloadOrError()          {}
func (ErrUserNotFound) IsAdminAddWalletPayloadOrError() {}

type ErrUsernameNotAvailable struct {
	Message string `json:"message"`
}

func (ErrUsernameNotAvailable) IsUpdateUserInfoPayloadOrError() {}
func (ErrUsernameNotAvailable) IsError()                        {}
func (ErrUsernameNotAvailable) IsCreateUserPayloadOrError()     {}

type GnosisSafeAuth struct {
	Address persist.Address `json:"address"`
	Nonce   string          `json:"nonce"`
	Message string          `json:"message"`
}

type GroupNotificationUserEdge struct {
	Node   *MutualsUser `json:"node"`
	Cursor *string      `json:"cursor"`
}

type GroupNotificationUsersConnection struct {
	HelperGroupNotificationUsersConnectionData
	Edges    []*GroupNotificationUserEdge `json:"edges"`
	PageInfo *PageInfo                    `json:"pageInfo"`
}

type LoginPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (LoginPayload) IsLoginPayloadOrError() {}

type LogoutPayload struct {
	Viewer *Viewer `json:"viewer"`
}

type MagicLinkAuth struct {
	Token string `json:"token"`
}

type MutualsUser struct {
	HelperMutualsUserData
	Dbid                persist.DBID    `json:"dbid"`
	Username            *string         `json:"username"`
	Universal           *bool           `json:"universal"`
	Roles               []*persist.Role `json:"roles"`
	Wallets             []*Wallet       `json:"wallets"`
	PrimaryWallet       *Wallet         `json:"primaryWallet"`
	Pools               []*Pool         `json:"pools"`
	PoolsByChain        *ChainPools     `json:"poolsByChain"`
	IsAuthenticatedUser *bool           `json:"isAuthenticatedUser"`
}

func (MutualsUser) IsNode()                              {}
func (MutualsUser) IsMutualsUserOrWallet()               {}
func (MutualsUser) IsMutualsUserOrAddress()              {}
func (MutualsUser) IsUserByUsernameOrError()             {}
func (MutualsUser) IsUserByIDOrError()                   {}
func (MutualsUser) IsUserByAddressOrError()              {}
func (MutualsUser) IsAddRolesToUserPayloadOrError()      {}
func (MutualsUser) IsRevokeRolesFromUserPayloadOrError() {}

type NotificationEdge struct {
	Node   Notification `json:"node"`
	Cursor *string      `json:"cursor"`
}

type NotificationSettings struct {
	SomeoneViewedYourPool *bool `json:"someoneViewedYourPool"`
}

type NotificationSettingsInput struct {
	SomeoneViewedYourPool *bool `json:"someoneViewedYourPool"`
}

type NotificationsConnection struct {
	HelperNotificationsConnectionData
	Edges       []*NotificationEdge `json:"edges"`
	UnseenCount *int                `json:"unseenCount"`
	PageInfo    *PageInfo           `json:"pageInfo"`
}

type OneTimeLoginTokenAuth struct {
	Token string `json:"token"`
}

type OptInForRolesPayload struct {
	User *MutualsUser `json:"user"`
}

func (OptInForRolesPayload) IsOptInForRolesPayloadOrError() {}

type OptOutForRolesPayload struct {
	User *MutualsUser `json:"user"`
}

func (OptOutForRolesPayload) IsOptOutForRolesPayloadOrError() {}

type PageInfo struct {
	Total           *int   `json:"total"`
	Size            int    `json:"size"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	HasNextPage     bool   `json:"hasNextPage"`
	StartCursor     string `json:"startCursor"`
	EndCursor       string `json:"endCursor"`
}

type Pool struct {
	Dbid                  persist.DBID             `json:"dbid"`
	Version               *int                     `json:"version"`
	Status                PoolStatus               `json:"status"`
	Name                  *string                  `json:"name"`
	Description           *string                  `json:"description"`
	Address               *persist.Address         `json:"address"`
	OwnerAddress          *persist.Address         `json:"ownerAddress"`
	CreatorAddress        *persist.Address         `json:"creatorAddress"`
	Chain                 *persist.Chain           `json:"chain"`
	AllocationAggregation []*AllocationAggregation `json:"allocationAggregation"`
	Allocations           []*Allocation            `json:"allocations"`
	Assets                []*Asset                 `json:"assets"`
}

func (Pool) IsNode()                   {}
func (Pool) IsPoolByIDPayloadOrError() {}

type PoolAllocationInput struct {
	ID               *persist.DBID             `json:"id"`
	RecipientAddress *persist.Address          `json:"recipientAddress"`
	CalculationType  []persist.CalculationType `json:"calculationType"`
	RecipientType    []persist.RecipientType   `json:"recipientType"`
	Value            persist.HexString         `json:"value"`
	Children         []*PoolAllocationInput    `json:"children"`
}

type PoolPositionInput struct {
	PoolID   persist.DBID `json:"poolId"`
	Position string       `json:"position"`
}

type PoolSearchResult struct {
	Pool *Pool `json:"pool"`
}

type PreverifyEmailInput struct {
	Email persist.Email `json:"email"`
}

type PreverifyEmailPayload struct {
	Email  persist.Email        `json:"email"`
	Result PreverifyEmailResult `json:"result"`
}

func (PreverifyEmailPayload) IsPreverifyEmailPayloadOrError() {}

type PrivyAuth struct {
	Token string `json:"token"`
}

type PublishPoolInput struct {
	PoolID  persist.DBID `json:"poolId"`
	EditID  string       `json:"editId"`
	Caption *string      `json:"caption"`
}

type PublishPoolPayload struct {
	Pool *Pool `json:"pool"`
}

func (PublishPoolPayload) IsPublishPoolPayloadOrError() {}

type RegisterUserPushTokenPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (RegisterUserPushTokenPayload) IsRegisterUserPushTokenPayloadOrError() {}

type RemoveUserWalletsPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (RemoveUserWalletsPayload) IsRemoveUserWalletsPayloadOrError() {}

type ResendVerificationEmailPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (ResendVerificationEmailPayload) IsResendVerificationEmailPayloadOrError() {}

type SearchPoolsPayload struct {
	Results []*PoolSearchResult `json:"results"`
}

func (SearchPoolsPayload) IsSearchPoolsPayloadOrError() {}

type SearchUsersPayload struct {
	Results []*UserSearchResult `json:"results"`
}

func (SearchUsersPayload) IsSearchUsersPayloadOrError() {}

type Token struct {
	Dbid            persist.DBID   `json:"dbid"`
	Version         *int           `json:"version"`
	CreationTime    *time.Time     `json:"creationTime"`
	LastUpdated     *time.Time     `json:"lastUpdated"`
	TokenType       *TokenType     `json:"tokenType"`
	Chain           *persist.Chain `json:"chain"`
	Name            *string        `json:"name"`
	Symbol          *string        `json:"symbol"`
	Decimals        *int           `json:"decimals"`
	Logo            *string        `json:"logo"`
	TotalSupply     *int           `json:"totalSupply"`
	ContractAddress *int           `json:"contractAddress"`
	BlockNumber     *string        `json:"blockNumber"`
	IsSpam          *bool          `json:"isSpam"`
}

func (Token) IsNode() {}

type UnregisterUserPushTokenPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UnregisterUserPushTokenPayload) IsUnregisterUserPushTokenPayloadOrError() {}

type UnsubscribeFromEmailTypeInput struct {
	Type  EmailUnsubscriptionType `json:"type"`
	Token string                  `json:"token"`
}

type UnsubscribeFromEmailTypePayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UnsubscribeFromEmailTypePayload) IsUnsubscribeFromEmailTypePayloadOrError() {}

type UpdateEmailInput struct {
	Email persist.Email `json:"email"`
	// authMechanism is an optional parameter that can verify a user's email address in lieu of sending
	// a verification email to the user. If not provided, a verification email will be sent.
	AuthMechanism *AuthMechanism `json:"authMechanism"`
}

type UpdateEmailNotificationSettingsInput struct {
	UnsubscribedFromAll           bool `json:"unsubscribedFromAll"`
	UnsubscribedFromNotifications bool `json:"unsubscribedFromNotifications"`
}

type UpdateEmailNotificationSettingsPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateEmailNotificationSettingsPayload) IsUpdateEmailNotificationSettingsPayloadOrError() {}

type UpdateEmailPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateEmailPayload) IsUpdateEmailPayloadOrError() {}

type UpdatePoolHiddenInput struct {
	ID     persist.DBID `json:"id"`
	Hidden bool         `json:"hidden"`
}

type UpdatePoolHiddenPayload struct {
	Pool *Pool `json:"pool"`
}

func (UpdatePoolHiddenPayload) IsUpdatePoolHiddenPayloadOrError() {}

type UpdatePoolInfoInput struct {
	ID          persist.DBID `json:"id"`
	Name        *string      `json:"name"`
	Description *string      `json:"description"`
}

type UpdatePoolInput struct {
	PoolID      persist.DBID   `json:"poolId"`
	Name        *string        `json:"name"`
	Description *string        `json:"description"`
	Order       []persist.DBID `json:"order"`
	EditID      string         `json:"editId"`
}

type UpdatePoolOrderInput struct {
	Positions []*PoolPositionInput `json:"positions"`
}

type UpdatePoolOrderPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdatePoolOrderPayload) IsUpdatePoolOrderPayloadOrError() {}

type UpdatePoolPayload struct {
	Pool *Pool `json:"pool"`
}

func (UpdatePoolPayload) IsUpdatePoolPayloadOrError() {}

type UpdatePrimaryWalletPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdatePrimaryWalletPayload) IsUpdatePrimaryWalletPayloadOrError() {}

type UpdateUserExperienceInput struct {
	ExperienceType UserExperienceType `json:"experienceType"`
	Experienced    bool               `json:"experienced"`
}

type UpdateUserExperiencePayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateUserExperiencePayload) IsUpdateUserExperiencePayloadOrError() {}

type UpdateUserInfoInput struct {
	Username string `json:"username"`
}

type UpdateUserInfoPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (UpdateUserInfoPayload) IsUpdateUserInfoPayloadOrError() {}

type UploadPersistedQueriesInput struct {
	PersistedQueries *string `json:"persistedQueries"`
}

type UploadPersistedQueriesPayload struct {
	Message *string `json:"message"`
}

func (UploadPersistedQueriesPayload) IsUploadPersistedQueriesPayloadOrError() {}

type UpsertPoolInput struct {
	PoolID      *persist.DBID          `json:"poolId"`
	Name        *string                `json:"name"`
	Description *string                `json:"description"`
	Allocations []*PoolAllocationInput `json:"allocations"`
}

type UpsertPoolPayload struct {
	Pool *Pool `json:"pool"`
}

func (UpsertPoolPayload) IsUpsertPoolPayloadOrError() {}

type UserEdge struct {
	Node   *MutualsUser `json:"node"`
	Cursor *string      `json:"cursor"`
}

type UserEmail struct {
	Email                     *persist.Email                   `json:"email"`
	VerificationStatus        *persist.EmailVerificationStatus `json:"verificationStatus"`
	EmailNotificationSettings *EmailNotificationSettings       `json:"emailNotificationSettings"`
}

type UserExperience struct {
	Type        UserExperienceType `json:"type"`
	Experienced bool               `json:"experienced"`
}

type UserSearchResult struct {
	User *MutualsUser `json:"user"`
}

type UsersConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type VerifyEmailInput struct {
	Token string `json:"token"`
}

type VerifyEmailMagicLinkInput struct {
	Email persist.Email `json:"email"`
}

type VerifyEmailMagicLinkPayload struct {
	CanSend bool `json:"canSend"`
}

func (VerifyEmailMagicLinkPayload) IsVerifyEmailMagicLinkPayloadOrError() {}

type VerifyEmailPayload struct {
	Email persist.Email `json:"email"`
}

func (VerifyEmailPayload) IsVerifyEmailPayloadOrError() {}

type Viewer struct {
	HelperViewerData
	User        *MutualsUser  `json:"user"`
	ViewerPools []*ViewerPool `json:"viewerPools"`
	Email       *UserEmail    `json:"email"`
	// Returns a list of notifications in reverse chronological order.
	// Seen notifications come after unseen notifications
	Notifications        *NotificationsConnection `json:"notifications"`
	NotificationSettings *NotificationSettings    `json:"notificationSettings"`
	UserExperiences      []*UserExperience        `json:"userExperiences"`
}

func (Viewer) IsNode()          {}
func (Viewer) IsViewerOrError() {}

type ViewerPool struct {
	Pool *Pool `json:"pool"`
}

func (ViewerPool) IsViewerPoolByIDPayloadOrError() {}

type Wallet struct {
	Dbid         persist.DBID          `json:"dbid"`
	ChainAddress *persist.ChainAddress `json:"chainAddress"`
	Chain        *persist.Chain        `json:"chain"`
	WalletType   *persist.WalletType   `json:"walletType"`
	Pools        []*Pool               `json:"pools"`
}

func (Wallet) IsNode()                {}
func (Wallet) IsMutualsUserOrWallet() {}

type EmailUnsubscriptionType string

const (
	EmailUnsubscriptionTypeAll           EmailUnsubscriptionType = "All"
	EmailUnsubscriptionTypeNotifications EmailUnsubscriptionType = "Notifications"
)

var AllEmailUnsubscriptionType = []EmailUnsubscriptionType{
	EmailUnsubscriptionTypeAll,
	EmailUnsubscriptionTypeNotifications,
}

func (e EmailUnsubscriptionType) IsValid() bool {
	switch e {
	case EmailUnsubscriptionTypeAll, EmailUnsubscriptionTypeNotifications:
		return true
	}
	return false
}

func (e EmailUnsubscriptionType) String() string {
	return string(e)
}

func (e *EmailUnsubscriptionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EmailUnsubscriptionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EmailUnsubscriptionType", str)
	}
	return nil
}

func (e EmailUnsubscriptionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PoolStatus string

const (
	PoolStatusDraft  PoolStatus = "Draft"
	PoolStatusActive PoolStatus = "Active"
	PoolStatusPaused PoolStatus = "Paused"
)

var AllPoolStatus = []PoolStatus{
	PoolStatusDraft,
	PoolStatusActive,
	PoolStatusPaused,
}

func (e PoolStatus) IsValid() bool {
	switch e {
	case PoolStatusDraft, PoolStatusActive, PoolStatusPaused:
		return true
	}
	return false
}

func (e PoolStatus) String() string {
	return string(e)
}

func (e *PoolStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PoolStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PoolStatus", str)
	}
	return nil
}

func (e PoolStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PreverifyEmailResult string

const (
	PreverifyEmailResultInvalid PreverifyEmailResult = "Invalid"
	PreverifyEmailResultRisky   PreverifyEmailResult = "Risky"
	PreverifyEmailResultValid   PreverifyEmailResult = "Valid"
)

var AllPreverifyEmailResult = []PreverifyEmailResult{
	PreverifyEmailResultInvalid,
	PreverifyEmailResultRisky,
	PreverifyEmailResultValid,
}

func (e PreverifyEmailResult) IsValid() bool {
	switch e {
	case PreverifyEmailResultInvalid, PreverifyEmailResultRisky, PreverifyEmailResultValid:
		return true
	}
	return false
}

func (e PreverifyEmailResult) String() string {
	return string(e)
}

func (e *PreverifyEmailResult) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PreverifyEmailResult(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PreverifyEmailResult", str)
	}
	return nil
}

func (e PreverifyEmailResult) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TokenType string

const (
	TokenTypeErc20 TokenType = "ERC20"
)

var AllTokenType = []TokenType{
	TokenTypeErc20,
}

func (e TokenType) IsValid() bool {
	switch e {
	case TokenTypeErc20:
		return true
	}
	return false
}

func (e TokenType) String() string {
	return string(e)
}

func (e *TokenType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TokenType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TokenType", str)
	}
	return nil
}

func (e TokenType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserExperienceType string

const (
	UserExperienceTypeEmailUpsell                       UserExperienceType = "EmailUpsell"
	UserExperienceTypeMaintenanceFeb2023                UserExperienceType = "MaintenanceFeb2023"
	UserExperienceTypeTwitterConnectionOnboardingUpsell UserExperienceType = "TwitterConnectionOnboardingUpsell"
	UserExperienceTypeUpsellMintMemento4                UserExperienceType = "UpsellMintMemento4"
)

var AllUserExperienceType = []UserExperienceType{
	UserExperienceTypeEmailUpsell,
	UserExperienceTypeMaintenanceFeb2023,
	UserExperienceTypeTwitterConnectionOnboardingUpsell,
	UserExperienceTypeUpsellMintMemento4,
}

func (e UserExperienceType) IsValid() bool {
	switch e {
	case UserExperienceTypeEmailUpsell, UserExperienceTypeMaintenanceFeb2023, UserExperienceTypeTwitterConnectionOnboardingUpsell, UserExperienceTypeUpsellMintMemento4:
		return true
	}
	return false
}

func (e UserExperienceType) String() string {
	return string(e)
}

func (e *UserExperienceType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserExperienceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserExperienceType", str)
	}
	return nil
}

func (e UserExperienceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
