// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

var typeConversionMap = map[string]func(object interface{}) (objectAsType interface{}, ok bool){
	"AddUserWalletResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(AddUserWalletResult)
		return obj, ok
	},

	"AuthorizationError": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(AuthorizationError)
		return obj, ok
	},

	"ClaimBulkCreateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClaimBulkCreateResult)
		return obj, ok
	},

	"ClaimBulkDeleteResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClaimBulkDeleteResult)
		return obj, ok
	},

	"ClaimBulkUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClaimBulkUpdateResult)
		return obj, ok
	},

	"ClaimCreateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClaimCreateResult)
		return obj, ok
	},

	"ClaimDeleteResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClaimDeleteResult)
		return obj, ok
	},

	"ClaimUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClaimUpdateResult)
		return obj, ok
	},

	"ClearNotificationsResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ClearNotificationsResult)
		return obj, ok
	},

	"EmailNotificationSettingsUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(EmailNotificationSettingsUpdateResult)
		return obj, ok
	},

	"Error": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(Error)
		return obj, ok
	},

	"LoginResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(LoginResult)
		return obj, ok
	},

	"Node": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(Node)
		return obj, ok
	},

	"NotificationSettingsUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(NotificationSettingsUpdateResult)
		return obj, ok
	},

	"PoolCreateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PoolCreateResult)
		return obj, ok
	},

	"PoolDeleteResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PoolDeleteResult)
		return obj, ok
	},

	"PoolOrUserOrEVMAccount": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PoolOrUserOrEVMAccount)
		return obj, ok
	},

	"PoolResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PoolResult)
		return obj, ok
	},

	"PoolUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PoolUpdateResult)
		return obj, ok
	},

	"PreverifyEmailResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PreverifyEmailResult)
		return obj, ok
	},

	"PushTokenRegisterResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PushTokenRegisterResult)
		return obj, ok
	},

	"PushTokenUnregisterResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(PushTokenUnregisterResult)
		return obj, ok
	},

	"RemoveUserWalletsResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(RemoveUserWalletsResult)
		return obj, ok
	},

	"ResendVerificationEmailResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ResendVerificationEmailResult)
		return obj, ok
	},

	"RoleUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(RoleUpdateResult)
		return obj, ok
	},

	"SearchPoolsResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(SearchPoolsResult)
		return obj, ok
	},

	"SearchUsersResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(SearchUsersResult)
		return obj, ok
	},

	"UnsubscribeFromEmailResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UnsubscribeFromEmailResult)
		return obj, ok
	},

	"UpdateEmailResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UpdateEmailResult)
		return obj, ok
	},

	"UserDeleteResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UserDeleteResult)
		return obj, ok
	},

	"UserOrAccount": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UserOrAccount)
		return obj, ok
	},

	"UserRegisterResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UserRegisterResult)
		return obj, ok
	},

	"UserResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UserResult)
		return obj, ok
	},

	"UserUpdateResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(UserUpdateResult)
		return obj, ok
	},

	"VerifyEmailResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(VerifyEmailResult)
		return obj, ok
	},

	"VerifyTokenResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(VerifyTokenResult)
		return obj, ok
	},

	"ViewerResult": func(object interface{}) (interface{}, bool) {
		obj, ok := object.(ViewerResult)
		return obj, ok
	},
}

func ConvertToModelType(object interface{}, gqlTypeName string) (objectAsType interface{}, ok bool) {
	if conversionFunc, ok := typeConversionMap[gqlTypeName]; ok {
		if convertedObj, ok := conversionFunc(object); ok {
			return convertedObj, true
		}
	}

	return nil, false
}
