version: "3.9"

services:
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"
  postgres:
    build:
      context: "docker/postgres"
      dockerfile: "DOCKERFILE"
      args:
        - PGHOST=${PGHOST}
        - PGPORT=${PGPORT}
        - PGUSER=${PGUSER}
        - PGPASSWORD=${PGPASSWORD}
        - PGDATABASE=${PGDATABASE}
        - PGTESTUSER=${PGTESTUSER}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "${PWD}/docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf"
    command: ["-c", "config-file=/etc/postgresql/postgresql.conf"]
  timescale:
    image: timescale/timescaledb-ha:pg15
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - timescale:/home/postgres/pgdata/data
    environment:
      - POSTGRES_HOST=${TIMESCALE_HOST:-timescale}
      - POSTGRES_USER=${TIMESCALE_USER:-timescale}
      - POSTGRES_DB=${TIMESCALE_DB:-timescale}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD:-''}
      - PGPORT=5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${TIMESCALE_USER:-timescale}"]
      interval: 10s
      timeout: 5s
      retries: 5
  hasura:
    build:
      context: "docker/hasura"
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - timescale
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://${TIMESCALE_USER:-timescale}:${TIMESCALE_PASSWORD:-''}@${TIMESCALE_HOST:-timescale}:5433/${TIMESCALE_DB:-timescale}
      - HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
  indexer:
    build:
      context: "."
      dockerfile: "docker/indexer/Dockerfile"
    environment:
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - ETHERSCAN_URL=${ETHERSCAN_URL}
      - HASURA_HOST=${HASURA_HOST}
      - HASURA_SECRET=${HASURA_SECRET}
      - NODE_URL=${ALCHEMY_API_URL}
      - NODE_WS_URL=${ALCHEMY_WS_API_URL}
      - POSTGRES_DB=${TIMESCALE_DB:-timescale}
      - POSTGRES_HOST=${TIMESCALE_HOST:-timescale}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD:-timescale}
      - POSTGRES_USER=${TIMESCALE_USER:-timescale}
      # - SENTRY_DSN=${SENTRY_DSN}
      # - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - SUBSQUID_URL=https://v2.archive.subsquid.io/network/ethereum-holesky
      - PGPORT=5433
    ports:
      - 46339
      - 9000
    command: ["-C", "compose", "run"]
    depends_on:
      - timescale
      - hasura
  task-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    ports:
      - "8123:8123"
    expose:
      - "8123"
    command: [
      "-host", "0.0.0.0",
      "-port", "8123",
      "-queue", "projects/mutuals-local/locations/here/queues/token-processing",
      "-queue", "projects/mutuals-local/locations/here/queues/indexer-refreshes",
      "-queue", "projects/mutuals-local/locations/here/queues/wallet-validate",
    ]
  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    expose:
      - "8085"
    ports:
      - "8085:8085"
    command: [
      "/bin/bash",
      "-c",
      "gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=mutuals-local"
    ]
volumes:
  timescale: