FROM timescale/timescaledb-ha:pg15

ENV POSTGRES_USER timescale
ENV POSTGRES_DB timescale
ARG PGHOST="localhost"
ARG PGPORT=5433
ARG PGUSER=timescale
ARG PGPASSWORD=timescale
ARG PGDATABASE=timescale
ARG PGTESTUSER=fapiper
ARG PGDATABASE=timescale
