# generated by DipDup 8.4.2

from __future__ import annotations

from pydantic import BaseModel


class PoolCreatedPayload(BaseModel):
    pool: str
    owner: str
    registry: str
    extensions: str
    data: str
