// Code generated by github.com/mutuals/go-mutuals/cmd/dataloaders, DO NOT EDIT.

package dataloader

import (
	"context"
	"time"

	"github.com/jackc/pgx/v4"

	"github.com/mutuals/go-mutuals/service/persist"

	"github.com/mutuals/go-mutuals/db/gen/coredb"
)

type Loaders struct {
	GetAllocationAggregationByIdBatch   *GetAllocationAggregationByIdBatch
	GetAllocationByIdBatch              *GetAllocationByIdBatch
	GetNotificationByIDBatch            *GetNotificationByIDBatch
	GetPoolByChainAddressBatch          *GetPoolByChainAddressBatch
	GetPoolByIdBatch                    *GetPoolByIdBatch
	GetPoolsByUserIDBatch               *GetPoolsByUserIDBatch
	GetUserByAddressAndL1Batch          *GetUserByAddressAndL1Batch
	GetUserByIdBatch                    *GetUserByIdBatch
	GetUserByUsernameBatch              *GetUserByUsernameBatch
	GetUserNotificationsBatch           *GetUserNotificationsBatch
	GetUsersByPositionPaginateBatch     *GetUsersByPositionPaginateBatch
	GetUsersByPositionPersonalizedBatch *GetUsersByPositionPersonalizedBatch
	GetWalletByIDBatch                  *GetWalletByIDBatch
	GetWalletsByUserIDBatch             *GetWalletsByUserIDBatch
}

func NewLoaders(ctx context.Context, q *coredb.Queries, disableCaching bool, preFetchHook PreFetchHook, postFetchHook PostFetchHook) *Loaders {
	loaders := &Loaders{}

	loaders.GetAllocationAggregationByIdBatch = newGetAllocationAggregationByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAllocationAggregationByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetAllocationByIdBatch = newGetAllocationByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAllocationByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetNotificationByIDBatch = newGetNotificationByIDBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetNotificationByIDBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolByChainAddressBatch = newGetPoolByChainAddressBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolByChainAddressBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolByIdBatch = newGetPoolByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolsByUserIDBatch = newGetPoolsByUserIDBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolsByUserIDBatch(q), preFetchHook, postFetchHook)
	loaders.GetUserByAddressAndL1Batch = newGetUserByAddressAndL1Batch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUserByAddressAndL1Batch(q), preFetchHook, postFetchHook)
	loaders.GetUserByIdBatch = newGetUserByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUserByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetUserByUsernameBatch = newGetUserByUsernameBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUserByUsernameBatch(q), preFetchHook, postFetchHook)
	loaders.GetUserNotificationsBatch = newGetUserNotificationsBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUserNotificationsBatch(q), preFetchHook, postFetchHook)
	loaders.GetUsersByPositionPaginateBatch = newGetUsersByPositionPaginateBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUsersByPositionPaginateBatch(q), preFetchHook, postFetchHook)
	loaders.GetUsersByPositionPersonalizedBatch = newGetUsersByPositionPersonalizedBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUsersByPositionPersonalizedBatch(q), preFetchHook, postFetchHook)
	loaders.GetWalletByIDBatch = newGetWalletByIDBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetWalletByIDBatch(q), preFetchHook, postFetchHook)
	loaders.GetWalletsByUserIDBatch = newGetWalletsByUserIDBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetWalletsByUserIDBatch(q), preFetchHook, postFetchHook)

	loaders.GetUserNotificationsBatch.RegisterResultSubscriber(func(result []coredb.Notification) {
		for _, entry := range result {
			loaders.GetNotificationByIDBatch.Prime(loaders.GetNotificationByIDBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetPoolByChainAddressBatch.RegisterResultSubscriber(func(result coredb.Pool) {
		loaders.GetPoolByIdBatch.Prime(loaders.GetPoolByIdBatch.getKeyForResult(result), result)
	})
	loaders.GetPoolsByUserIDBatch.RegisterResultSubscriber(func(result []coredb.Pool) {
		for _, entry := range result {
			loaders.GetPoolByIdBatch.Prime(loaders.GetPoolByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUserByAddressAndL1Batch.RegisterResultSubscriber(func(result coredb.User) {
		loaders.GetUserByIdBatch.Prime(loaders.GetUserByIdBatch.getKeyForResult(result), result)
	})
	loaders.GetUserByUsernameBatch.RegisterResultSubscriber(func(result coredb.User) {
		loaders.GetUserByIdBatch.Prime(loaders.GetUserByIdBatch.getKeyForResult(result), result)
	})
	loaders.GetUsersByPositionPaginateBatch.RegisterResultSubscriber(func(result []coredb.User) {
		for _, entry := range result {
			loaders.GetUserByIdBatch.Prime(loaders.GetUserByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUsersByPositionPersonalizedBatch.RegisterResultSubscriber(func(result []coredb.User) {
		for _, entry := range result {
			loaders.GetUserByIdBatch.Prime(loaders.GetUserByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUserByAddressAndL1Batch.RegisterResultSubscriber(func(result coredb.User) {
		loaders.GetUserByUsernameBatch.Prime(loaders.GetUserByUsernameBatch.getKeyForResult(result), result)
	})
	loaders.GetUserByIdBatch.RegisterResultSubscriber(func(result coredb.User) {
		loaders.GetUserByUsernameBatch.Prime(loaders.GetUserByUsernameBatch.getKeyForResult(result), result)
	})
	loaders.GetUsersByPositionPaginateBatch.RegisterResultSubscriber(func(result []coredb.User) {
		for _, entry := range result {
			loaders.GetUserByUsernameBatch.Prime(loaders.GetUserByUsernameBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUsersByPositionPersonalizedBatch.RegisterResultSubscriber(func(result []coredb.User) {
		for _, entry := range result {
			loaders.GetUserByUsernameBatch.Prime(loaders.GetUserByUsernameBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetWalletsByUserIDBatch.RegisterResultSubscriber(func(result []coredb.Wallet) {
		for _, entry := range result {
			loaders.GetWalletByIDBatch.Prime(loaders.GetWalletByIDBatch.getKeyForResult(entry), entry)
		}
	})

	return loaders
}

func loadGetAllocationAggregationByIdBatch(q *coredb.Queries) func(context.Context, *GetAllocationAggregationByIdBatch, []persist.DBID) ([]coredb.AllocationAggregation, []error) {
	return func(ctx context.Context, d *GetAllocationAggregationByIdBatch, params []persist.DBID) ([]coredb.AllocationAggregation, []error) {
		results := make([]coredb.AllocationAggregation, len(params))
		errors := make([]error, len(params))

		b := q.GetAllocationAggregationByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.AllocationAggregation, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetAllocationByIdBatch(q *coredb.Queries) func(context.Context, *GetAllocationByIdBatch, []persist.DBID) ([]coredb.Allocation, []error) {
	return func(ctx context.Context, d *GetAllocationByIdBatch, params []persist.DBID) ([]coredb.Allocation, []error) {
		results := make([]coredb.Allocation, len(params))
		errors := make([]error, len(params))

		b := q.GetAllocationByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Allocation, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetNotificationByIDBatch(q *coredb.Queries) func(context.Context, *GetNotificationByIDBatch, []persist.DBID) ([]coredb.Notification, []error) {
	return func(ctx context.Context, d *GetNotificationByIDBatch, params []persist.DBID) ([]coredb.Notification, []error) {
		results := make([]coredb.Notification, len(params))
		errors := make([]error, len(params))

		b := q.GetNotificationByIDBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Notification, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetPoolByChainAddressBatch(q *coredb.Queries) func(context.Context, *GetPoolByChainAddressBatch, []coredb.GetPoolByChainAddressBatchParams) ([]coredb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolByChainAddressBatch, params []coredb.GetPoolByChainAddressBatchParams) ([]coredb.Pool, []error) {
		results := make([]coredb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolByChainAddressBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Pool, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetPoolByIdBatch(q *coredb.Queries) func(context.Context, *GetPoolByIdBatch, []persist.DBID) ([]coredb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolByIdBatch, params []persist.DBID) ([]coredb.Pool, []error) {
		results := make([]coredb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Pool, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetPoolsByUserIDBatch(q *coredb.Queries) func(context.Context, *GetPoolsByUserIDBatch, []persist.DBID) ([][]coredb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolsByUserIDBatch, params []persist.DBID) ([][]coredb.Pool, []error) {
		results := make([][]coredb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolsByUserIDBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Pool, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetUserByAddressAndL1Batch(q *coredb.Queries) func(context.Context, *GetUserByAddressAndL1Batch, []coredb.GetUserByAddressAndL1BatchParams) ([]coredb.User, []error) {
	return func(ctx context.Context, d *GetUserByAddressAndL1Batch, params []coredb.GetUserByAddressAndL1BatchParams) ([]coredb.User, []error) {
		results := make([]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUserByAddressAndL1Batch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.User, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetUserByIdBatch(q *coredb.Queries) func(context.Context, *GetUserByIdBatch, []persist.DBID) ([]coredb.User, []error) {
	return func(ctx context.Context, d *GetUserByIdBatch, params []persist.DBID) ([]coredb.User, []error) {
		results := make([]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUserByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.User, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetUserByUsernameBatch(q *coredb.Queries) func(context.Context, *GetUserByUsernameBatch, []string) ([]coredb.User, []error) {
	return func(ctx context.Context, d *GetUserByUsernameBatch, params []string) ([]coredb.User, []error) {
		results := make([]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUserByUsernameBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.User, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetUserNotificationsBatch(q *coredb.Queries) func(context.Context, *GetUserNotificationsBatch, []coredb.GetUserNotificationsBatchParams) ([][]coredb.Notification, []error) {
	return func(ctx context.Context, d *GetUserNotificationsBatch, params []coredb.GetUserNotificationsBatchParams) ([][]coredb.Notification, []error) {
		results := make([][]coredb.Notification, len(params))
		errors := make([]error, len(params))

		b := q.GetUserNotificationsBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Notification, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetUsersByPositionPaginateBatch(q *coredb.Queries) func(context.Context, *GetUsersByPositionPaginateBatch, []coredb.GetUsersByPositionPaginateBatchParams) ([][]coredb.User, []error) {
	return func(ctx context.Context, d *GetUsersByPositionPaginateBatch, params []coredb.GetUsersByPositionPaginateBatchParams) ([][]coredb.User, []error) {
		results := make([][]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUsersByPositionPaginateBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.User, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetUsersByPositionPersonalizedBatch(q *coredb.Queries) func(context.Context, *GetUsersByPositionPersonalizedBatch, [][]string) ([][]coredb.User, []error) {
	return func(ctx context.Context, d *GetUsersByPositionPersonalizedBatch, params [][]string) ([][]coredb.User, []error) {
		results := make([][]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUsersByPositionPersonalizedBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.User, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetWalletByIDBatch(q *coredb.Queries) func(context.Context, *GetWalletByIDBatch, []persist.DBID) ([]coredb.Wallet, []error) {
	return func(ctx context.Context, d *GetWalletByIDBatch, params []persist.DBID) ([]coredb.Wallet, []error) {
		results := make([]coredb.Wallet, len(params))
		errors := make([]error, len(params))

		b := q.GetWalletByIDBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Wallet, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetWalletsByUserIDBatch(q *coredb.Queries) func(context.Context, *GetWalletsByUserIDBatch, []persist.DBID) ([][]coredb.Wallet, []error) {
	return func(ctx context.Context, d *GetWalletsByUserIDBatch, params []persist.DBID) ([][]coredb.Wallet, []error) {
		results := make([][]coredb.Wallet, len(params))
		errors := make([]error, len(params))

		b := q.GetWalletsByUserIDBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Wallet, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}
