// Code generated by github.com/mutuals/go-mutuals/cmd/dataloaders, DO NOT EDIT.

package dataloader

import (
	"context"
	"time"

	"github.com/jackc/pgx/v4"

	"github.com/mutuals/go-mutuals/service/persist"

	"github.com/mutuals/go-mutuals/db/gen/coredb"
)

type Loaders struct {
	GetClaimByIdBatch                   *GetClaimByIdBatch
	GetClaimsByAddressBatch             *GetClaimsByAddressBatch
	GetClaimsByPoolIdBatch              *GetClaimsByPoolIdBatch
	GetNotificationByIdBatch            *GetNotificationByIdBatch
	GetPoolByIdBatch                    *GetPoolByIdBatch
	GetPoolsByAddressBatch              *GetPoolsByAddressBatch
	GetUserByIdBatch                    *GetUserByIdBatch
	GetUserNotificationsBatch           *GetUserNotificationsBatch
	GetUsersByPositionPaginateBatch     *GetUsersByPositionPaginateBatch
	GetUsersByPositionPersonalizedBatch *GetUsersByPositionPersonalizedBatch
}

func NewLoaders(ctx context.Context, q *coredb.Queries, disableCaching bool, preFetchHook PreFetchHook, postFetchHook PostFetchHook) *Loaders {
	loaders := &Loaders{}

	loaders.GetClaimByIdBatch = newGetClaimByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetClaimByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetClaimsByAddressBatch = newGetClaimsByAddressBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetClaimsByAddressBatch(q), preFetchHook, postFetchHook)
	loaders.GetClaimsByPoolIdBatch = newGetClaimsByPoolIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetClaimsByPoolIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetNotificationByIdBatch = newGetNotificationByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetNotificationByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolByIdBatch = newGetPoolByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolsByAddressBatch = newGetPoolsByAddressBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolsByAddressBatch(q), preFetchHook, postFetchHook)
	loaders.GetUserByIdBatch = newGetUserByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUserByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetUserNotificationsBatch = newGetUserNotificationsBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUserNotificationsBatch(q), preFetchHook, postFetchHook)
	loaders.GetUsersByPositionPaginateBatch = newGetUsersByPositionPaginateBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUsersByPositionPaginateBatch(q), preFetchHook, postFetchHook)
	loaders.GetUsersByPositionPersonalizedBatch = newGetUsersByPositionPersonalizedBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetUsersByPositionPersonalizedBatch(q), preFetchHook, postFetchHook)

	loaders.GetClaimsByAddressBatch.RegisterResultSubscriber(func(result []coredb.Claim) {
		for _, entry := range result {
			loaders.GetClaimByIdBatch.Prime(loaders.GetClaimByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetClaimsByPoolIdBatch.RegisterResultSubscriber(func(result []coredb.Claim) {
		for _, entry := range result {
			loaders.GetClaimByIdBatch.Prime(loaders.GetClaimByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUserNotificationsBatch.RegisterResultSubscriber(func(result []coredb.Notification) {
		for _, entry := range result {
			loaders.GetNotificationByIdBatch.Prime(loaders.GetNotificationByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetPoolsByAddressBatch.RegisterResultSubscriber(func(result []coredb.Pool) {
		for _, entry := range result {
			loaders.GetPoolByIdBatch.Prime(loaders.GetPoolByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUsersByPositionPaginateBatch.RegisterResultSubscriber(func(result []coredb.User) {
		for _, entry := range result {
			loaders.GetUserByIdBatch.Prime(loaders.GetUserByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetUsersByPositionPersonalizedBatch.RegisterResultSubscriber(func(result []coredb.User) {
		for _, entry := range result {
			loaders.GetUserByIdBatch.Prime(loaders.GetUserByIdBatch.getKeyForResult(entry), entry)
		}
	})

	return loaders
}

func loadGetClaimByIdBatch(q *coredb.Queries) func(context.Context, *GetClaimByIdBatch, []persist.DBID) ([]coredb.Claim, []error) {
	return func(ctx context.Context, d *GetClaimByIdBatch, params []persist.DBID) ([]coredb.Claim, []error) {
		results := make([]coredb.Claim, len(params))
		errors := make([]error, len(params))

		b := q.GetClaimByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Claim, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetClaimsByAddressBatch(q *coredb.Queries) func(context.Context, *GetClaimsByAddressBatch, []persist.Address) ([][]coredb.Claim, []error) {
	return func(ctx context.Context, d *GetClaimsByAddressBatch, params []persist.Address) ([][]coredb.Claim, []error) {
		results := make([][]coredb.Claim, len(params))
		errors := make([]error, len(params))

		b := q.GetClaimsByAddressBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Claim, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetClaimsByPoolIdBatch(q *coredb.Queries) func(context.Context, *GetClaimsByPoolIdBatch, []persist.DBID) ([][]coredb.Claim, []error) {
	return func(ctx context.Context, d *GetClaimsByPoolIdBatch, params []persist.DBID) ([][]coredb.Claim, []error) {
		results := make([][]coredb.Claim, len(params))
		errors := make([]error, len(params))

		b := q.GetClaimsByPoolIdBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Claim, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetNotificationByIdBatch(q *coredb.Queries) func(context.Context, *GetNotificationByIdBatch, []persist.DBID) ([]coredb.Notification, []error) {
	return func(ctx context.Context, d *GetNotificationByIdBatch, params []persist.DBID) ([]coredb.Notification, []error) {
		results := make([]coredb.Notification, len(params))
		errors := make([]error, len(params))

		b := q.GetNotificationByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Notification, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetPoolByIdBatch(q *coredb.Queries) func(context.Context, *GetPoolByIdBatch, []persist.DBID) ([]coredb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolByIdBatch, params []persist.DBID) ([]coredb.Pool, []error) {
		results := make([]coredb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.Pool, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetPoolsByAddressBatch(q *coredb.Queries) func(context.Context, *GetPoolsByAddressBatch, []persist.Address) ([][]coredb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolsByAddressBatch, params []persist.Address) ([][]coredb.Pool, []error) {
		results := make([][]coredb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolsByAddressBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Pool, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetUserByIdBatch(q *coredb.Queries) func(context.Context, *GetUserByIdBatch, []persist.DBID) ([]coredb.User, []error) {
	return func(ctx context.Context, d *GetUserByIdBatch, params []persist.DBID) ([]coredb.User, []error) {
		results := make([]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUserByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r coredb.User, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetUserNotificationsBatch(q *coredb.Queries) func(context.Context, *GetUserNotificationsBatch, []coredb.GetUserNotificationsBatchParams) ([][]coredb.Notification, []error) {
	return func(ctx context.Context, d *GetUserNotificationsBatch, params []coredb.GetUserNotificationsBatchParams) ([][]coredb.Notification, []error) {
		results := make([][]coredb.Notification, len(params))
		errors := make([]error, len(params))

		b := q.GetUserNotificationsBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.Notification, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetUsersByPositionPaginateBatch(q *coredb.Queries) func(context.Context, *GetUsersByPositionPaginateBatch, []coredb.GetUsersByPositionPaginateBatchParams) ([][]coredb.User, []error) {
	return func(ctx context.Context, d *GetUsersByPositionPaginateBatch, params []coredb.GetUsersByPositionPaginateBatchParams) ([][]coredb.User, []error) {
		results := make([][]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUsersByPositionPaginateBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.User, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetUsersByPositionPersonalizedBatch(q *coredb.Queries) func(context.Context, *GetUsersByPositionPersonalizedBatch, [][]string) ([][]coredb.User, []error) {
	return func(ctx context.Context, d *GetUsersByPositionPersonalizedBatch, params [][]string) ([][]coredb.User, []error) {
		results := make([][]coredb.User, len(params))
		errors := make([]error, len(params))

		b := q.GetUsersByPositionPersonalizedBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []coredb.User, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}
