// Code generated by github.com/mutuals/go-mutuals/cmd/dataloaders, DO NOT EDIT.

package indexerdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v4"

	"github.com/mutuals/go-mutuals/db/gen/indexerdb"

	"github.com/mutuals/go-mutuals/service/persist"
)

type Loaders struct {
	GetAccountByAddressBatch                *GetAccountByAddressBatch
	GetAccountByIdBatch                     *GetAccountByIdBatch
	GetAccountsByAddressesBatch             *GetAccountsByAddressesBatch
	GetAccountsByAddressesPaginateBatch     *GetAccountsByAddressesPaginateBatch
	GetPoolContractByIdBatch                *GetPoolContractByIdBatch
	GetPoolContractsByAccountAddressBatch   *GetPoolContractsByAccountAddressBatch
	GetPoolContractsByAccountAddressesBatch *GetPoolContractsByAccountAddressesBatch
	GetPoolContractsByIdsBatch              *GetPoolContractsByIdsBatch
	GetTokenBalancesByPoolIdBatch           *GetTokenBalancesByPoolIdBatch
	GetTokenBalancesByPoolIdsBatch          *GetTokenBalancesByPoolIdsBatch
	GetTokenByIdBatch                       *GetTokenByIdBatch
	GetTokensByIdsBatch                     *GetTokensByIdsBatch
}

func NewLoaders(ctx context.Context, q *indexerdb.Queries, disableCaching bool, preFetchHook PreFetchHook, postFetchHook PostFetchHook) *Loaders {
	loaders := &Loaders{}

	loaders.GetAccountByAddressBatch = newGetAccountByAddressBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAccountByAddressBatch(q), preFetchHook, postFetchHook)
	loaders.GetAccountByIdBatch = newGetAccountByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAccountByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetAccountsByAddressesBatch = newGetAccountsByAddressesBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAccountsByAddressesBatch(q), preFetchHook, postFetchHook)
	loaders.GetAccountsByAddressesPaginateBatch = newGetAccountsByAddressesPaginateBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAccountsByAddressesPaginateBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolContractByIdBatch = newGetPoolContractByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolContractByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolContractsByAccountAddressBatch = newGetPoolContractsByAccountAddressBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolContractsByAccountAddressBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolContractsByAccountAddressesBatch = newGetPoolContractsByAccountAddressesBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolContractsByAccountAddressesBatch(q), preFetchHook, postFetchHook)
	loaders.GetPoolContractsByIdsBatch = newGetPoolContractsByIdsBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetPoolContractsByIdsBatch(q), preFetchHook, postFetchHook)
	loaders.GetTokenBalancesByPoolIdBatch = newGetTokenBalancesByPoolIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetTokenBalancesByPoolIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetTokenBalancesByPoolIdsBatch = newGetTokenBalancesByPoolIdsBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetTokenBalancesByPoolIdsBatch(q), preFetchHook, postFetchHook)
	loaders.GetTokenByIdBatch = newGetTokenByIdBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetTokenByIdBatch(q), preFetchHook, postFetchHook)
	loaders.GetTokensByIdsBatch = newGetTokensByIdsBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetTokensByIdsBatch(q), preFetchHook, postFetchHook)

	loaders.GetAccountByAddressBatch.RegisterResultSubscriber(func(result indexerdb.Account) {
		loaders.GetAccountByIdBatch.Prime(loaders.GetAccountByIdBatch.getKeyForResult(result), result)
	})
	loaders.GetAccountsByAddressesBatch.RegisterResultSubscriber(func(result []indexerdb.Account) {
		for _, entry := range result {
			loaders.GetAccountByIdBatch.Prime(loaders.GetAccountByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetAccountsByAddressesPaginateBatch.RegisterResultSubscriber(func(result []indexerdb.Account) {
		for _, entry := range result {
			loaders.GetAccountByIdBatch.Prime(loaders.GetAccountByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetPoolContractsByAccountAddressBatch.RegisterResultSubscriber(func(result []indexerdb.Pool) {
		for _, entry := range result {
			loaders.GetPoolContractByIdBatch.Prime(loaders.GetPoolContractByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetPoolContractsByAccountAddressesBatch.RegisterResultSubscriber(func(result []indexerdb.Pool) {
		for _, entry := range result {
			loaders.GetPoolContractByIdBatch.Prime(loaders.GetPoolContractByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetPoolContractsByIdsBatch.RegisterResultSubscriber(func(result []indexerdb.Pool) {
		for _, entry := range result {
			loaders.GetPoolContractByIdBatch.Prime(loaders.GetPoolContractByIdBatch.getKeyForResult(entry), entry)
		}
	})
	loaders.GetTokensByIdsBatch.RegisterResultSubscriber(func(result []indexerdb.Token) {
		for _, entry := range result {
			loaders.GetTokenByIdBatch.Prime(loaders.GetTokenByIdBatch.getKeyForResult(entry), entry)
		}
	})

	return loaders
}

func loadGetAccountByAddressBatch(q *indexerdb.Queries) func(context.Context, *GetAccountByAddressBatch, []string) ([]indexerdb.Account, []error) {
	return func(ctx context.Context, d *GetAccountByAddressBatch, params []string) ([]indexerdb.Account, []error) {
		results := make([]indexerdb.Account, len(params))
		errors := make([]error, len(params))

		b := q.GetAccountByAddressBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r indexerdb.Account, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetAccountByIdBatch(q *indexerdb.Queries) func(context.Context, *GetAccountByIdBatch, []persist.DBID) ([]indexerdb.Account, []error) {
	return func(ctx context.Context, d *GetAccountByIdBatch, params []persist.DBID) ([]indexerdb.Account, []error) {
		results := make([]indexerdb.Account, len(params))
		errors := make([]error, len(params))

		b := q.GetAccountByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r indexerdb.Account, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetAccountsByAddressesBatch(q *indexerdb.Queries) func(context.Context, *GetAccountsByAddressesBatch, [][]string) ([][]indexerdb.Account, []error) {
	return func(ctx context.Context, d *GetAccountsByAddressesBatch, params [][]string) ([][]indexerdb.Account, []error) {
		results := make([][]indexerdb.Account, len(params))
		errors := make([]error, len(params))

		b := q.GetAccountsByAddressesBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.Account, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetAccountsByAddressesPaginateBatch(q *indexerdb.Queries) func(context.Context, *GetAccountsByAddressesPaginateBatch, []indexerdb.GetAccountsByAddressesPaginateBatchParams) ([][]indexerdb.Account, []error) {
	return func(ctx context.Context, d *GetAccountsByAddressesPaginateBatch, params []indexerdb.GetAccountsByAddressesPaginateBatchParams) ([][]indexerdb.Account, []error) {
		results := make([][]indexerdb.Account, len(params))
		errors := make([]error, len(params))

		b := q.GetAccountsByAddressesPaginateBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.Account, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetPoolContractByIdBatch(q *indexerdb.Queries) func(context.Context, *GetPoolContractByIdBatch, []persist.DBID) ([]indexerdb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolContractByIdBatch, params []persist.DBID) ([]indexerdb.Pool, []error) {
		results := make([]indexerdb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolContractByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r indexerdb.Pool, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetPoolContractsByAccountAddressBatch(q *indexerdb.Queries) func(context.Context, *GetPoolContractsByAccountAddressBatch, []string) ([][]indexerdb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolContractsByAccountAddressBatch, params []string) ([][]indexerdb.Pool, []error) {
		results := make([][]indexerdb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolContractsByAccountAddressBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.Pool, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetPoolContractsByAccountAddressesBatch(q *indexerdb.Queries) func(context.Context, *GetPoolContractsByAccountAddressesBatch, []string) ([][]indexerdb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolContractsByAccountAddressesBatch, params []string) ([][]indexerdb.Pool, []error) {
		results := make([][]indexerdb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolContractsByAccountAddressesBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.Pool, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetPoolContractsByIdsBatch(q *indexerdb.Queries) func(context.Context, *GetPoolContractsByIdsBatch, []persist.DBID) ([][]indexerdb.Pool, []error) {
	return func(ctx context.Context, d *GetPoolContractsByIdsBatch, params []persist.DBID) ([][]indexerdb.Pool, []error) {
		results := make([][]indexerdb.Pool, len(params))
		errors := make([]error, len(params))

		b := q.GetPoolContractsByIdsBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.Pool, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetTokenBalancesByPoolIdBatch(q *indexerdb.Queries) func(context.Context, *GetTokenBalancesByPoolIdBatch, []persist.DBID) ([][]indexerdb.TokenBalance, []error) {
	return func(ctx context.Context, d *GetTokenBalancesByPoolIdBatch, params []persist.DBID) ([][]indexerdb.TokenBalance, []error) {
		results := make([][]indexerdb.TokenBalance, len(params))
		errors := make([]error, len(params))

		b := q.GetTokenBalancesByPoolIdBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.TokenBalance, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetTokenBalancesByPoolIdsBatch(q *indexerdb.Queries) func(context.Context, *GetTokenBalancesByPoolIdsBatch, []persist.DBID) ([][]indexerdb.TokenBalance, []error) {
	return func(ctx context.Context, d *GetTokenBalancesByPoolIdsBatch, params []persist.DBID) ([][]indexerdb.TokenBalance, []error) {
		results := make([][]indexerdb.TokenBalance, len(params))
		errors := make([]error, len(params))

		b := q.GetTokenBalancesByPoolIdsBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.TokenBalance, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}

func loadGetTokenByIdBatch(q *indexerdb.Queries) func(context.Context, *GetTokenByIdBatch, []persist.DBID) ([]indexerdb.Token, []error) {
	return func(ctx context.Context, d *GetTokenByIdBatch, params []persist.DBID) ([]indexerdb.Token, []error) {
		results := make([]indexerdb.Token, len(params))
		errors := make([]error, len(params))

		b := q.GetTokenByIdBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r indexerdb.Token, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}

func loadGetTokensByIdsBatch(q *indexerdb.Queries) func(context.Context, *GetTokensByIdsBatch, []persist.DBID) ([][]indexerdb.Token, []error) {
	return func(ctx context.Context, d *GetTokensByIdsBatch, params []persist.DBID) ([][]indexerdb.Token, []error) {
		results := make([][]indexerdb.Token, len(params))
		errors := make([]error, len(params))

		b := q.GetTokensByIdsBatch(ctx, params)
		defer b.Close()

		b.Query(func(i int, r []indexerdb.Token, err error) {
			results[i], errors[i] = r, err
		})

		return results, errors
	}
}
