// Code generated by github.com/mutuals/go-mutuals/cmd/dataloaders, DO NOT EDIT.

package indexerdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v4"

	"github.com/mutuals/go-mutuals/service/persist"

	"github.com/mutuals/go-mutuals/db/gen/indexerdb"
)

type Loaders struct {
	GetAccountByIDBatch *GetAccountByIDBatch
}

func NewLoaders(ctx context.Context, q *indexerdb.Queries, disableCaching bool, preFetchHook PreFetchHook, postFetchHook PostFetchHook) *Loaders {
	loaders := &Loaders{}

	loaders.GetAccountByIDBatch = newGetAccountByIDBatch(ctx, 100, time.Duration(2000000), !disableCaching, true, loadGetAccountByIDBatch(q), preFetchHook, postFetchHook)

	return loaders
}

func loadGetAccountByIDBatch(q *indexerdb.Queries) func(context.Context, *GetAccountByIDBatch, []persist.DBID) ([]indexerdb.Account, []error) {
	return func(ctx context.Context, d *GetAccountByIDBatch, params []persist.DBID) ([]indexerdb.Account, []error) {
		results := make([]indexerdb.Account, len(params))
		errors := make([]error, len(params))

		b := q.GetAccountByIDBatch(ctx, params)
		defer b.Close()

		b.QueryRow(func(i int, r indexerdb.Account, err error) {
			results[i], errors[i] = r, err
			if errors[i] == pgx.ErrNoRows {
				errors[i] = d.getNotFoundError(params[i])
			}
		})

		return results, errors
	}
}
