// Code generated by github.com/mutuals/go-mutuals/cmd/dataloaders, DO NOT EDIT.

package indexerdb

import (
	"context"
	"time"

	"github.com/mutuals/go-mutuals/cmd/dataloaders/generator"

	"github.com/mutuals/go-mutuals/db/gen/indexerdb"
)

type autoCacheWithKey[TKey any, TResult any] interface {
	getKeyForResult(TResult) TKey
}

type autoCacheWithKeys[TKey any, TResult any] interface {
	getKeysForResult(TResult) []TKey
}

type notFoundErrorProvider[TKey any] interface {
	getNotFoundError(TKey) error
}

type PreFetchHook func(context.Context, string) context.Context
type PostFetchHook func(context.Context, string)

// GetHoldersByAddressBatch batches and caches requests
type GetHoldersByAddressBatch struct {
	generator.Dataloader[string, []indexerdb.Holder]
}

// newGetHoldersByAddressBatch creates a new GetHoldersByAddressBatch with the given settings, functions, and options
func newGetHoldersByAddressBatch(
	ctx context.Context,
	maxBatchSize int,
	batchTimeout time.Duration,
	cacheResults bool,
	publishResults bool,
	fetch func(context.Context, *GetHoldersByAddressBatch, []string) ([][]indexerdb.Holder, []error),
	preFetchHook PreFetchHook,
	postFetchHook PostFetchHook,
) *GetHoldersByAddressBatch {
	d := &GetHoldersByAddressBatch{}

	fetchWithHooks := func(ctx context.Context, keys []string) ([][]indexerdb.Holder, []error) {
		// Allow the preFetchHook to modify and return a new context
		if preFetchHook != nil {
			ctx = preFetchHook(ctx, "GetHoldersByAddressBatch")
		}

		results, errors := fetch(ctx, d, keys)

		if postFetchHook != nil {
			postFetchHook(ctx, "GetHoldersByAddressBatch")
		}

		return results, errors
	}

	d.Dataloader = *generator.NewDataloader(ctx, maxBatchSize, batchTimeout, cacheResults, publishResults, fetchWithHooks)
	return d
}
