// Code generated by github.com/mutuals/go-mutuals/cmd/dataloaders, DO NOT EDIT.

package indexerdb

import (
	"context"
	"time"

	"github.com/mutuals/go-mutuals/cmd/dataloaders/generator"

	"github.com/mutuals/go-mutuals/service/persist"

	"github.com/mutuals/go-mutuals/db/gen/indexerdb"
)

type autoCacheWithKey[TKey any, TResult any] interface {
	getKeyForResult(TResult) TKey
}

type autoCacheWithKeys[TKey any, TResult any] interface {
	getKeysForResult(TResult) []TKey
}

type notFoundErrorProvider[TKey any] interface {
	getNotFoundError(TKey) error
}

type PreFetchHook func(context.Context, string) context.Context
type PostFetchHook func(context.Context, string)

// GetAccountByIDBatch batches and caches requests
type GetAccountByIDBatch struct {
	generator.Dataloader[persist.DBID, indexerdb.Account]
}

// newGetAccountByIDBatch creates a new GetAccountByIDBatch with the given settings, functions, and options
func newGetAccountByIDBatch(
	ctx context.Context,
	maxBatchSize int,
	batchTimeout time.Duration,
	cacheResults bool,
	publishResults bool,
	fetch func(context.Context, *GetAccountByIDBatch, []persist.DBID) ([]indexerdb.Account, []error),
	preFetchHook PreFetchHook,
	postFetchHook PostFetchHook,
) *GetAccountByIDBatch {
	d := &GetAccountByIDBatch{}

	fetchWithHooks := func(ctx context.Context, keys []persist.DBID) ([]indexerdb.Account, []error) {
		// Allow the preFetchHook to modify and return a new context
		if preFetchHook != nil {
			ctx = preFetchHook(ctx, "GetAccountByIDBatch")
		}

		results, errors := fetch(ctx, d, keys)

		if postFetchHook != nil {
			postFetchHook(ctx, "GetAccountByIDBatch")
		}

		return results, errors
	}

	d.Dataloader = *generator.NewDataloader(ctx, maxBatchSize, batchTimeout, cacheResults, publishResults, fetchWithHooks)
	return d
}

func (*GetAccountByIDBatch) getKeyForResult(result indexerdb.Account) persist.DBID {
	return result.ID
}
