"""
Any field decorated with the @experimental directive should not be used in production.
It will not conform to our rules around breaking changes.
"""
directive @experimental on FIELD_DEFINITION

directive @goField(
  forceResolver: Boolean
  name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @authRequired on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @basicAuth(allowed: [BasicAuthType!]!) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @frontendBuildAuth on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @scrub on INPUT_FIELD_DEFINITION

directive @restrictEnvironment(
  allowed: [String!]!
) on INPUT_FIELD_DEFINITION | INPUT_OBJECT | FIELD_DEFINITION | OBJECT

scalar Time
scalar Address
scalar PubKey
scalar HexString
scalar JSON

enum ErrorPolicyEnum {
  IGNORE_FAILED
  REJECT_EVERYTHING
  REJECT_FAILED_ROWS
}

enum BasicAuthType {
  Retool
  Monitoring
}

interface Node {
  id: ID!
}

type DeletedNode implements Node {
  id: ID!
}

interface Error {
  message: String!
}

#-------------------------------------------------------------------------------
# PAGINATION
#-------------------------------------------------------------------------------

type PageInfo {
  total: Int
  size: Int!
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: String!
  endCursor: String!
}

#-------------------------------------------------------------------------------
# ACCOUNT AND CONTRACTS
#-------------------------------------------------------------------------------

enum EVMAccountType {
  EOA
  Contract
}

type EVMAccount implements Node {
  id: ID!
  address: Address!
  accountType: EVMAccountType!
  selfPools: [Pool!] @goField(forceResolver: true)
  balances: [TokenBalance!] @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

type PoolFactory implements Node {
  id: ID!
  address: Address!
  chainId: Int!
  poolCount: Int!
  owner: EVMAccount!
  createdAt: Time!
  updatedAt: Time!
}

type ModuleRegistry implements Node {
  id: ID!
  address: Address!
  chainId: Int!
  moduleCount: Int!
  owner: EVMAccount! @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# USER
#-------------------------------------------------------------------------------

enum Role {
  ADMIN
  BETA_TESTER
  EARLY_ACCESS
}

type User implements Node {
  id: ID!
  roles: [Role] @goField(forceResolver: true)
  pools: [Pool] @goField(forceResolver: true)
}

union UserOrEVMAccount = User | EVMAccount

type UserEdge {
  node: User
  cursor: String
}

type UsersConnection {
  edges: [UserEdge]
  pageInfo: PageInfo!
}

# -------------------------------------------------------------------------------
# TOKEN
#-------------------------------------------------------------------------------

enum TokenType {
  ERC20
  ERC721
  ERC1155
}

type Token implements Node {
  id: ID!
  address: Address!
  chainId: Int!
  tokenType: TokenType!
  symbol: String!
  name: String!
  decimals: Int!
  logo: String
  thumbnail: String
  validated: Int
  possibleSpam: Boolean
  createdAt: Time!
  updatedAt: Time!
}

type TokenBalance implements Node {
  id: ID!
  chainId: Int!
  token: Token! @goField(forceResolver: true)
  holder: PoolOrUserOrEVMAccount! @goField(forceResolver: true)
  amount: HexString!
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# MODULES
#-------------------------------------------------------------------------------

enum ModuleType {
  Validation
  Distribution
}

type Module implements Node {
  id: ID!
  address: Address!
  chainId: Int!
  moduleRegistry: ModuleRegistry! @goField(forceResolver: true)
  moduleId: String!
  moduleType: ModuleType!
  permissions: [String!]
  data: JSON
  name: String!
  description: String!
  createdAt: Time!
  updatedAt: Time!
}

type Claim implements Node {
  id: ID!
  label: String!
  path: String!
  parent: Claim @goField(forceResolver: true)
  children: [Claim!] @goField(forceResolver: true)
  pool: Pool! @goField(forceResolver: true)
  validation: Module! @goField(forceResolver: true)
  validationData: JSON
  distribution: Module! @goField(forceResolver: true)
  distributionData: JSON
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# POOL
#-------------------------------------------------------------------------------

enum PoolStatus {
  Draft
  Active
  Paused
}

type Pool implements Node {
  id: ID!
  name: String!
  description: String!
  image: String!
  donationBps: Int!
  slug: String!
  status: PoolStatus!
  owner: UserOrEVMAccount! @goField(forceResolver: true)
  contract: PoolContract @goField(forceResolver: true)
  claims: [Claim!] @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

union PoolOrUserOrEVMAccount = Pool | User | EVMAccount

type PoolContract implements Node {
  id: ID!
  address: Address!
  chainId: Int!
  status: PoolStatus!
  poolFactory: PoolFactory! @goField(forceResolver: true)
  account: EVMAccount! @goField(forceResolver: true)
  owner: EVMAccount! @goField(forceResolver: true)
  dayBalance: [PoolDayBalance!]! @goField(forceResolver: true)
  hourBalance: [PoolHourBalance!]! @goField(forceResolver: true)
  deposits: [Deposit!]! @goField(forceResolver: true)
  withdrawals: [Withdrawal!]! @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

type PoolDayBalance implements Node {
  id: ID!
  chainId: Int!
  date: Time!
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  amount: HexString!
  createdAt: Time!
  updatedAt: Time!
}

type PoolHourBalance implements Node {
  id: ID!
  chainId: Int!
  date: Time!
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  amount: HexString!
  createdAt: Time!
  updatedAt: Time!
}


#-------------------------------------------------------------------------------
# POOL
#-------------------------------------------------------------------------------
# EVENT
#-------------------------------------------------------------------------------

enum ReportWindow {
  LAST_5_DAYS
  LAST_7_DAYS
  ALL_TIME
}

type Tx implements Node {
  id: ID!
  gasUsed: HexString!
  gasPrice: HexString!
  createdAt: Time!
  updatedAt: Time!
  deposits: [Deposit]! @goField(forceResolver: true)
  withdrawals: [Withdrawal]! @goField(forceResolver: true)
}

type Deposit implements Node {
  id: ID!
  transaction: Tx! @goField(forceResolver: true)
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  from: Address!
  to: Address!
  origin: String!
  amount: HexString!
  logIndex: Int
  createdAt: Time!
  updatedAt: Time!
}

type Withdrawal implements Node {
  id: ID!
  transaction: Tx! @goField(forceResolver: true)
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  from: Address!
  to: Address!
  origin: String!
  amount: HexString!
  logIndex: Int
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# SEARCH
#-------------------------------------------------------------------------------

type UserSearchResult {
  user: User
}

type SearchUsersPayload {
  results: [UserSearchResult!]
}

type PoolSearchResult {
  pool: Pool
}

type SearchPoolsPayload {
  results: [PoolSearchResult!]
}

#-------------------------------------------------------------------------------
# ERRORS
#-------------------------------------------------------------------------------

type ErrAuthenticationFailed implements Error {
  message: String!
}

type ErrUserAlreadyExists implements Error {
  message: String!
}

type ErrUsernameNotAvailable implements Error {
  message: String!
}

type ErrAddressOwnedByUser implements Error {
  message: String!
}

type ErrUserNotFound implements Error {
  message: String!
}

type ErrPoolNotFound implements Error {
  message: String!
}

type ErrTokenNotFound implements Error {
  message: String!
}

type ErrInvalidInput implements Error {
  message: String!
  parameters: [String!]!
  reasons: [String!]!
}

type ErrNoCookie implements Error {
  message: String!
}

type ErrInvalidToken implements Error {
  message: String!
}

type ErrSessionInvalidated implements Error {
  message: String!
}

type ErrDoesNotOwnRequiredToken implements Error {
  message: String!
}

union AuthorizationError =
  ErrNoCookie
  | ErrInvalidToken
  | ErrSessionInvalidated
  | ErrDoesNotOwnRequiredToken

type ErrNotAuthorized implements Error {
  message: String!
  cause: AuthorizationError!
}

type ErrSyncFailed implements Error {
  message: String!
}


#-------------------------------------------------------------------------------
# QUERY
#-------------------------------------------------------------------------------

union UserResult = User | ErrNotAuthorized | ErrUserNotFound | ErrInvalidInput
union PoolResult = Pool | ErrPoolNotFound | ErrInvalidInput
union SearchUsersResult = SearchUsersPayload | ErrInvalidInput
union SearchPoolsResult = SearchPoolsPayload | ErrInvalidInput

type Query {
  node(id: ID!): Node
  viewer: UserResult @authRequired
  userByUsername(username: String!): UserResult!
  userById(id: ID!): UserResult!
  userByAddress(address: Address!): UserResult!

  """Look up a pool by ID, slug, or contract ID."""
  pool(
    id: ID
    slug: String
    contractId: ID
  ): PoolResult!

  searchUsers(
    query: String!
    limit: Int
    usernameWeight: Float
  ): SearchUsersResult!

  searchPools(
    query: String!
    limit: Int
    nameWeight: Float
    descriptionWeight: Float
  ): SearchPoolsResult!


  usersByRole(role: Role!, before: String, after: String, first: Int, last: Int): UsersConnection
  @basicAuth(allowed: [Retool])
}

#-------------------------------------------------------------------------------
# MUTATIONS
#-------------------------------------------------------------------------------

# USER MUTATIONS

type UserRegisterPayload {
  user: User!
  requiresConfirmation: Boolean
}

union UserRegisterResult = UserRegisterPayload | ErrAuthenticationFailed | ErrUserAlreadyExists | ErrInvalidInput | ErrDoesNotOwnRequiredToken

type UserUpdatePayload {
  user: User!
}

input UserUpdateInput {
  username: String
}

union UserUpdateResult = UserUpdatePayload | ErrNotAuthorized | ErrUsernameNotAvailable | ErrInvalidInput

type UserDeletePayload {
  user: User
}

union UserDeleteResult = UserDeletePayload | ErrNotAuthorized | ErrInvalidInput

# WALLET MUTATIONS

type AddUserWalletPayload {
  viewer: User!
}

union AddUserWalletResult = AddUserWalletPayload | ErrAuthenticationFailed | ErrNotAuthorized | ErrInvalidInput | ErrAddressOwnedByUser

type RemoveUserWalletsPayload {
  viewer: User!
}

union RemoveUserWalletsResult = RemoveUserWalletsPayload | ErrNotAuthorized | ErrInvalidInput

# AUTH MUTATIONS

type LoginPayload {
  viewer: User!
}

union LoginResult = LoginPayload | ErrUserNotFound | ErrAuthenticationFailed | ErrDoesNotOwnRequiredToken

type LogoutPayload {
  viewer: User
}

type VerifyTokenPayload {
  user: User!
  isValid: Boolean!
}

union VerifyTokenResult = VerifyTokenPayload | ErrNotAuthorized | ErrInvalidInput


# ROLE MUTATIONS

type RoleUpdatePayload {
  user: User!
}

input RoleUpdateInput {
  addRoles: [Role!]
  removeRoles: [Role!]
}

union RoleUpdateResult = RoleUpdatePayload | ErrNotAuthorized | ErrInvalidInput

# CLAIM MUTATIONS

type ClaimCreatePayload {
  claim: Claim!
}

input ClaimCreateInput {
  label: String!
  validationData: JSON
  distributionData: JSON
  parent: String
  children: [String!]
  validationId: String!
  distributionId: String!
}

union ClaimCreateResult = ClaimCreatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimUpdatePayload {
  claim: Claim!
}

input ClaimUpdateInput {
  claimId: ID!
  validationData: JSON
  distributionData: JSON
  parent: ID
  children: [ID!]
  validationId: String
  distributionId: String
}

union ClaimUpdateResult = ClaimUpdatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimDeletePayload {
  claim: Claim!
}

union ClaimDeleteResult = ClaimDeletePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimBulkCreatePayload {
  count: Int!
  claims: [Claim!]!
}

input ClaimBulkCreateInput {
  validationData: JSON
  distributionData: JSON
  parent: ID
  children: [ID!]
  validationId: String!
  distributionId: String!
}

union ClaimBulkCreateResult = ClaimBulkCreatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimBulkUpdatePayload {
  count: Int!
  claims: [Claim!]!
}

input ClaimBulkUpdateInput {
  claimId: ID!
  validationData: JSON
  distributionData: JSON
  parent: ID
  children: [ID!]
  validationId: String
  distributionId: String
}

union ClaimBulkUpdateResult = ClaimBulkUpdatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimBulkDeletePayload {
  count: Int!
}

union ClaimBulkDeleteResult = ClaimBulkDeletePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

# POOL MUTATIONS

type PoolCreatePayload {
  pool: Pool!
}

input PoolCreateInput {
  owner: String
  private: Boolean
  name: String!
  description: String!
  image: String
  donationBps: Int
  slug: String!
  addClaims: [ClaimCreateInput!]
}

union PoolCreateResult = PoolCreatePayload | ErrNotAuthorized | ErrInvalidInput

type PoolUpdatePayload {
  pool: Pool!
}

input PoolUpdateInput {
  private: Boolean
  name: String
  description: String
  image: String
  donationBps: Int
  slug: String
  addClaims: [ClaimCreateInput!]
  updateClaims: [ClaimUpdateInput!]
  removeClaims: [ID!]
}

union PoolUpdateResult = PoolUpdatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type PoolDeletePayload {
  pool: Pool!
}

union PoolDeleteResult = PoolDeletePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type Mutation {
  # User
  userRegister: UserRegisterResult! @authRequired
  userUpdate(input: UserUpdateInput!): UserUpdateResult! @authRequired
  userRequestDeletion(redirectUrl: String!): UserDeleteResult! @authRequired
  userDelete(token: String!): UserDeleteResult! @authRequired

  # Roles
  roleUpdate(role: Role!, input: RoleUpdateInput!): RoleUpdateResult! @authRequired

  # Claims
  poolClaimCreate(poolId: ID!, input: ClaimCreateInput!): ClaimCreateResult! @authRequired
  poolClaimUpdate(poolId: ID!, input: ClaimUpdateInput!): ClaimUpdateResult! @authRequired
  poolClaimDelete(poolId: ID!, claimId: ID!): ClaimDeleteResult! @authRequired
  poolClaimBulkCreate(errorPolicy: ErrorPolicyEnum, poolId: ID!, claims: [ClaimBulkCreateInput!]!): ClaimBulkCreateResult! @authRequired
  poolClaimBulkUpdate(errorPolicy: ErrorPolicyEnum, poolId: ID!, claims: [ClaimBulkUpdateInput!]!): ClaimBulkUpdateResult! @authRequired
  poolClaimBulkDelete(poolId: ID!, claimIds: [ID!]!): ClaimBulkDeleteResult! @authRequired

  # Pools
  poolCreate(input: PoolCreateInput!): PoolCreateResult!
  poolUpdate(id: ID!, input: PoolUpdateInput!): PoolUpdateResult! @authRequired
  poolDelete(id: ID!): PoolDeleteResult! @authRequired
}
