"""
Any field decorated with the @experimental directive should not be used in production.
It will not conform to our rules around breaking changes.
"""
directive @experimental on FIELD_DEFINITION

directive @goField(
  forceResolver: Boolean
  name: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @authRequired on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @basicAuth(allowed: [BasicAuthType!]!) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @frontendBuildAuth on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @scrub on INPUT_FIELD_DEFINITION

directive @restrictEnvironment(
  allowed: [String!]!
) on INPUT_FIELD_DEFINITION | INPUT_OBJECT | FIELD_DEFINITION | OBJECT

directive @goGqlId(fields: [String!]!) on OBJECT

directive @goEmbedHelper on OBJECT

scalar Time
scalar Address
scalar PubKey
scalar DBID
scalar Email
scalar HexString
scalar JSON

enum ErrorPolicyEnum {
  IGNORE_FAILED
  REJECT_EVERYTHING
  REJECT_FAILED_ROWS
}

enum BasicAuthType {
  Retool
  Monitoring
}

interface Node {
  id: ID!
}

type DeletedNode implements Node {
  id: ID!
  dbid: DBID!
}

interface Error {
  message: String!
}

type ChainAddress {
  address: Address
  chainId: Int
}

type ChainPubKey {
  pubKey: PubKey
  chainId: Int
}

type ChainPools {
  chainId: Int
  pools: [Pool]
}

input ChainAddressInput {
  address: Address! @goField(forceResolver: true)
  chainId: Int! @goField(forceResolver: true)
}

input ChainPubKeyInput {
  pubKey: PubKey! @goField(forceResolver: true)
  chainId: Int! @goField(forceResolver: true)
}

#-------------------------------------------------------------------------------
# PAGINATION
#-------------------------------------------------------------------------------

type PageInfo {
  total: Int
  size: Int!
  hasPreviousPage: Boolean!
  hasNextPage: Boolean!
  startCursor: String!
  endCursor: String!
}

#-------------------------------------------------------------------------------
# ACCOUNT AND CONTRACTS
#-------------------------------------------------------------------------------

enum EVMAccountType {
  EOA
  Contract
}

type EVMAccount {
  id: ID!
  address: Address!
  accountType: EVMAccountType!
  selfPools: [Pool!] @goField(forceResolver: true)
  balances: [TokenBalance!] @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

type PoolFactory {
  id: ID!
  address: Address!
  chainId: Int!
  poolCount: Int!
  owner: EVMAccount!
  createdAt: Time!
  updatedAt: Time!
}

type ExtensionRegistry {
  id: ID!
  address: Address!
  chainId: Int!
  extensionCount: Int!
  owner: EVMAccount! @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# USER
#-------------------------------------------------------------------------------

enum Role {
  ADMIN
  BETA_TESTER
  EARLY_ACCESS
}

type User implements Node @goEmbedHelper {
  id: ID!
  dbid: DBID!
  roles: [Role] @goField(forceResolver: true)
  pools: [Pool] @goField(forceResolver: true)
}

union UserOrAccount = User | EVMAccount

type UserEdge {
  node: User
  cursor: String
}

type UsersConnection {
  edges: [UserEdge]
  pageInfo: PageInfo!
}

#-------------------------------------------------------------------------------
# VIEWER
#-------------------------------------------------------------------------------

type Viewer implements Node @goGqlId(fields: ["userId"]) @goEmbedHelper {
  id: ID!
  user: User @goField(forceResolver: true)
  pools: [Pool] @goField(forceResolver: true)
  notifications(before: String, after: String, first: Int, last: Int): NotificationsConnection
  @goField(forceResolver: true)
  notificationSettings: NotificationSettings @goField(forceResolver: true)
}

# -------------------------------------------------------------------------------
# TOKEN
#-------------------------------------------------------------------------------

enum TokenType {
  ERC20
}

type Token {
  id: ID!
  address: Address!
  chainId: Int!
  tokenType: TokenType!
  symbol: String!
  name: String!
  decimals: Int!
  logo: String
  thumbnail: String
  validated: Int
  possibleSpam: Boolean
  createdAt: Time!
  updatedAt: Time!
}

type TokenBalance {
  id: ID!
  chainId: Int!
  token: Token! @goField(forceResolver: true)
  holder: PoolOrUserOrEVMAccount! @goField(forceResolver: true)
  amount: HexString!
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# EXTENSION
#-------------------------------------------------------------------------------

enum ExtensionType {
  State
  Strategy
}

type Extension {
  id: ID!
  address: Address!
  chainId: Int!
  extensionRegistry: ExtensionRegistry! @goField(forceResolver: true)
  extensionId: String!
  extensionType: ExtensionType!
  permissions: [String!]
  data: JSON
  name: String!
  description: String!
  createdAt: Time!
  updatedAt: Time!
}

type Claim implements Node {
  id: ID!
  dbid: DBID!
  data: JSON
  label: String!
  path: String!
  childrenCount: Int!
  parent: Claim @goField(forceResolver: true)
  children: [Claim!] @goField(forceResolver: true)
  pool: Pool! @goField(forceResolver: true)
  recipient: PoolOrUserOrEVMAccount @goField(forceResolver: true)
  state: Extension! @goField(forceResolver: true)
  strategy: Extension! @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# POOL
#-------------------------------------------------------------------------------

enum PoolStatus {
  Draft
  Active
  Paused
}

type Pool implements Node {
  id: ID!
  dbid: DBID!
  name: String!
  description: String!
  image: String!
  donationBps: Int!
  slug: String!
  status: PoolStatus!
  owner: UserOrAccount! @goField(forceResolver: true)
  contract: PoolContract @goField(forceResolver: true)
  claims: [Claim!] @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

union PoolOrUserOrEVMAccount = Pool | User | EVMAccount

type PoolContract {
  id: ID!
  address: Address!
  chainId: Int!
  status: PoolStatus!
  poolFactory: PoolFactory! @goField(forceResolver: true)
  account: EVMAccount! @goField(forceResolver: true)
  owner: EVMAccount! @goField(forceResolver: true)
  dayBalance: [PoolDayBalance!]! @goField(forceResolver: true)
  hourBalance: [PoolHourBalance!]! @goField(forceResolver: true)
  deposits: [Deposit!]! @goField(forceResolver: true)
  withdrawals: [Withdrawal!]! @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
}

type PoolDayBalance {
  id: ID!
  chainId: Int!
  date: Time!
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  amount: HexString!
  createdAt: Time!
  updatedAt: Time!
}

type PoolHourBalance {
  id: ID!
  chainId: Int!
  date: Time!
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  amount: HexString!
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# NOTIFICATIONS
#-------------------------------------------------------------------------------

type NotificationEdge {
  node: Notification
  cursor: String
}

type NotificationsConnection @goEmbedHelper {
  edges: [NotificationEdge]
  unseenCount: Int
  pageInfo: PageInfo
}

type NotificationSettings {
  someoneViewedYourPool: Boolean
}

input NotificationSettingsInput {
  someoneViewedYourPool: Boolean
}

#-------------------------------------------------------------------------------
# EMAIL
#-------------------------------------------------------------------------------

enum EmailVerificationStatus {
  Unverified
  Verified
  Failed
  Admin
}

enum EmailUnsubscriptionType {
  All
  Notifications
}

type UserEmail {
  email: Email
  verificationStatus: EmailVerificationStatus
  emailNotificationSettings: EmailNotificationSettings @goField(forceResolver: true)
}

type EmailNotificationSettings {
  unsubscribedFromAll: Boolean!
  unsubscribedFromNotifications: Boolean!
}

input UpdateEmailNotificationSettingsInput {
  unsubscribedFromAll: Boolean!
  unsubscribedFromNotifications: Boolean!
}

input UnsubscribeFromEmailTypeInput {
  type: EmailUnsubscriptionType!
  token: String! @scrub
}

#-------------------------------------------------------------------------------
# EVENT
#-------------------------------------------------------------------------------

enum ReportWindow {
  LAST_5_DAYS
  LAST_7_DAYS
  ALL_TIME
}

type Tx {
  id: ID!
  gasUsed: HexString!
  gasPrice: HexString!
  createdAt: Time!
  updatedAt: Time!
  deposits: [Deposit]! @goField(forceResolver: true)
  withdrawals: [Withdrawal]! @goField(forceResolver: true)
}

type Deposit {
  id: ID!
  transaction: Tx! @goField(forceResolver: true)
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  from: Address!
  to: Address!
  origin: String!
  amount: HexString!
  logIndex: Int
  createdAt: Time!
  updatedAt: Time!
}

type Withdrawal {
  id: ID!
  transaction: Tx! @goField(forceResolver: true)
  pool: Pool! @goField(forceResolver: true)
  token: Token! @goField(forceResolver: true)
  from: Address!
  to: Address!
  origin: String!
  amount: HexString!
  logIndex: Int
  createdAt: Time!
  updatedAt: Time!
}

#-------------------------------------------------------------------------------
# SEARCH
#-------------------------------------------------------------------------------

type UserSearchResult {
  user: User
}

type SearchUsersPayload {
  results: [UserSearchResult!]
}

type PoolSearchResult {
  pool: Pool
}

type SearchPoolsPayload {
  results: [PoolSearchResult!]
}

#-------------------------------------------------------------------------------
# ERRORS
#-------------------------------------------------------------------------------

type ErrAuthenticationFailed implements Error {
  message: String!
}

type ErrUserAlreadyExists implements Error {
  message: String!
}

type ErrUsernameNotAvailable implements Error {
  message: String!
}

type ErrAddressOwnedByUser implements Error {
  message: String!
}

type ErrUserNotFound implements Error {
  message: String!
}

type ErrPoolNotFound implements Error {
  message: String!
}

type ErrTokenNotFound implements Error {
  message: String!
}

type ErrInvalidInput implements Error {
  message: String!
  parameters: [String!]!
  reasons: [String!]!
}

type ErrNoCookie implements Error {
  message: String!
}

type ErrInvalidToken implements Error {
  message: String!
}

type ErrSessionInvalidated implements Error {
  message: String!
}

type ErrDoesNotOwnRequiredToken implements Error {
  message: String!
}

union AuthorizationError =
  ErrNoCookie
  | ErrInvalidToken
  | ErrSessionInvalidated
  | ErrDoesNotOwnRequiredToken

type ErrNotAuthorized implements Error {
  message: String!
  cause: AuthorizationError!
}

type ErrSyncFailed implements Error {
  message: String!
}

type ErrPushTokenBelongsToAnotherUser implements Error {
  message: String!
}

#-------------------------------------------------------------------------------
# AUTH MECHANISMS
#-------------------------------------------------------------------------------

input AuthMechanism {
  eoa: EoaAuth
  gnosisSafe: GnosisSafeAuth
  debug: DebugAuth
  magicLink: MagicLinkAuth
  oneTimeLoginToken: OneTimeLoginTokenAuth
  privy: PrivyAuth
}

input EoaAuth {
  chainPubKey: ChainPubKeyInput!
  nonce: String!
  message: String!
  signature: String! @scrub
}

input DebugAuth @restrictEnvironment(allowed: ["local", "development", "sandbox"]) {
  asUsername: String
  userId: DBID
  chainAddresses: [ChainAddressInput!]
  debugToolsPassword: String
}

input GnosisSafeAuth {
  address: Address!
  nonce: String!
  message: String!
}

input MagicLinkAuth {
  token: String!
}

input PrivyAuth {
  token: String!
}

input OneTimeLoginTokenAuth {
  token: String!
}

#-------------------------------------------------------------------------------
# NOTIFICATIONS
#-------------------------------------------------------------------------------

interface Notification implements Node {
  id: ID!
  seen: Boolean
  creationTime: Time
  updatedTime: Time
}

type GroupNotificationUserEdge {
  node: User
  cursor: String
}

type GroupNotificationUsersConnection @goEmbedHelper {
  edges: [GroupNotificationUserEdge]
  pageInfo: PageInfo
}

#-------------------------------------------------------------------------------
# QUERY
#-------------------------------------------------------------------------------

union ViewerResult = Viewer | ErrNotAuthorized
union UserResult = User | ErrUserNotFound | ErrInvalidInput
union PoolResult = Pool | ErrPoolNotFound | ErrInvalidInput
union SearchUsersResult = SearchUsersPayload | ErrInvalidInput
union SearchPoolsResult = SearchPoolsPayload | ErrInvalidInput

type Query {
  node(id: ID!): Node
  viewer: ViewerResult! @authRequired
  userByUsername(username: String!): UserResult!
  userById(id: DBID!): UserResult!
  userByAddress(chainAddress: ChainAddressInput!): UserResult!

  """Look up a pool by ID, slug, or contract ID."""
  pool(
    id: DBID
    slug: String
    contractId: DBID
  ): PoolResult!

  searchUsers(
    query: String!
    limit: Int
    usernameWeight: Float
  ): SearchUsersResult!

  searchPools(
    query: String!
    limit: Int
    nameWeight: Float
    descriptionWeight: Float
  ): SearchPoolsResult!

  isEmailAddressAvailable(emailAddress: Email!): Boolean

  usersByRole(role: Role!, before: String, after: String, first: Int, last: Int): UsersConnection
  @basicAuth(allowed: [Retool])
}

#-------------------------------------------------------------------------------
# MUTATIONS
#-------------------------------------------------------------------------------

type Nonce {
  nonce: String
  message: String
}

# USER MUTATIONS

type UserRegisterPayload {
  user: User!
  requiresConfirmation: Boolean
}

input UserRegisterInput {
  authMechanism: AuthMechanism!
}

union UserRegisterResult = UserRegisterPayload | ErrAuthenticationFailed | ErrUserAlreadyExists | ErrInvalidInput | ErrDoesNotOwnRequiredToken

type UserUpdatePayload {
  user: User!
}

input UserUpdateInput {
  username: String
}

union UserUpdateResult = UserUpdatePayload | ErrNotAuthorized | ErrUsernameNotAvailable | ErrInvalidInput

type UserDeletePayload {
  user: User
}

union UserDeleteResult = UserDeletePayload | ErrNotAuthorized | ErrInvalidInput

# WALLET MUTATIONS

type AddUserWalletPayload {
  viewer: Viewer!
}

union AddUserWalletResult = AddUserWalletPayload | ErrAuthenticationFailed | ErrNotAuthorized | ErrInvalidInput | ErrAddressOwnedByUser

type RemoveUserWalletsPayload {
  viewer: Viewer!
}

union RemoveUserWalletsResult = RemoveUserWalletsPayload | ErrNotAuthorized | ErrInvalidInput

# AUTH MUTATIONS

type LoginPayload {
  viewer: Viewer!
}

union LoginResult = LoginPayload | ErrUserNotFound | ErrAuthenticationFailed | ErrDoesNotOwnRequiredToken

type LogoutPayload {
  viewer: Viewer
}

type VerifyTokenPayload {
  user: User!
  isValid: Boolean!
}

union VerifyTokenResult = VerifyTokenPayload | ErrNotAuthorized | ErrInvalidInput

# PUSH TOKEN MUTATIONS

type PushTokenRegisterPayload {
  pushToken: String!
  user: User!
}

union PushTokenRegisterResult = PushTokenRegisterPayload | ErrNotAuthorized | ErrInvalidInput | ErrPushTokenBelongsToAnotherUser

type PushTokenUnregisterPayload {
  pushToken: String!
  user: User!
}

union PushTokenUnregisterResult = PushTokenUnregisterPayload | ErrNotAuthorized | ErrInvalidInput

# NOTIFICATION MUTATIONS

type NotificationSettingsUpdatePayload {
  notificationSettings: NotificationSettings!
}

union NotificationSettingsUpdateResult = NotificationSettingsUpdatePayload | ErrNotAuthorized | ErrInvalidInput

type ClearNotificationsPayload {
  notifications: [Notification]!
}

union ClearNotificationsResult = ClearNotificationsPayload | ErrNotAuthorized

# EMAIL MUTATIONS

type EmailNotificationSettingsUpdatePayload {
  emailNotificationSettings: EmailNotificationSettings!
}

union EmailNotificationSettingsUpdateResult = EmailNotificationSettingsUpdatePayload | ErrNotAuthorized | ErrInvalidInput

type VerifyEmailPayload {
  email: Email!
}

union VerifyEmailResult = VerifyEmailPayload | ErrInvalidInput

enum PreverifyEmailStatus {
  Invalid
  Risky
  Valid
}

type PreverifyEmailPayload {
  email: Email!
  result: PreverifyEmailStatus!
}

union PreverifyEmailResult = PreverifyEmailPayload | ErrInvalidInput

type UpdateEmailPayload {
  viewer: Viewer!
}

union UpdateEmailResult = UpdateEmailPayload | ErrNotAuthorized | ErrInvalidInput

type ResendVerificationEmailPayload {
  viewer: Viewer!
}

union ResendVerificationEmailResult = ResendVerificationEmailPayload | ErrNotAuthorized | ErrInvalidInput

type UnsubscribeFromEmailPayload {
  viewer: Viewer!
}

union UnsubscribeFromEmailResult = UnsubscribeFromEmailPayload | ErrInvalidInput

# ROLE MUTATIONS

type RoleUpdatePayload {
  user: User!
}

input RoleUpdateInput {
  addRoles: [Role!]
  removeRoles: [Role!]
}

union RoleUpdateResult = RoleUpdatePayload | ErrNotAuthorized | ErrInvalidInput

# CLAIM MUTATIONS

type ClaimCreatePayload {
  claim: Claim!
}

input ClaimCreateInput {
  label: String!
  recipientAddress: Address
  data: JSON
  parent: String
  children: [String!]
  stateId: String!
  strategyId: String!
}

union ClaimCreateResult = ClaimCreatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimUpdatePayload {
  claim: Claim!
}

input ClaimUpdateInput {
  claimId: DBID!
  recipientAddress: Address
  data: JSON
  parent: DBID
  children: [DBID!]
  stateId: String
  strategyId: String
}

union ClaimUpdateResult = ClaimUpdatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimDeletePayload {
  claim: Claim!
}

union ClaimDeleteResult = ClaimDeletePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimBulkCreatePayload {
  count: Int!
  claims: [Claim!]!
}

input ClaimBulkCreateInput {
  recipientAddress: Address
  data: JSON
  parent: DBID
  children: [DBID!]
  stateId: String!
  strategyId: String!
}

union ClaimBulkCreateResult = ClaimBulkCreatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimBulkUpdatePayload {
  count: Int!
  claims: [Claim!]!
}

input ClaimBulkUpdateInput {
  claimId: DBID!
  recipientAddress: Address
  data: JSON
  parent: DBID
  children: [DBID!]
  stateId: String
  strategyId: String
}

union ClaimBulkUpdateResult = ClaimBulkUpdatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type ClaimBulkDeletePayload {
  count: Int!
}

union ClaimBulkDeleteResult = ClaimBulkDeletePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

# POOL MUTATIONS

type PoolCreatePayload {
  pool: Pool!
}

input PoolCreateInput {
  owner: String
  private: Boolean
  name: String!
  description: String!
  image: String
  donationBps: Int
  slug: String!
  addClaims: [ClaimCreateInput!]
}

union PoolCreateResult = PoolCreatePayload | ErrNotAuthorized | ErrInvalidInput

type PoolUpdatePayload {
  pool: Pool!
}

input PoolUpdateInput {
  private: Boolean
  name: String
  description: String
  image: String
  donationBps: Int
  slug: String
  addClaims: [ClaimCreateInput!]
  updateClaims: [ClaimUpdateInput!]
  removeClaims: [DBID!]
}

union PoolUpdateResult = PoolUpdatePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type PoolDeletePayload {
  pool: Pool!
}

union PoolDeleteResult = PoolDeletePayload | ErrNotAuthorized | ErrInvalidInput | ErrPoolNotFound

type Mutation {
  # User
  userRegister(input: UserRegisterInput!): UserRegisterResult!
  userUpdate(userId: DBID, input: UserUpdateInput!): UserUpdateResult! @authRequired
  userRequestDeletion(redirectUrl: String!): UserDeleteResult! @authRequired
  userDelete(token: String!): UserDeleteResult! @authRequired

  # Auth
  login(authMechanism: AuthMechanism!): LoginResult!
  logout: LogoutPayload!
  tokenVerify(token: String!): VerifyTokenResult! @authRequired

  # Wallets
  addUserWallet(authMechanism: AuthMechanism!): AddUserWalletResult! @authRequired
  removeUserWallets(walletIds: [DBID!]!): RemoveUserWalletsResult! @authRequired

  # Push Tokens
  pushTokenRegister(pushToken: String!): PushTokenRegisterResult! @authRequired
  pushTokenUnregister(pushToken: String!): PushTokenUnregisterResult! @authRequired

  # Notifications
  notificationSettingsUpdate(settings: NotificationSettingsInput!): NotificationSettingsUpdateResult! @authRequired
  clearNotifications: ClearNotificationsResult! @authRequired

  # Email
  emailNotificationSettingsUpdate(settings: UpdateEmailNotificationSettingsInput!): EmailNotificationSettingsUpdateResult! @authRequired
  verifyEmail(token: String!): VerifyEmailResult!
  preverifyEmail(email: Email!): PreverifyEmailResult!
  updateEmail(email: Email!, authMechanism: AuthMechanism): UpdateEmailResult! @authRequired
  resendVerificationEmail: ResendVerificationEmailResult! @authRequired
  unsubscribeFromEmail(input: UnsubscribeFromEmailTypeInput!): UnsubscribeFromEmailResult!

  # Roles
  roleUpdate(role: Role!, input: RoleUpdateInput!): RoleUpdateResult! @authRequired

  # Claims
  poolClaimCreate(poolId: DBID!, input: ClaimCreateInput!): ClaimCreateResult! @authRequired
  poolClaimUpdate(poolId: DBID!, input: ClaimUpdateInput!): ClaimUpdateResult! @authRequired
  poolClaimDelete(poolId: DBID!, claimId: DBID!): ClaimDeleteResult! @authRequired
  poolClaimBulkCreate(errorPolicy: ErrorPolicyEnum, poolId: DBID!, claims: [ClaimBulkCreateInput!]!): ClaimBulkCreateResult! @authRequired
  poolClaimBulkUpdate(errorPolicy: ErrorPolicyEnum, poolId: DBID!, claims: [ClaimBulkUpdateInput!]!): ClaimBulkUpdateResult! @authRequired
  poolClaimBulkDelete(poolId: DBID!, claimIds: [DBID!]!): ClaimBulkDeleteResult! @authRequired

  # Pools
  poolCreate(input: PoolCreateInput!): PoolCreateResult!
  poolUpdate(id: DBID!, input: PoolUpdateInput!): PoolUpdateResult! @authRequired
  poolDelete(id: DBID!): PoolDeleteResult! @authRequired
}

type Subscription {
  notificationCreated: Notification
  notificationUpdated: Notification
}