package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/mutuals/go-mutuals/graphql/generated"
	"github.com/mutuals/go-mutuals/graphql/model"
	"github.com/mutuals/go-mutuals/publicapi"
	"github.com/mutuals/go-mutuals/service/auth"
	"github.com/mutuals/go-mutuals/service/emails"
	"github.com/mutuals/go-mutuals/service/logger"
	"github.com/mutuals/go-mutuals/service/persist"
	"github.com/mutuals/go-mutuals/util"
)

// SelfPools is the resolver for the selfPools field.
func (r *accountResolver) SelfPools(ctx context.Context, obj *model.Account) ([]*model.Pool, error) {
	panic(fmt.Errorf("not implemented: SelfPools - selfPools"))
}

// Balances is the resolver for the balances field.
func (r *accountResolver) Balances(ctx context.Context, obj *model.Account) ([]*model.TokenBalance, error) {
	panic(fmt.Errorf("not implemented: Balances - balances"))
}

// ChainID is the resolver for the chainId field.
func (r *chainAddressResolver) ChainID(ctx context.Context, obj *persist.ChainAddress) (*int, error) {
	panic(fmt.Errorf("not implemented: ChainID - chainId"))
}

// ChainID is the resolver for the chainId field.
func (r *chainPubKeyResolver) ChainID(ctx context.Context, obj *persist.ChainPubKey) (*int, error) {
	panic(fmt.Errorf("not implemented: ChainID - chainId"))
}

// Parent is the resolver for the parent field.
func (r *claimResolver) Parent(ctx context.Context, obj *model.Claim) (*model.Claim, error) {
	panic(fmt.Errorf("not implemented: Parent - parent"))
}

// Pool is the resolver for the pool field.
func (r *claimResolver) Pool(ctx context.Context, obj *model.Claim) (*model.Pool, error) {
	panic(fmt.Errorf("not implemented: Pool - pool"))
}

// Recipient is the resolver for the recipient field.
func (r *claimResolver) Recipient(ctx context.Context, obj *model.Claim) (model.PoolOrMutualsUserOrAccount, error) {
	panic(fmt.Errorf("not implemented: Recipient - recipient"))
}

// State is the resolver for the state field.
func (r *claimResolver) State(ctx context.Context, obj *model.Claim) (*model.Extension, error) {
	panic(fmt.Errorf("not implemented: State - state"))
}

// Strategy is the resolver for the strategy field.
func (r *claimResolver) Strategy(ctx context.Context, obj *model.Claim) (*model.Extension, error) {
	panic(fmt.Errorf("not implemented: Strategy - strategy"))
}

// Transaction is the resolver for the transaction field.
func (r *depositResolver) Transaction(ctx context.Context, obj *model.Deposit) (*model.Tx, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// Pool is the resolver for the pool field.
func (r *depositResolver) Pool(ctx context.Context, obj *model.Deposit) (*model.Pool, error) {
	panic(fmt.Errorf("not implemented: Pool - pool"))
}

// Token is the resolver for the token field.
func (r *depositResolver) Token(ctx context.Context, obj *model.Deposit) (*model.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// ExtensionRegistry is the resolver for the extensionRegistry field.
func (r *extensionResolver) ExtensionRegistry(ctx context.Context, obj *model.Extension) (*model.ExtensionRegistry, error) {
	panic(fmt.Errorf("not implemented: ExtensionRegistry - extensionRegistry"))
}

// Owner is the resolver for the owner field.
func (r *extensionRegistryResolver) Owner(ctx context.Context, obj *model.ExtensionRegistry) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// AddUserWallet is the resolver for the addUserWallet field.
func (r *mutationResolver) AddUserWallet(ctx context.Context, chainAddress persist.ChainAddress, authMechanism model.AuthMechanism) (model.AddUserWalletPayloadOrError, error) {
	api := publicapi.For(ctx)

	authenticator, err := r.authMechanismToAuthenticator(ctx, authMechanism)
	if err != nil {
		return nil, err
	}

	err = api.User.AddWalletToUser(ctx, chainAddress, authenticator)
	if err != nil {
		return nil, err
	}

	output := &model.AddUserWalletPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// RemoveUserWallets is the resolver for the removeUserWallets field.
func (r *mutationResolver) RemoveUserWallets(ctx context.Context, walletIds []persist.DBID) (model.RemoveUserWalletsPayloadOrError, error) {
	api := publicapi.For(ctx)

	err := api.User.RemoveWalletsFromUser(ctx, walletIds)
	if err != nil {
		return nil, err
	}

	output := &model.RemoveUserWalletsPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// UpdateUserInfo is the resolver for the updateUserInfo field.
func (r *mutationResolver) UpdateUserInfo(ctx context.Context, input model.UpdateUserInfoInput) (model.UpdateUserInfoPayloadOrError, error) {
	api := publicapi.For(ctx)

	err := api.User.UpdateUserInfo(ctx, input.Username)
	if err != nil {
		return nil, err
	}

	output := &model.UpdateUserInfoPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// RegisterUserPushToken is the resolver for the registerUserPushToken field.
func (r *mutationResolver) RegisterUserPushToken(ctx context.Context, pushToken string) (model.RegisterUserPushTokenPayloadOrError, error) {
	_, err := publicapi.For(ctx).User.CreatePushTokenForUser(ctx, pushToken)
	if err != nil {
		return nil, err
	}

	output := &model.RegisterUserPushTokenPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// UnregisterUserPushToken is the resolver for the unregisterUserPushToken field.
func (r *mutationResolver) UnregisterUserPushToken(ctx context.Context, pushToken string) (model.UnregisterUserPushTokenPayloadOrError, error) {
	err := publicapi.For(ctx).User.DeletePushTokenByPushToken(ctx, pushToken)
	if err != nil {
		return nil, err
	}

	output := &model.UnregisterUserPushTokenPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// GetAuthNonce is the resolver for the getAuthNonce field.
func (r *mutationResolver) GetAuthNonce(ctx context.Context) (model.GetAuthNoncePayloadOrError, error) {
	nonce, message, err := publicapi.For(ctx).Auth.GetAuthNonce(ctx)
	if err != nil {
		return nil, err
	}

	output := &model.AuthNonce{
		Nonce:   &nonce,
		Message: &message,
	}

	return output, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, authMechanism model.AuthMechanism, input model.CreateUserInput) (model.CreateUserPayloadOrError, error) {
	authenticator, err := r.authMechanismToAuthenticator(ctx, authMechanism)
	if err != nil {
		return nil, err
	}

	userName := ""
	if input.Username != nil {
		userName = *input.Username
	}

	var email *persist.Email
	if input.Email != nil {
		it := *input.Email
		email = &it
	}

	_, err = publicapi.For(ctx).User.CreateUser(ctx, authenticator, userName, email)
	if err != nil {
		return nil, err
	}

	output := &model.CreateUserPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// UpdateEmail is the resolver for the updateEmail field.
func (r *mutationResolver) UpdateEmail(ctx context.Context, input model.UpdateEmailInput) (model.UpdateEmailPayloadOrError, error) {
	var authenticator *auth.Authenticator

	if input.AuthMechanism != nil {
		a, err := r.authMechanismToAuthenticator(ctx, *input.AuthMechanism)
		if err != nil {
			return nil, err
		}
		authenticator = &a
	}

	return updateUserEmail(ctx, input.Email, authenticator)
}

// ResendVerificationEmail is the resolver for the resendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context) (model.ResendVerificationEmailPayloadOrError, error) {
	return resendEmailVerification(ctx)
}

// UpdateEmailNotificationSettings is the resolver for the updateEmailNotificationSettings field.
func (r *mutationResolver) UpdateEmailNotificationSettings(ctx context.Context, input model.UpdateEmailNotificationSettingsInput) (model.UpdateEmailNotificationSettingsPayloadOrError, error) {
	return updateUserEmailNotificationSettings(ctx, input)
}

// UnsubscribeFromEmailType is the resolver for the unsubscribeFromEmailType field.
func (r *mutationResolver) UnsubscribeFromEmailType(ctx context.Context, input model.UnsubscribeFromEmailTypeInput) (model.UnsubscribeFromEmailTypePayloadOrError, error) {
	return unsubscribeFromEmailType(ctx, input)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, authMechanism model.AuthMechanism) (model.LoginPayloadOrError, error) {
	authenticator, err := r.authMechanismToAuthenticator(ctx, authMechanism)
	if err != nil {
		return nil, err
	}

	_, err = publicapi.For(ctx).Auth.Login(ctx, authenticator)
	if err != nil {
		return nil, err
	}

	output := &model.LoginPayload{
		Viewer: resolveViewer(ctx),
	}
	return output, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, pushTokenToUnregister *string) (*model.LogoutPayload, error) {
	publicapi.For(ctx).Auth.Logout(ctx)

	output := &model.LogoutPayload{
		Viewer: resolveViewer(ctx),
	}

	return output, nil
}

// UpsertPool is the resolver for the upsertPool field.
func (r *mutationResolver) UpsertPool(ctx context.Context, input model.UpsertPoolInput) (model.UpsertPoolPayloadOrError, error) {
	dbPool, err := publicapi.For(ctx).Pool.UpsertPool(ctx, input)
	if err != nil {
		return nil, err
	}

	payload := model.UpsertPoolPayload{
		Pool: poolToModel(ctx, dbPool),
	}

	return payload, nil
}

// PublishPool is the resolver for the publishPool field.
func (r *mutationResolver) PublishPool(ctx context.Context, input model.PublishPoolInput) (model.PublishPoolPayloadOrError, error) {
	err := publicapi.For(ctx).Pool.PublishPool(ctx, input)
	if err != nil {
		return nil, err
	}

	pool, err := resolvePoolByPoolID(ctx, input.PoolID)
	if err != nil {
		return nil, err
	}

	return &model.PublishPoolPayload{
		Pool: pool,
	}, nil
}

// CreatePool is the resolver for the createPool field.
func (r *mutationResolver) CreatePool(ctx context.Context, input model.CreatePoolInput) (model.CreatePoolPayloadOrError, error) {
	pool, err := publicapi.For(ctx).Pool.UpsertPool(ctx, model.UpsertPoolInput{
		PoolID:      util.ToPointer(persist.GenerateID()),
		Name:        input.Name,
		Description: input.Description,
		// TODO Logo: input.Logo
		Allocations: nil, // TODO
	})
	if err != nil {
		return nil, err
	}

	output := &model.CreatePoolPayload{
		Pool: poolToModel(ctx, pool),
	}

	return output, nil
}

// UpdatePoolHidden is the resolver for the updatePoolHidden field.
func (r *mutationResolver) UpdatePoolHidden(ctx context.Context, input model.UpdatePoolHiddenInput) (model.UpdatePoolHiddenPayloadOrError, error) {
	panic(fmt.Errorf("not implemented: UpdatePoolHidden - updatePoolHidden"))
}

// DeletePool is the resolver for the deletePool field.
func (r *mutationResolver) DeletePool(ctx context.Context, poolID persist.DBID) (model.DeletePoolPayloadOrError, error) {
	panic(fmt.Errorf("not implemented: DeletePool - deletePool"))
}

// UpdatePoolOrder is the resolver for the updatePoolOrder field.
func (r *mutationResolver) UpdatePoolOrder(ctx context.Context, input model.UpdatePoolOrderInput) (model.UpdatePoolOrderPayloadOrError, error) {
	panic(fmt.Errorf("not implemented: UpdatePoolOrder - updatePoolOrder"))
}

// ClearAllNotifications is the resolver for the clearAllNotifications field.
func (r *mutationResolver) ClearAllNotifications(ctx context.Context) (*model.ClearAllNotificationsPayload, error) {
	notifications, err := publicapi.For(ctx).Notifications.ClearUserNotifications(ctx)
	if err != nil {
		return nil, err
	}

	models := make([]model.Notification, len(notifications))
	for i, n := range notifications {
		model, err := notificationToModel(n)
		if err != nil {
			return nil, err
		}
		models[i] = model
	}

	output := &model.ClearAllNotificationsPayload{
		Notifications: models,
	}
	return output, nil
}

// UpdateNotificationSettings is the resolver for the updateNotificationSettings field.
func (r *mutationResolver) UpdateNotificationSettings(ctx context.Context, settings *model.NotificationSettingsInput) (*model.NotificationSettings, error) {
	//TODO
	err := publicapi.For(ctx).User.UpdateUserNotificationSettings(ctx, persist.UserNotificationSettings{})
	if err != nil {
		return nil, err
	}
	return resolveViewerNotificationSettings(ctx)
}

// PreverifyEmail is the resolver for the preverifyEmail field.
func (r *mutationResolver) PreverifyEmail(ctx context.Context, input model.PreverifyEmailInput) (model.PreverifyEmailPayloadOrError, error) {
	// todo we could have the frontend send the source? right now I don't see any other sources of verification other than signing up
	result, err := emails.PreverifyEmail(ctx, input.Email, "signup")
	if err != nil {
		return nil, err
	}

	var modelResult model.PreverifyEmailResult

	switch result.Result {
	case emails.PreverifyEmailResultValid:
		modelResult = model.PreverifyEmailResultValid
	case emails.PreverifyEmailResultInvalid:
		modelResult = model.PreverifyEmailResultInvalid
	case emails.PreverifyEmailResultRisky:
		modelResult = model.PreverifyEmailResultRisky
	default:
		return nil, fmt.Errorf("unknown preverify result: %d", result.Result)
	}

	return model.PreverifyEmailPayload{
		Email:  input.Email,
		Result: modelResult,
	}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input model.VerifyEmailInput) (model.VerifyEmailPayloadOrError, error) {
	return verifyEmail(ctx, input.Token)
}

// VerifyEmailMagicLink is the resolver for the verifyEmailMagicLink field.
func (r *mutationResolver) VerifyEmailMagicLink(ctx context.Context, input model.VerifyEmailMagicLinkInput) (model.VerifyEmailMagicLinkPayloadOrError, error) {
	_, err := publicapi.For(ctx).User.GetUserByVerifiedEmailAddress(ctx, input.Email)

	return model.VerifyEmailMagicLinkPayload{
		CanSend: err == nil,
	}, nil
}

// OptInForRoles is the resolver for the optInForRoles field.
func (r *mutationResolver) OptInForRoles(ctx context.Context, roles []persist.Role) (model.OptInForRolesPayloadOrError, error) {
	user, err := publicapi.For(ctx).User.OptInForRoles(ctx, roles)
	if err != nil {
		return nil, err
	}

	payload := model.OptInForRolesPayload{
		User: userToModel(ctx, *user),
	}

	return payload, nil
}

// OptOutForRoles is the resolver for the optOutForRoles field.
func (r *mutationResolver) OptOutForRoles(ctx context.Context, roles []persist.Role) (model.OptOutForRolesPayloadOrError, error) {
	user, err := publicapi.For(ctx).User.OptOutForRoles(ctx, roles)
	if err != nil {
		return nil, err
	}

	payload := model.OptOutForRolesPayload{
		User: userToModel(ctx, *user),
	}

	return payload, nil
}

// AddRolesToUser is the resolver for the addRolesToUser field.
func (r *mutationResolver) AddRolesToUser(ctx context.Context, username string, roles []*persist.Role) (model.AddRolesToUserPayloadOrError, error) {
	user, err := publicapi.For(ctx).Admin.AddRolesToUser(ctx, username, roles)

	if err != nil {
		return nil, err
	}

	return userToModel(ctx, *user), nil
}

// AddWalletToUserUnchecked is the resolver for the addWalletToUserUnchecked field.
func (r *mutationResolver) AddWalletToUserUnchecked(ctx context.Context, input model.AdminAddWalletInput) (model.AdminAddWalletPayloadOrError, error) {
	err := publicapi.For(ctx).Admin.AddWalletByUsernameUnchecked(ctx, input.Username, *input.ChainAddress)
	if err != nil {
		return nil, err
	}

	user, err := publicapi.For(ctx).User.GetUserByUsername(ctx, input.Username)
	if err != nil {
		return nil, err
	}

	return model.AdminAddWalletPayload{User: userToModel(ctx, *user)}, nil
}

// RevokeRolesFromUser is the resolver for the revokeRolesFromUser field.
func (r *mutationResolver) RevokeRolesFromUser(ctx context.Context, username string, roles []*persist.Role) (model.RevokeRolesFromUserPayloadOrError, error) {
	user, err := publicapi.For(ctx).Admin.RemoveRolesFromUser(ctx, username, roles)

	if err != nil {
		return nil, err
	}

	return userToModel(ctx, *user), nil
}

// UploadPersistedQueries is the resolver for the uploadPersistedQueries field.
func (r *mutationResolver) UploadPersistedQueries(ctx context.Context, input *model.UploadPersistedQueriesInput) (model.UploadPersistedQueriesPayloadOrError, error) {
	err := publicapi.For(ctx).APQ.UploadPersistedQueries(ctx, *input.PersistedQueries)

	if err != nil {
		return nil, err
	}

	message := "Persisted queries uploaded successfully"

	return model.UploadPersistedQueriesPayload{Message: &message}, nil
}

// UpdatePrimaryWallet is the resolver for the updatePrimaryWallet field.
func (r *mutationResolver) UpdatePrimaryWallet(ctx context.Context, walletID persist.DBID) (model.UpdatePrimaryWalletPayloadOrError, error) {
	err := publicapi.For(ctx).User.UpdateUserPrimaryWallet(ctx, walletID)
	if err != nil {
		return nil, err
	}
	return model.UpdatePrimaryWalletPayload{
		Viewer: resolveViewer(ctx),
	}, nil
}

// UpdateUserExperience is the resolver for the updateUserExperience field.
func (r *mutationResolver) UpdateUserExperience(ctx context.Context, input model.UpdateUserExperienceInput) (model.UpdateUserExperiencePayloadOrError, error) {
	err := publicapi.For(ctx).User.UpdateUserExperience(ctx, input.ExperienceType, input.Experienced)
	if err != nil {
		return nil, err
	}
	return model.UpdateUserExperiencePayload{
		Viewer: resolveViewer(ctx),
	}, nil
}

// Roles is the resolver for the roles field.
func (r *mutualsUserResolver) Roles(ctx context.Context, obj *model.MutualsUser) ([]*persist.Role, error) {
	dbRoles, err := publicapi.For(ctx).User.GetUserRolesByUserID(ctx, obj.Dbid)
	if err != nil {
		return nil, err
	}

	roles := make([]*persist.Role, len(dbRoles))
	for i, role := range dbRoles {
		r := role
		roles[i] = &r
	}

	return roles, nil
}

// Accounts is the resolver for the accounts field.
func (r *mutualsUserResolver) Accounts(ctx context.Context, obj *model.MutualsUser) ([]*model.Account, error) {
	return resolveWalletsByUserID(ctx, obj.Dbid)
}

// PrimaryAccount is the resolver for the primaryAccount field.
func (r *mutualsUserResolver) PrimaryAccount(ctx context.Context, obj *model.MutualsUser) (*model.Account, error) {
	return resolvePrimaryWalletByUserID(ctx, obj.HelperMutualsUserData.UserID)
}

// Pools is the resolver for the pools field.
func (r *mutualsUserResolver) Pools(ctx context.Context, obj *model.MutualsUser) ([]*model.Pool, error) {
	return resolvePoolsByUserID(ctx, obj.HelperMutualsUserData.UserID)
}

// Owner is the resolver for the owner field.
func (r *poolResolver) Owner(ctx context.Context, obj *model.Pool) (model.MutualsUserOrAccount, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// Contract is the resolver for the contract field.
func (r *poolResolver) Contract(ctx context.Context, obj *model.Pool) (*model.PoolContract, error) {
	panic(fmt.Errorf("not implemented: Contract - contract"))
}

// Claims is the resolver for the claims field.
func (r *poolResolver) Claims(ctx context.Context, obj *model.Pool) ([]*model.Claim, error) {
	return resolveClaimsByPoolID(ctx, obj.Dbid)
}

// PoolFactory is the resolver for the poolFactory field.
func (r *poolContractResolver) PoolFactory(ctx context.Context, obj *model.PoolContract) (*model.PoolFactory, error) {
	panic(fmt.Errorf("not implemented: PoolFactory - poolFactory"))
}

// Account is the resolver for the account field.
func (r *poolContractResolver) Account(ctx context.Context, obj *model.PoolContract) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// Owner is the resolver for the owner field.
func (r *poolContractResolver) Owner(ctx context.Context, obj *model.PoolContract) (*model.Account, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// DayBalance is the resolver for the dayBalance field.
func (r *poolContractResolver) DayBalance(ctx context.Context, obj *model.PoolContract) ([]*model.PoolDayBalance, error) {
	panic(fmt.Errorf("not implemented: DayBalance - dayBalance"))
}

// HourBalance is the resolver for the hourBalance field.
func (r *poolContractResolver) HourBalance(ctx context.Context, obj *model.PoolContract) ([]*model.PoolHourBalance, error) {
	panic(fmt.Errorf("not implemented: HourBalance - hourBalance"))
}

// Deposits is the resolver for the deposits field.
func (r *poolContractResolver) Deposits(ctx context.Context, obj *model.PoolContract) ([]*model.Deposit, error) {
	panic(fmt.Errorf("not implemented: Deposits - deposits"))
}

// Withdrawals is the resolver for the withdrawals field.
func (r *poolContractResolver) Withdrawals(ctx context.Context, obj *model.PoolContract) ([]*model.Withdrawal, error) {
	panic(fmt.Errorf("not implemented: Withdrawals - withdrawals"))
}

// Pool is the resolver for the pool field.
func (r *poolDayBalanceResolver) Pool(ctx context.Context, obj *model.PoolDayBalance) (*model.Pool, error) {
	panic(fmt.Errorf("not implemented: Pool - pool"))
}

// Token is the resolver for the token field.
func (r *poolDayBalanceResolver) Token(ctx context.Context, obj *model.PoolDayBalance) (*model.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// Pool is the resolver for the pool field.
func (r *poolHourBalanceResolver) Pool(ctx context.Context, obj *model.PoolHourBalance) (*model.Pool, error) {
	panic(fmt.Errorf("not implemented: Pool - pool"))
}

// Token is the resolver for the token field.
func (r *poolHourBalanceResolver) Token(ctx context.Context, obj *model.PoolHourBalance) (*model.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id model.GqlID) (model.Node, error) {
	return nodeFetcher.GetNodeByGqlID(ctx, id)
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (model.ViewerOrError, error) {
	return resolveViewer(ctx), nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (model.UserByUsernameOrError, error) {
	return resolveMutualsUserByUsername(ctx, username)
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id persist.DBID) (model.UserByIDOrError, error) {
	return resolveMutualsUserByUserID(ctx, id)
}

// UserByAddress is the resolver for the userByAddress field.
func (r *queryResolver) UserByAddress(ctx context.Context, chainAddress persist.ChainAddress) (model.UserByAddressOrError, error) {
	return resolveMutualsUserByAddress(ctx, chainAddress)
}

// PoolByID is the resolver for the poolById field.
func (r *queryResolver) PoolByID(ctx context.Context, id persist.DBID) (model.PoolByIDPayloadOrError, error) {
	pool, err := resolvePoolByPoolID(ctx, id)

	if err != nil {
		return nil, err
	}

	return pool, nil
}

// ViewerPoolByID is the resolver for the viewerPoolById field.
func (r *queryResolver) ViewerPoolByID(ctx context.Context, id persist.DBID) (model.ViewerPoolByIDPayloadOrError, error) {
	pool, err := resolveViewerPoolByPoolID(ctx, id)

	if err != nil {
		return nil, err
	}

	return pool, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, limit *int, usernameWeight *float64) (model.SearchUsersPayloadOrError, error) {
	panic(fmt.Errorf("not implemented: SearchUsers - searchUsers"))
}

// SearchPools is the resolver for the searchPools field.
func (r *queryResolver) SearchPools(ctx context.Context, query string, limit *int, nameWeight *float64, descriptionWeight *float64) (model.SearchPoolsPayloadOrError, error) {
	panic(fmt.Errorf("not implemented: SearchPools - searchPools"))
}

// IsEmailAddressAvailable is the resolver for the isEmailAddressAvailable field.
func (r *queryResolver) IsEmailAddressAvailable(ctx context.Context, emailAddress persist.Email) (*bool, error) {
	exists, err := publicapi.For(ctx).User.VerifiedEmailAddressExists(ctx, emailAddress)
	if err != nil {
		return nil, err
	}

	available := !exists
	return &available, nil
}

// UsersByRole is the resolver for the usersByRole field.
func (r *queryResolver) UsersByRole(ctx context.Context, role persist.Role, before *string, after *string, first *int, last *int) (*model.UsersConnection, error) {
	users, pageInfo, err := publicapi.For(ctx).User.PaginateUsersWithRole(ctx, role, before, after, first, last)
	if err != nil {
		return nil, err
	}

	return &model.UsersConnection{
		Edges:    usersToEdges(ctx, users),
		PageInfo: pageInfoToModel(ctx, pageInfo),
	}, nil
}

// NewNotification is the resolver for the newNotification field.
func (r *subscriptionResolver) NewNotification(ctx context.Context) (<-chan model.Notification, error) {
	return resolveNewNotificationSubscription(ctx), nil
}

// NotificationUpdated is the resolver for the notificationUpdated field.
func (r *subscriptionResolver) NotificationUpdated(ctx context.Context) (<-chan model.Notification, error) {
	return resolveUpdatedNotificationSubscription(ctx), nil
}

// Token is the resolver for the token field.
func (r *tokenBalanceResolver) Token(ctx context.Context, obj *model.TokenBalance) (*model.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// Holder is the resolver for the holder field.
func (r *tokenBalanceResolver) Holder(ctx context.Context, obj *model.TokenBalance) (model.PoolOrMutualsUserOrAccount, error) {
	panic(fmt.Errorf("not implemented: Holder - holder"))
}

// Deposits is the resolver for the deposits field.
func (r *txResolver) Deposits(ctx context.Context, obj *model.Tx) ([]*model.Deposit, error) {
	panic(fmt.Errorf("not implemented: Deposits - deposits"))
}

// Withdrawals is the resolver for the withdrawals field.
func (r *txResolver) Withdrawals(ctx context.Context, obj *model.Tx) ([]*model.Withdrawal, error) {
	panic(fmt.Errorf("not implemented: Withdrawals - withdrawals"))
}

// EmailNotificationSettings is the resolver for the emailNotificationSettings field.
func (r *userEmailResolver) EmailNotificationSettings(ctx context.Context, obj *model.UserEmail) (*model.EmailNotificationSettings, error) {
	unsubs, err := publicapi.For(ctx).User.GetCurrentUserEmailNotificationSettings(ctx)
	if err != nil {
		logger.For(ctx).Errorf("error getting email notification settings from email service: %s", err)
		return obj.EmailNotificationSettings, nil
	}

	return &model.EmailNotificationSettings{
		UnsubscribedFromAll:           unsubs.All.Bool(),
		UnsubscribedFromNotifications: unsubs.Notifications.Bool(),
	}, nil
}

// User is the resolver for the user field.
func (r *viewerResolver) User(ctx context.Context, obj *model.Viewer) (*model.MutualsUser, error) {
	userID := publicapi.For(ctx).User.GetLoggedInUserId(ctx)
	return resolveMutualsUserByUserID(ctx, userID)
}

// ViewerPools is the resolver for the viewerPools field.
func (r *viewerResolver) ViewerPools(ctx context.Context, obj *model.Viewer) ([]*model.ViewerPool, error) {
	userID := publicapi.For(ctx).User.GetLoggedInUserId(ctx)

	pools, err := resolvePoolsByUserID(ctx, userID)

	if err != nil {
		return nil, err
	}

	output := make([]*model.ViewerPool, len(pools))
	for i, pool := range pools {
		output[i] = &model.ViewerPool{
			Pool: pool,
		}
	}

	return output, nil
}

// Email is the resolver for the email field.
func (r *viewerResolver) Email(ctx context.Context, obj *model.Viewer) (*model.UserEmail, error) {
	return resolveViewerEmail(ctx), nil
}

// Notifications is the resolver for the notifications field.
func (r *viewerResolver) Notifications(ctx context.Context, obj *model.Viewer, before *string, after *string, first *int, last *int) (*model.NotificationsConnection, error) {
	return resolveViewerNotifications(ctx, before, after, first, last)
}

// NotificationSettings is the resolver for the notificationSettings field.
func (r *viewerResolver) NotificationSettings(ctx context.Context, obj *model.Viewer) (*model.NotificationSettings, error) {
	return resolveViewerNotificationSettings(ctx)
}

// UserExperiences is the resolver for the userExperiences field.
func (r *viewerResolver) UserExperiences(ctx context.Context, obj *model.Viewer) ([]*model.UserExperience, error) {
	return resolveViewerExperiencesByUserID(ctx, obj.UserId)
}

// Transaction is the resolver for the transaction field.
func (r *withdrawalResolver) Transaction(ctx context.Context, obj *model.Withdrawal) (*model.Tx, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// Pool is the resolver for the pool field.
func (r *withdrawalResolver) Pool(ctx context.Context, obj *model.Withdrawal) (*model.Pool, error) {
	panic(fmt.Errorf("not implemented: Pool - pool"))
}

// Token is the resolver for the token field.
func (r *withdrawalResolver) Token(ctx context.Context, obj *model.Withdrawal) (*model.Token, error) {
	panic(fmt.Errorf("not implemented: Token - token"))
}

// Address is the resolver for the address field.
func (r *chainAddressInputResolver) Address(ctx context.Context, obj *persist.ChainAddress, data persist.Address) error {
	return obj.GQLSetAddressFromResolver(data)
}

// ChainID is the resolver for the chainId field.
func (r *chainAddressInputResolver) ChainID(ctx context.Context, obj *persist.ChainAddress, data int) error {
	panic(fmt.Errorf("not implemented: ChainID - chainId"))
}

// PubKey is the resolver for the pubKey field.
func (r *chainPubKeyInputResolver) PubKey(ctx context.Context, obj *persist.ChainPubKey, data persist.PubKey) error {
	return obj.GQLSetPubKeyFromResolver(data)
}

// ChainID is the resolver for the chainId field.
func (r *chainPubKeyInputResolver) ChainID(ctx context.Context, obj *persist.ChainPubKey, data int) error {
	panic(fmt.Errorf("not implemented: ChainID - chainId"))
}

// Account returns generated.AccountResolver implementation.
func (r *Resolver) Account() generated.AccountResolver { return &accountResolver{r} }

// ChainAddress returns generated.ChainAddressResolver implementation.
func (r *Resolver) ChainAddress() generated.ChainAddressResolver { return &chainAddressResolver{r} }

// ChainPubKey returns generated.ChainPubKeyResolver implementation.
func (r *Resolver) ChainPubKey() generated.ChainPubKeyResolver { return &chainPubKeyResolver{r} }

// Claim returns generated.ClaimResolver implementation.
func (r *Resolver) Claim() generated.ClaimResolver { return &claimResolver{r} }

// Deposit returns generated.DepositResolver implementation.
func (r *Resolver) Deposit() generated.DepositResolver { return &depositResolver{r} }

// Extension returns generated.ExtensionResolver implementation.
func (r *Resolver) Extension() generated.ExtensionResolver { return &extensionResolver{r} }

// ExtensionRegistry returns generated.ExtensionRegistryResolver implementation.
func (r *Resolver) ExtensionRegistry() generated.ExtensionRegistryResolver {
	return &extensionRegistryResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// MutualsUser returns generated.MutualsUserResolver implementation.
func (r *Resolver) MutualsUser() generated.MutualsUserResolver { return &mutualsUserResolver{r} }

// Pool returns generated.PoolResolver implementation.
func (r *Resolver) Pool() generated.PoolResolver { return &poolResolver{r} }

// PoolContract returns generated.PoolContractResolver implementation.
func (r *Resolver) PoolContract() generated.PoolContractResolver { return &poolContractResolver{r} }

// PoolDayBalance returns generated.PoolDayBalanceResolver implementation.
func (r *Resolver) PoolDayBalance() generated.PoolDayBalanceResolver {
	return &poolDayBalanceResolver{r}
}

// PoolHourBalance returns generated.PoolHourBalanceResolver implementation.
func (r *Resolver) PoolHourBalance() generated.PoolHourBalanceResolver {
	return &poolHourBalanceResolver{r}
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// TokenBalance returns generated.TokenBalanceResolver implementation.
func (r *Resolver) TokenBalance() generated.TokenBalanceResolver { return &tokenBalanceResolver{r} }

// Tx returns generated.TxResolver implementation.
func (r *Resolver) Tx() generated.TxResolver { return &txResolver{r} }

// UserEmail returns generated.UserEmailResolver implementation.
func (r *Resolver) UserEmail() generated.UserEmailResolver { return &userEmailResolver{r} }

// Viewer returns generated.ViewerResolver implementation.
func (r *Resolver) Viewer() generated.ViewerResolver { return &viewerResolver{r} }

// Withdrawal returns generated.WithdrawalResolver implementation.
func (r *Resolver) Withdrawal() generated.WithdrawalResolver { return &withdrawalResolver{r} }

// ChainAddressInput returns generated.ChainAddressInputResolver implementation.
func (r *Resolver) ChainAddressInput() generated.ChainAddressInputResolver {
	return &chainAddressInputResolver{r}
}

// ChainPubKeyInput returns generated.ChainPubKeyInputResolver implementation.
func (r *Resolver) ChainPubKeyInput() generated.ChainPubKeyInputResolver {
	return &chainPubKeyInputResolver{r}
}

type accountResolver struct{ *Resolver }
type chainAddressResolver struct{ *Resolver }
type chainPubKeyResolver struct{ *Resolver }
type claimResolver struct{ *Resolver }
type depositResolver struct{ *Resolver }
type extensionResolver struct{ *Resolver }
type extensionRegistryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type mutualsUserResolver struct{ *Resolver }
type poolResolver struct{ *Resolver }
type poolContractResolver struct{ *Resolver }
type poolDayBalanceResolver struct{ *Resolver }
type poolHourBalanceResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tokenBalanceResolver struct{ *Resolver }
type txResolver struct{ *Resolver }
type userEmailResolver struct{ *Resolver }
type viewerResolver struct{ *Resolver }
type withdrawalResolver struct{ *Resolver }
type chainAddressInputResolver struct{ *Resolver }
type chainPubKeyInputResolver struct{ *Resolver }
