rhai:
  main: "copy_cookies.rhai"

headers:
  all:
    request:
      - propagate:
          matching: .*

cors:
  allow_credentials: true
  match_origins:
    - "^https://splitfi.*.vercel.app$"
    - "http://localhost:3000"

supergraph:
  # The socket address and port to listen on.
  # Note that this must be quoted to avoid interpretation as an array in YAML.
  listen: '0.0.0.0:8000'