# Query operations
query userByIdQuery($id: DBID!) {
    userById(id: $id) {
        ... on User {
            id
            dbid
            roles
        }
        ... on ErrUserNotFound {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

query userByAddressQuery($input: ChainAddressInput!) {
    userByAddress(chainAddress: $input) {
        ... on User {
            id
            dbid
            roles
        }
        ... on ErrUserNotFound {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

query viewerQuery {
    viewer {
        ... on Viewer {
            id
            user {
                id
                dbid
                roles
            }
        }
        ... on ErrNotAuthorized {
            message
            cause {
                ... on ErrNoCookie {
                    message
                }
                ... on ErrInvalidToken {
                    message
                }
                ... on ErrSessionInvalidated {
                    message
                }
                ... on ErrDoesNotOwnRequiredToken {
                    message
                }
            }
        }
    }
}

query notificationsForViewerQuery {
    viewer {
        ... on Viewer {
            notifications(last: 1, before: null) {
                unseenCount
                edges {
                    node {
                        id
                        seen
                        creationTime
                    }
                }
                pageInfo {
                    hasNextPage
                    hasPreviousPage
                    startCursor
                    endCursor
                }
            }
        }
        ... on ErrNotAuthorized {
            message
            cause {
                ... on ErrNoCookie {
                    message
                }
                ... on ErrInvalidToken {
                    message
                }
                ... on ErrSessionInvalidated {
                    message
                }
                ... on ErrDoesNotOwnRequiredToken {
                    message
                }
            }
        }
    }
}

query poolQuery($id: DBID, $slug: String, $contractId: DBID) {
    pool(id: $id, slug: $slug, contractId: $contractId) {
        ... on Pool {
            id
            dbid
            name
            description
            status
            image
            donationBps
            slug
            owner {
                ... on User {
                    id
                    dbid
                }
                ... on EVMAccount {
                    address
                    accountType
                }
            }
            createdAt
            updatedAt
        }
        ... on ErrPoolNotFound {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

query searchUsersQuery($query: String!, $limit: Int, $usernameWeight: Float) {
    searchUsers(query: $query, limit: $limit, usernameWeight: $usernameWeight) {
        ... on SearchUsersPayload {
            results {
                user {
                    id
                    dbid
                }
            }
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

query searchPoolsQuery($query: String!, $limit: Int, $nameWeight: Float, $descriptionWeight: Float) {
    searchPools(query: $query, limit: $limit, nameWeight: $nameWeight, descriptionWeight: $descriptionWeight) {
        ... on SearchPoolsPayload {
            results {
                pool {
                    id
                    dbid
                    name
                    description
                }
            }
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

query isEmailAvailableQuery($emailAddress: Email!) {
    isEmailAddressAvailable(emailAddress: $emailAddress)
}

query usersByRoleQuery($role: Role!, $before: String, $after: String, $first: Int, $last: Int) {
    usersByRole(role: $role, before: $before, after: $after, first: $first, last: $last) {
        edges {
            node {
                id
                dbid
                roles
            }
            cursor
        }
        pageInfo {
            total
            size
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
    }
}

# Mutation operations
mutation userRegisterMutation($input: UserRegisterInput!) {
    userRegister(input: $input) {
        ... on UserRegisterPayload {
            requiresConfirmation
            user {
                id
                dbid
            }
        }
        ... on ErrAuthenticationFailed {
            message
        }
        ... on ErrUserAlreadyExists {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrDoesNotOwnRequiredToken {
            message
        }
    }
}

mutation userUpdateMutation($userId: DBID, $input: UserUpdateInput!) {
    userUpdate(userId: $userId, input: $input) {
        ... on UserUpdatePayload {
            user {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
            cause {
                ... on ErrNoCookie {
                    message
                }
                ... on ErrInvalidToken {
                    message
                }
                ... on ErrSessionInvalidated {
                    message
                }
                ... on ErrDoesNotOwnRequiredToken {
                    message
                }
            }
        }
        ... on ErrUsernameNotAvailable {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation userRequestDeletionMutation($redirectUrl: String!) {
    userRequestDeletion(redirectUrl: $redirectUrl) {
        ... on UserDeletePayload {
            user {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
            cause {
                ... on ErrNoCookie {
                    message
                }
                ... on ErrInvalidToken {
                    message
                }
            }
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation userDeleteMutation($token: String!) {
    userDelete(token: $token) {
        ... on UserDeletePayload {
            user {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation tokenVerifyMutation($token: String!) {
    tokenVerify(token: $token) {
        ... on VerifyTokenPayload {
            user {
                id
                dbid
            }
            isValid
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation pushTokenRegisterMutation($pushToken: String!) {
    pushTokenRegister(pushToken: $pushToken) {
        ... on PushTokenRegisterPayload {
            pushToken
            user {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPushTokenBelongsToAnotherUser {
            message
        }
    }
}

mutation pushTokenUnregisterMutation($pushToken: String!) {
    pushTokenUnregister(pushToken: $pushToken) {
        ... on PushTokenUnregisterPayload {
            pushToken
            user {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation notificationSettingsUpdateMutation($settings: NotificationSettingsInput!) {
    notificationSettingsUpdate(settings: $settings) {
        ... on NotificationSettingsUpdatePayload {
            notificationSettings {
                someoneViewedYourPool
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation clearNotificationsMutation {
    clearNotifications {
        ... on ClearNotificationsPayload {
            notifications {
                id
                seen
            }
        }
        ... on ErrNotAuthorized {
            message
        }
    }
}

mutation emailNotificationSettingsUpdateMutation($settings: UpdateEmailNotificationSettingsInput!) {
    emailNotificationSettingsUpdate(settings: $settings) {
        ... on EmailNotificationSettingsUpdatePayload {
            emailNotificationSettings {
                unsubscribedFromAll
                unsubscribedFromNotifications
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation poolCreateMutation($input: PoolCreateInput!) {
    poolCreate(input: $input) {
        ... on PoolCreatePayload {
            pool {
                id
                dbid
                name
                description
                image
                donationBps
                slug
                status
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

mutation poolUpdateMutation($id: DBID!, $input: PoolUpdateInput!) {
    poolUpdate(id: $id, input: $input) {
        ... on PoolUpdatePayload {
            pool {
                id
                dbid
                name
                description
                image
                donationBps
                slug
                status
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolDeleteMutation($id: DBID!) {
    poolDelete(id: $id) {
        ... on PoolDeletePayload {
            pool {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolClaimCreateMutation($poolId: DBID!, $input: ClaimCreateInput!) {
    poolClaimCreate(poolId: $poolId, input: $input) {
        ... on ClaimCreatePayload {
            claim {
                id
                dbid
                label
                path
                data
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolClaimUpdateMutation($poolId: DBID!, $input: ClaimUpdateInput!) {
    poolClaimUpdate(poolId: $poolId, input: $input) {
        ... on ClaimUpdatePayload {
            claim {
                id
                dbid
                label
                path
                data
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolClaimDeleteMutation($poolId: DBID!, $claimId: DBID!) {
    poolClaimDelete(poolId: $poolId, claimId: $claimId) {
        ... on ClaimDeletePayload {
            claim {
                id
                dbid
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolClaimBulkCreateMutation($poolId: DBID!, $claims: [ClaimBulkCreateInput!]!, $errorPolicy: ErrorPolicyEnum) {
    poolClaimBulkCreate(poolId: $poolId, claims: $claims, errorPolicy: $errorPolicy) {
        ... on ClaimBulkCreatePayload {
            count
            claims {
                id
                dbid
                label
                path
                data
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolClaimBulkUpdateMutation($poolId: DBID!, $claims: [ClaimBulkUpdateInput!]!, $errorPolicy: ErrorPolicyEnum) {
    poolClaimBulkUpdate(poolId: $poolId, claims: $claims, errorPolicy: $errorPolicy) {
        ... on ClaimBulkUpdatePayload {
            count
            claims {
                id
                dbid
                label
                path
                data
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation poolClaimBulkDeleteMutation($poolId: DBID!, $claimIds: [DBID!]!) {
    poolClaimBulkDelete(poolId: $poolId, claimIds: $claimIds) {
        ... on ClaimBulkDeletePayload {
            count
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
        ... on ErrPoolNotFound {
            message
        }
    }
}

mutation roleUpdateMutation($role: Role!, $input: RoleUpdateInput!) {
    roleUpdate(role: $role, input: $input) {
        ... on RoleUpdatePayload {
            user {
                id
                dbid
                roles
            }
        }
        ... on ErrNotAuthorized {
            message
        }
        ... on ErrInvalidInput {
            message
            parameters
            reasons
        }
    }
}

# Subscription operations
subscription notificationCreatedSubscription {
    notificationCreated {
        id
        seen
        creationTime
        updatedTime
    }
}

subscription notificationUpdatedSubscription {
    notificationUpdated {
        id
        seen
        creationTime
        updatedTime
    }
}