name: deployer
on:
  push:
    branches:
      - main
env:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1
jobs:
  deploy-dev-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install build deps"
        uses: ./.github/actions/build-deps
        with:
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          gcp-credentials-json: ${{ secrets.GCP_DEV_CREDENTIALS }}
      - name: "Deploy"
        run: make deploy-dev-backend
  deploy-prod-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install build deps"
        uses: ./.github/actions/build-deps
        with:
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          gcp-credentials-json: ${{ secrets.GCP_PROD_CREDENTIALS }}
      - name: "Deploy"
        run: make deploy-prod-backend
  deploy-dev-emails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install build deps"
        uses: ./.github/actions/build-deps
        with:
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          gcp-credentials-json: ${{ secrets.GCP_DEV_CREDENTIALS }}
      - name: "Deploy"
        run: make deploy-dev-emails
  deploy-prod-emails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install build deps"
        uses: ./.github/actions/build-deps
        with:
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          gcp-credentials-json: ${{ secrets.GCP_PROD_CREDENTIALS }}
      - name: "Deploy"
        run: make deploy-prod-emails