creation_rules:
  - age:
      - recipient: age15da8kvyw6dz0ky5cus4fgfx8e9cd6tg57xcqtlakn6a34ux4633qwru942
        enc: |
          -----BEGIN AGE ENCRYPTED FILE-----
          YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZUkvYTdIcUNNbXBJcTc0
          WFhqUFhnV014d01wR0U2a1NRUk40TitlcW5nClpsRWhzK1A0Nm82emc2NVhiaS9S
          VUdXcTJSaUs4U08rK2FKTlVXczBtdk0KLS0tIGZrQm9TK2JvZ2hBczJHeE5WclM1
          VVZvTjRYZENKUDNCL2ZNdUs3QjNVWUUKiyAnDw3CuJ7tx0Yk0rpphr4rfDio13nT
          UBdFtNWvTyKP6io9qD+YYk1QgImPmBxFv2mPOgNY4uPDCBDhT6IXqw==
          -----END AGE ENCRYPTED FILE-----